// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
// Run 'vex dev' or 'vex generate' to update this file.

/* eslint-disable perfectionist/sort-union-types */
/* eslint-disable perfectionist/sort-interfaces */
/* eslint-disable perfectionist/sort-modules */

import type { Id } from "@convex/_generated/dataModel"
import type { VexDocument, VexDocumentGlobal } from "@vexcms/core"

export type HeroBlock = {
  blockType: "hero"
  blockName?: string
  id: string
  badge?: string
  title: string
  subtitle?: string
  primaryCtaLabel?: string
  primaryCtaHref?: string
  secondaryCtaLabel?: string
  secondaryCtaHref?: string
  showImage?: boolean
  image?: string
}

export type FeatureBlock = {
  blockType: "feature"
  blockName?: string
  id: string
  icon?: string
  title: string
  description?: string
  linkLabel?: string
  linkHref?: string
}

export type CtaBlock = {
  blockType: "cta"
  blockName?: string
  id: string
  title: string
  description?: string
  buttonLabel?: string
  buttonHref?: string
  variant?: string[]
}

export type TestimonialBlock = {
  blockType: "testimonial"
  blockName?: string
  id: string
  quote: string
  authorName: string
  authorRole?: string
  authorAvatar?: string
  company?: string
  rating?: number
}

export type StatsBlock = {
  blockType: "stats"
  blockName?: string
  id: string
  title?: string
  stats?: {
    /**
     * The number or metric, e.g. '10K+' or '99.9%'.
     */
    value: string
    /**
     * What the number represents, e.g. 'Active Users'.
     */
    label: string
  }[]
}

export type LogoCloudBlock = {
  blockType: "logo-cloud"
  blockName?: string
  id: string
  title?: string
  logos?: {
    name: string
    image: string
    link?: string
  }[]
}

export type FaqBlock = {
  blockType: "faq"
  blockName?: string
  id: string
  title?: string
  questions?: {
    question: string
    /**
     * The answer text. Supports basic formatting.
     */
    answer: string
  }[]
}

export type PricingBlock = {
  blockType: "pricing"
  blockName?: string
  id: string
  planName: string
  price: string
  period?: string
  description?: string
  features?: string[]
  ctaLabel?: string
  ctaHref?: string
  highlighted?: boolean
  badge?: string
}

export type ContentBlock = {
  blockType: "content"
  blockName?: string
  id: string
  body: string
  align?: string[]
  maxWidth?: string[]
}

export type PageBlock =
  | HeroBlock
  | FeatureBlock
  | CtaBlock
  | TestimonialBlock
  | StatsBlock
  | LogoCloudBlock
  | FaqBlock
  | PricingBlock
  | ContentBlock

export type SEO = {
  metaTitle?: string
  metaDescription?: string
  ogImage?: string
}

export type InnerGroup = {
  /**
   * test field description
   */
  title?: string
  /**
   * another test description
   */
  description?: string
  queue?: {
    title?: string
    description?: string
  }[]
}

export type AnotherGroupNames = {
  title?: string
  subtitle?: string
  list?: InnerGroup[]
}

export interface Page extends VexDocument {
  _id: Id<"pages">
  /**
   * Display title shown as the page heading and in browser tabs (as fallback).
   */
  title: string
  /**
   * URL-friendly identifier. Used for routing: /<slug>. Must be unique.
   */
  slug: string
  /**
   * Page body content. Legacy field — use the blocks field for new pages.
   */
  content?: string
  blocks?: PageBlock[]
  testImage?: Id<"images">[]
  /**
   * Custom <title> tag for search engines. Falls back to the title field if empty.
   */
  metaTitle?: string
  /**
   * Summary shown in search result snippets. Keep under 160 characters for best
   * display.
   */
  metaDescription?: string
  /**
   * Image URL for Open Graph social sharing previews. Recommended 1200×630px.
   */
  ogImage?: string
  themes?: Id<"themes">[]
  /**
   * some test description.
   */
  test?: string[]
  /**
   * some test number array description
   */
  test2?: number[][]
  /**
   * seo metadata
   */
  seo?: SEO
  anotherTest?: AnotherGroupNames
}

export interface UserDocument extends VexDocument {
  _id: Id<"user">
  name: string
  email: string
  emailVerified: boolean
  image?: string
  createdAt: number
  updatedAt: number
  role?: string
  banned?: boolean
  banReason?: string
  banExpires?: number
  isAnonymous?: boolean
  userId?: string
  roles: string[]
  /**
   * something for the editor only
   */
  newUserFieldTest?: string
}

export interface Header extends VexDocument {
  _id: Id<"headers">
  /**
   * Internal identifier for this header config. Used for idempotent lookups.
   */
  name: string
  /**
   * Brand name rendered as the logo. Falls back to site settings name.
   */
  logoText?: string
  /**
   * URL the logo links to. Typically / for the home page.
   */
  logoHref?: string
  /**
   * JSON array of navigation links. Each item: { label: string, href: string }.
   * Example: [{"label":"Features","href":"/features"}]
   */
  menuItems?: string
  /**
   * JSON array of CTA buttons. Each item: { label, href, variant }. Variant options:
   * default, outline, ghost.
   */
  actionButtons?: string
}

export interface Footer extends VexDocument {
  _id: Id<"footers">
  /**
   * Internal identifier for this footer config. Used for idempotent lookups.
   */
  name: string
  /**
   * Brand name shown in the footer. Falls back to site settings name.
   */
  logoText?: string
  /**
   * Copyright line displayed at the bottom of the footer. Auto-prepends © and the
   * current year.
   */
  copyright?: string
  /**
   * JSON array of footer navigation links. Each item: { label: string, href: string
   * }. Grouped by section in the UI.
   */
  links?: string
  /**
   * JSON array of social profile links. Each item: { platform: string, href: string,
   * icon: string }. Icon maps to a Lucide icon name.
   */
  socialLinks?: string
}

export interface Theme extends VexDocument {
  _id: Id<"themes">
  /**
   * Internal identifier for this theme. Used for idempotent lookups and admin
   * display.
   */
  name: string
  /**
   * CSS font-family stack applied to --font-sans. The first available font wins, so
   * a stack naming an unloaded font degrades rather than breaking.
   */
  fontFamily?: string
  /**
   * Applied to the --radius custom property. Any CSS length.
   */
  radius?: string
  /**
   * Tokens emitted under :root.
   */
  light?: {
    background?: string
    foreground?: string
    card?: string
    cardForeground?: string
    popover?: string
    popoverForeground?: string
    primary?: string
    primaryForeground?: string
    secondary?: string
    secondaryForeground?: string
    muted?: string
    mutedForeground?: string
    accent?: string
    accentForeground?: string
    destructive?: string
    destructiveForeground?: string
    border?: string
    input?: string
    ring?: string
    chart1?: string
    chart2?: string
    chart3?: string
    chart4?: string
    chart5?: string
    sidebar?: string
    sidebarForeground?: string
    sidebarPrimary?: string
    sidebarPrimaryForeground?: string
    sidebarAccent?: string
    sidebarAccentForeground?: string
    sidebarBorder?: string
    sidebarRing?: string
  }
  /**
   * Tokens emitted under .dark.
   */
  dark?: {
    background?: string
    foreground?: string
    card?: string
    cardForeground?: string
    popover?: string
    popoverForeground?: string
    primary?: string
    primaryForeground?: string
    secondary?: string
    secondaryForeground?: string
    muted?: string
    mutedForeground?: string
    accent?: string
    accentForeground?: string
    destructive?: string
    destructiveForeground?: string
    border?: string
    input?: string
    ring?: string
    chart1?: string
    chart2?: string
    chart3?: string
    chart4?: string
    chart5?: string
    sidebar?: string
    sidebarForeground?: string
    sidebarPrimary?: string
    sidebarPrimaryForeground?: string
    sidebarAccent?: string
    sidebarAccentForeground?: string
    sidebarBorder?: string
    sidebarRing?: string
  }
}

type ArticleStatusOption = "draft" | "review" | "published"
export interface Article extends VexDocument {
  _id: Id<"articles">
  /**
   * Display title, shown as the document heading and in the admin table.
   */
  title: string
  /**
   * URL path segment. Unique per collection.
   */
  slug: string
  /**
   * Short summary used in listings and social previews.
   */
  excerpt?: string
  /**
   * When this document went live. Empty while it is still a draft.
   */
  publishedAt?: number
  /**
   * User who owns this document. Contributors are scoped to their own rows through
   * this field.
   */
  authorId: Id<"user">[]
  /**
   * Editorial workflow state. Only `published` rows are readable by anonymous
   * visitors.
   */
  status?: ArticleStatusOption[]
  /**
   * Article body copy. Markdown until rich text lands on this collection.
   */
  body?: string
  /**
   * Estimated reading time shown under the article heading.
   */
  readingMinutes?: number
  /**
   * Pins this article to the top of the blog index.
   */
  featured?: boolean
  /**
   * Hero image displayed above the article body.
   */
  coverImage?: Id<"images">[]
}

type CaseStudyStatusOption = "draft" | "review" | "published"
export interface CaseStudy extends VexDocument {
  _id: Id<"case_studies">
  /**
   * Display title, shown as the document heading and in the admin table.
   */
  title: string
  /**
   * URL path segment. Unique per collection.
   */
  slug: string
  /**
   * Short summary used in listings and social previews.
   */
  excerpt?: string
  /**
   * When this document went live. Empty while it is still a draft.
   */
  publishedAt?: number
  /**
   * User who owns this document. Contributors are scoped to their own rows through
   * this field.
   */
  authorId: Id<"user">[]
  /**
   * Editorial workflow state. Only `published` rows are readable by anonymous
   * visitors.
   */
  status?: CaseStudyStatusOption[]
  /**
   * Company the study is about.
   */
  clientName: string
  /**
   * Client's industry, used to group studies on the index page.
   */
  industry?: string
  /**
   * Link to the client's site, shown in the study header.
   */
  clientUrl?: string
  /**
   * One-line result, e.g. "cut page build time by 60%".
   */
  outcomeSummary?: string
  /**
   * Internal figure. Never rendered on the public site.
   */
  contractValue?: number
}

type ChangelogEntryStatusOption = "draft" | "review" | "published"
type ChangelogEntryReleaseTypeOption = "major" | "minor" | "patch"
export interface ChangelogEntry extends VexDocument {
  _id: Id<"changelog">
  /**
   * Display title, shown as the document heading and in the admin table.
   */
  title: string
  /**
   * URL path segment. Unique per collection.
   */
  slug: string
  /**
   * Short summary used in listings and social previews.
   */
  excerpt?: string
  /**
   * When this document went live. Empty while it is still a draft.
   */
  publishedAt?: number
  /**
   * User who owns this document. Contributors are scoped to their own rows through
   * this field.
   */
  authorId: Id<"user">[]
  /**
   * Editorial workflow state. Only `published` rows are readable by anonymous
   * visitors.
   */
  status?: ChangelogEntryStatusOption[]
  /**
   * Semver tag for this release, e.g. `0.4.2`.
   */
  version: string
  /**
   * Drives the badge colour on the changelog page.
   */
  releaseType?: ChangelogEntryReleaseTypeOption[]
  /**
   * Surfaces a migration warning above the entry.
   */
  breaking?: boolean
  /**
   * Markdown list of changes in this release.
   */
  notes?: string
}

export interface Comment extends VexDocument {
  _id: Id<"comments">
  /**
   * User who owns this document. Contributors are scoped to their own rows through
   * this field.
   */
  authorId: Id<"user">[]
  /**
   * Comment text as submitted.
   */
  body: string
  /**
   * Article this comment belongs to.
   */
  article: Id<"articles">[]
  /**
   * Unapproved comments are hidden from the public site.
   */
  approved?: boolean
}

export interface SessionDocument extends VexDocument {
  _id: Id<"session">
  expiresAt: number
  token: string
  createdAt: number
  updatedAt: number
  ipAddress?: string
  userAgent?: string
  userId: string
  impersonatedBy?: string
  activeOrganizationId?: string
  activeTeamId?: string
}

export interface AccountDocument extends VexDocument {
  _id: Id<"account">
  accountId: string
  providerId: string
  userId: string
  accessToken?: string
  refreshToken?: string
  idToken?: string
  accessTokenExpiresAt?: number
  refreshTokenExpiresAt?: number
  scope?: string
  password?: string
  createdAt: number
  updatedAt: number
}

export interface VerificationDocument extends VexDocument {
  _id: Id<"verification">
  identifier: string
  value: string
  expiresAt: number
  createdAt: number
  updatedAt: number
}

export interface OrganizationDocument extends VexDocument {
  _id: Id<"organization">
  name: string
  slug: string
  logo?: string
  createdAt: number
  metadata?: string
  test?: string
}

export interface TeamDocument extends VexDocument {
  _id: Id<"team">
  name: string
  organizationId: string
  createdAt: number
  updatedAt?: number
}

export interface TeamMemberDocument extends VexDocument {
  _id: Id<"teamMember">
  teamId: string
  userId: string
  createdAt?: number
}

export interface MemberDocument extends VexDocument {
  _id: Id<"member">
  organizationId: string
  userId: string
  role: string
  createdAt: number
}

export interface InvitationDocument extends VexDocument {
  _id: Id<"invitation">
  organizationId: string
  email: string
  role?: string
  teamId?: string
  status: string
  expiresAt: number
  createdAt: number
  inviterId: string
  roles: string[]
}

export interface ApikeyDocument extends VexDocument {
  _id: Id<"apikey">
  configId: string
  name?: string
  start?: string
  referenceId: string
  prefix?: string
  key: string
  refillInterval?: number
  refillAmount?: number
  lastRefillAt?: number
  enabled?: boolean
  rateLimitEnabled?: boolean
  rateLimitTimeWindow?: number
  rateLimitMax?: number
  requestCount?: number
  remaining?: number
  lastRequest?: number
  expiresAt?: number
  createdAt: number
  updatedAt: number
  permissions?: string
  metadata?: string
}

export interface JwksDocument extends VexDocument {
  _id: Id<"jwks">
  publicKey: string
  privateKey: string
  createdAt: number
  expiresAt?: number
}

export interface Image extends VexDocument {
  _id: Id<"images">
  filename: string
  alt: string
  mimeType: string
  size: number
  storageId: string
  deleted?: boolean
  src: string
  width?: number
  height?: number
}

export interface NavGlobal extends VexDocumentGlobal<"nav"> {
  items?: {
    title?: string
    href?: string
  }[]
}

export interface SiteSettingsGlobal extends VexDocumentGlobal<"siteSettings"> {
  /**
   * Global site name used as fallback for logo text, page titles, and meta tags.
   */
  name: string
  /**
   * The theme applied to the public site. Changing it re-skins the site on the next
   * page load.
   */
  activeTheme?: Id<"themes">[]
  /**
   * Optional. Leave empty and the admin panel uses the Active Theme; set it to give
   * the admin its own palette.
   */
  adminTheme?: Id<"themes">[]
}

export type CollectionSlug =
  | "pages"
  | "user"
  | "headers"
  | "footers"
  | "themes"
  | "articles"
  | "case_studies"
  | "changelog"
  | "comments"
  | "session"
  | "account"
  | "verification"
  | "organization"
  | "team"
  | "teamMember"
  | "member"
  | "invitation"
  | "apikey"
  | "jwks"
  | "images"

export type GlobalSlug = "nav" | "siteSettings"

export type MediaCollectionSlug = "images"

export type StorageAdapterSlug = "convex"

export type DocumentBySlug = {
  pages: Page
  user: UserDocument
  headers: Header
  footers: Footer
  themes: Theme
  articles: Article
  case_studies: CaseStudy
  changelog: ChangelogEntry
  comments: Comment
  session: SessionDocument
  account: AccountDocument
  verification: VerificationDocument
  organization: OrganizationDocument
  team: TeamDocument
  teamMember: TeamMemberDocument
  member: MemberDocument
  invitation: InvitationDocument
  apikey: ApikeyDocument
  jwks: JwksDocument
  images: Image
}

export type GlobalDocumentBySlug = {
  nav: NavGlobal
  siteSettings: SiteSettingsGlobal
}

declare module "@vexcms/core" {
  interface GeneratedVexTypes {
    CollectionSlug:
      | "pages"
      | "user"
      | "headers"
      | "footers"
      | "themes"
      | "articles"
      | "case_studies"
      | "changelog"
      | "comments"
      | "session"
      | "account"
      | "verification"
      | "organization"
      | "team"
      | "teamMember"
      | "member"
      | "invitation"
      | "apikey"
      | "jwks"
      | "images"
    GlobalSlug: "nav" | "siteSettings"
    MediaCollectionSlug: "images"
    StorageAdapterSlug: "convex"
    DocumentBySlug: {
      pages: Page
      user: UserDocument
      headers: Header
      footers: Footer
      themes: Theme
      articles: Article
      case_studies: CaseStudy
      changelog: ChangelogEntry
      comments: Comment
      session: SessionDocument
      account: AccountDocument
      verification: VerificationDocument
      organization: OrganizationDocument
      team: TeamDocument
      teamMember: TeamMemberDocument
      member: MemberDocument
      invitation: InvitationDocument
      apikey: ApikeyDocument
      jwks: JwksDocument
      images: Image
    }
    GlobalDocumentBySlug: {
      nav: NavGlobal
      siteSettings: SiteSettingsGlobal
    }
    CollectionsFieldTypeMap: {
      pages: {
        text: "title" | "slug" | "content" | "metaTitle" | "metaDescription"
        blocks: "blocks"
        upload: "testImage"
        url: "ogImage"
        relationship: "themes"
        array: "test" | "test2"
        group: "seo" | "anotherTest"
      }
      user: {
        text: "name" | "email" | "image" | "role" | "banReason" | "userId" | "newUserFieldTest"
        checkbox: "emailVerified" | "banned" | "isAnonymous"
        date: "createdAt" | "updatedAt" | "banExpires"
        array: "roles"
      }
      headers: {
        text: "name" | "logoText" | "logoHref" | "menuItems" | "actionButtons"
      }
      footers: {
        text: "name" | "logoText" | "copyright" | "links" | "socialLinks"
      }
      themes: {
        text: "name" | "fontFamily" | "radius"
        group: "light" | "dark"
      }
      articles: {
        text: "title" | "slug" | "excerpt" | "body"
        date: "publishedAt"
        relationship: "authorId" | "coverImage"
        select: "status"
        number: "readingMinutes"
        checkbox: "featured"
      }
      case_studies: {
        text: "title" | "slug" | "excerpt" | "clientName" | "industry" | "outcomeSummary"
        date: "publishedAt"
        relationship: "authorId"
        select: "status"
        url: "clientUrl"
        number: "contractValue"
      }
      changelog: {
        text: "title" | "slug" | "excerpt" | "version" | "notes"
        date: "publishedAt"
        relationship: "authorId"
        select: "status" | "releaseType"
        checkbox: "breaking"
      }
      comments: {
        relationship: "authorId" | "article"
        text: "body"
        checkbox: "approved"
      }
      session: {
        date: "expiresAt" | "createdAt" | "updatedAt"
        text:
          | "token"
          | "ipAddress"
          | "userAgent"
          | "userId"
          | "impersonatedBy"
          | "activeOrganizationId"
          | "activeTeamId"
      }
      account: {
        text:
          | "accountId"
          | "providerId"
          | "userId"
          | "accessToken"
          | "refreshToken"
          | "idToken"
          | "scope"
          | "password"
        date: "accessTokenExpiresAt" | "refreshTokenExpiresAt" | "createdAt" | "updatedAt"
      }
      verification: {
        text: "identifier" | "value"
        date: "expiresAt" | "createdAt" | "updatedAt"
      }
      organization: {
        text: "name" | "slug" | "logo" | "metadata" | "test"
        date: "createdAt"
      }
      team: {
        text: "name" | "organizationId"
        date: "createdAt" | "updatedAt"
      }
      teamMember: {
        text: "teamId" | "userId"
        date: "createdAt"
      }
      member: {
        text: "organizationId" | "userId" | "role"
        date: "createdAt"
      }
      invitation: {
        text: "organizationId" | "email" | "role" | "teamId" | "status" | "inviterId"
        date: "expiresAt" | "createdAt"
        array: "roles"
      }
      apikey: {
        text:
          | "configId"
          | "name"
          | "start"
          | "referenceId"
          | "prefix"
          | "key"
          | "permissions"
          | "metadata"
        number:
          | "refillInterval"
          | "refillAmount"
          | "rateLimitTimeWindow"
          | "rateLimitMax"
          | "requestCount"
          | "remaining"
        date: "lastRefillAt" | "lastRequest" | "expiresAt" | "createdAt" | "updatedAt"
        checkbox: "enabled" | "rateLimitEnabled"
      }
      jwks: {
        text: "publicKey" | "privateKey"
        date: "createdAt" | "expiresAt"
      }
      images: {
        text: "filename" | "alt" | "mimeType" | "storageId" | "src"
        number: "size" | "width" | "height"
        checkbox: "deleted"
      }
    }
    GlobalsFieldTypeMap: {
      nav: {
        array: "items"
      }
      siteSettings: {
        text: "name"
        relationship: "activeTheme" | "adminTheme"
      }
    }
    IndexFieldsBySlug: {
      pages: { by_slug: readonly ["slug"]; by_themes: readonly ["themes"] }
      user: { by_email: readonly ["email"] }
      headers: { by_name: readonly ["name"] }
      footers: { by_name: readonly ["name"] }
      themes: { by_name: readonly ["name"] }
      articles: {
        by_slug: readonly ["slug"]
        by_author: readonly ["authorId"]
        by_status: readonly ["status"]
        by_coverImage: readonly ["coverImage"]
      }
      case_studies: {
        by_slug: readonly ["slug"]
        by_author: readonly ["authorId"]
        by_status: readonly ["status"]
      }
      changelog: {
        by_slug: readonly ["slug"]
        by_author: readonly ["authorId"]
        by_status: readonly ["status"]
        by_version: readonly ["version"]
      }
      comments: { by_author: readonly ["authorId"]; by_article: readonly ["article"] }
      session: { by_token: readonly ["token"]; by_userId: readonly ["userId"] }
      account: { by_userId: readonly ["userId"] }
      verification: { by_identifier: readonly ["identifier"] }
      organization: { by_slug: readonly ["slug"] }
      team: { by_organizationId: readonly ["organizationId"] }
      teamMember: { by_teamId: readonly ["teamId"]; by_userId: readonly ["userId"] }
      member: { by_organizationId: readonly ["organizationId"]; by_userId: readonly ["userId"] }
      invitation: { by_organizationId: readonly ["organizationId"]; by_email: readonly ["email"] }
      apikey: {
        by_configId: readonly ["configId"]
        by_referenceId: readonly ["referenceId"]
        by_key: readonly ["key"]
      }
      jwks: {}
      images: { by_deleted: readonly ["deleted"] }
    }
    CustomActionsBySlug: {
      articles: { query: "listFeatured"; mutation: "publish" }
    }
    AuthSlugs: {
      user: "user"
      organization: "organization"
    }
  }
}
