// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
// Run 'vex dev' or 'vex generate' to update this file.

/* eslint-disable perfectionist/sort-union-types */
/* eslint-disable perfectionist/sort-interfaces */
/* eslint-disable perfectionist/sort-modules */

type Type = "one" | "two" | "three" | "four" | "five" | "six"
export interface Post {
  _id: string
  _creationTime: number
  title: string
  slug: string
  excerpt?: string
  link?: string
  index?: number
  published?: boolean
  publishedAt?: number
  type?: Type
}

export type CollectionSlug = "posts"

export type DocumentBySlug = {
  posts: Post
}
