// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
// Run 'vex dev' or 'vex generate' to update this file.

import { defineTable } from "convex/server"
import { v } from "convex/values"

export const user = defineTable({
  name: v.string(),
  email: v.string(),
  emailVerified: v.boolean(),
  image: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
  role: v.optional(v.string()),
  banned: v.optional(v.boolean()),
  banReason: v.optional(v.string()),
  banExpires: v.optional(v.number()),
  isAnonymous: v.optional(v.boolean()),
  userId: v.optional(v.string()),
  roles: v.array(v.string()),
}).index("by_email", ["email"])

export const session = defineTable({
  expiresAt: v.number(),
  token: v.string(),
  createdAt: v.number(),
  updatedAt: v.number(),
  ipAddress: v.optional(v.string()),
  userAgent: v.optional(v.string()),
  userId: v.string(),
  impersonatedBy: v.optional(v.string()),
  activeOrganizationId: v.optional(v.string()),
})
  .index("by_token", ["token"])
  .index("by_userId", ["userId"])

export const account = defineTable({
  accountId: v.string(),
  providerId: v.string(),
  userId: v.string(),
  accessToken: v.optional(v.string()),
  refreshToken: v.optional(v.string()),
  idToken: v.optional(v.string()),
  accessTokenExpiresAt: v.optional(v.number()),
  refreshTokenExpiresAt: v.optional(v.number()),
  scope: v.optional(v.string()),
  password: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
}).index("by_userId", ["userId"])

export const verification = defineTable({
  identifier: v.string(),
  value: v.string(),
  expiresAt: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
}).index("by_identifier", ["identifier"])

export const apikey = defineTable({
  configId: v.string(),
  name: v.optional(v.string()),
  start: v.optional(v.string()),
  referenceId: v.string(),
  prefix: v.optional(v.string()),
  key: v.string(),
  refillInterval: v.optional(v.number()),
  refillAmount: v.optional(v.number()),
  lastRefillAt: v.optional(v.number()),
  enabled: v.optional(v.boolean()),
  rateLimitEnabled: v.optional(v.boolean()),
  rateLimitTimeWindow: v.optional(v.number()),
  rateLimitMax: v.optional(v.number()),
  requestCount: v.optional(v.number()),
  remaining: v.optional(v.number()),
  lastRequest: v.optional(v.number()),
  expiresAt: v.optional(v.number()),
  createdAt: v.number(),
  updatedAt: v.number(),
  permissions: v.optional(v.string()),
  metadata: v.optional(v.string()),
})
  .index("by_configId", ["configId"])
  .index("by_referenceId", ["referenceId"])
  .index("by_key", ["key"])

export const jwks = defineTable({
  publicKey: v.string(),
  privateKey: v.string(),
  createdAt: v.number(),
  expiresAt: v.optional(v.number()),
})

export const organization = defineTable({
  name: v.string(),
  slug: v.string(),
  logo: v.optional(v.string()),
  createdAt: v.number(),
  metadata: v.optional(v.string()),
}).index("by_slug", ["slug"])

export const member = defineTable({
  organizationId: v.string(),
  userId: v.string(),
  role: v.string(),
  createdAt: v.number(),
})
  .index("by_organizationId", ["organizationId"])
  .index("by_userId", ["userId"])

export const invitation = defineTable({
  organizationId: v.string(),
  email: v.string(),
  role: v.optional(v.string()),
  status: v.string(),
  expiresAt: v.number(),
  createdAt: v.number(),
  inviterId: v.string(),
})
  .index("by_organizationId", ["organizationId"])
  .index("by_email", ["email"])

export const images = defineTable({
  filename: v.string(),
  alt: v.string(),
  mimeType: v.string(),
  size: v.number(),
  storageId: v.string(),
  deleted: v.optional(v.boolean()),
  src: v.string(),
  width: v.optional(v.number()),
  height: v.optional(v.number()),
})
  .index("by_deleted", ["deleted"])
  .searchIndex("search_filename", {
    searchField: "filename",
    filterFields: ["alt"],
  })
