import { describe, it, expect } from "vitest";
import { defineConfig, defineCollection } from "../index";
import { text } from "../fields/text/config";
import { number } from "../fields/number/config";
import { checkbox } from "../fields/checkbox/config";
import { date } from "../fields/date/config";
import { select } from "../fields/select/config";
import { relationship } from "../fields/relationship/config";
import { upload } from "../fields/upload/config";
import { ADMIN_FIELDS } from "../fields/constants";
import { collectionConfigToInterface } from "./interfaceGen";
import { slugToPascalCase } from "./utils";
import { generateVexTypes } from "../types/generateVexTypes";

const HEADER = "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️";

// ─── slugToPascalCase ─────────────────────────────────────────────────────────

describe("slugToPascalCase", () => {
  it("capitalizes single-word slug", () => {
    expect(slugToPascalCase({ slug: "posts" })).toBe("Posts");
  });

  it("capitalizes and joins underscore-separated slug", () => {
    expect(slugToPascalCase({ slug: "blog_posts" })).toBe("BlogPosts");
  });

  it("capitalizes and joins hyphen-separated slug", () => {
    expect(slugToPascalCase({ slug: "blog-posts" })).toBe("BlogPosts");
  });
});

// ─── ADMIN_FIELDS.interfaceType ──────────────────────────────────────────────

describe("ADMIN_FIELDS — interfaceType", () => {
  it("text maps to string", () => {
    expect(ADMIN_FIELDS.text.interfaceType).toBe("string");
  });

  it("number maps to number", () => {
    expect(ADMIN_FIELDS.number.interfaceType).toBe("number");
  });

  it("checkbox maps to boolean", () => {
    expect(ADMIN_FIELDS.checkbox.interfaceType).toBe("boolean");
  });

  it("date maps to number (stored as Unix ms)", () => {
    expect(ADMIN_FIELDS.date.interfaceType).toBe("number");
  });

  it("select maps to string[] (always array)", () => {
    expect(ADMIN_FIELDS.select.interfaceType).toBe("string[]");
  });
});

// ─── relationship / upload target slug ───────────────────────────────────────

describe("interfaceType carries the target collection slug", () => {
  it("relationship emits Id<\"target\">[] rather than the CollectionSlug union", () => {
    const field = relationship({ collection: { slug: "themes" } });
    // Regression: a static `Id<CollectionSlug>[]` makes `RelationshipTargetOf`
    // infer the whole slug union, so `populate` widens to a union of every doc.
    expect(field.interfaceType).toBe('Id<"themes">[]');
    expect(field.interfaceType).not.toBe(ADMIN_FIELDS.relationship.interfaceType);
  });

  it("upload emits Id<\"target\">[] rather than the MediaCollectionSlug union", () => {
    expect(upload({ to: "images" }).interfaceType).toBe('Id<"images">[]');
  });

  it("emits the literal target into the generated interface source", () => {
    const themes = defineCollection({ slug: "themes", fields: { name: text({}) } });
    const pages = defineCollection({
      slug: "pages",
      fields: {
        title: text({}),
        themes: relationship({ collection: { slug: "themes" } }),
      },
    });
    const source = generateVexTypes({ config: defineConfig({ collections: [themes, pages] }) });
    expect(source).toContain('themes?: Id<"themes">[]');
    expect(source).not.toContain("Id<CollectionSlug>[]");
  });
});

// ─── Header ──────────────────────────────────────────────────────────────────

describe("generateVexTypes — header", () => {
  it("always includes the auto-generated header on line 1", () => {
    const config = defineConfig();
    const output = generateVexTypes({ config });
    expect(output.split("\n")[0]).toBe(HEADER);
  });
});

// ─── Document interfaces ──────────────────────────────────────────────────────

describe("generateVexTypes — document interfaces", () => {
  it("generates a document interface for each collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
        defineCollection({
          slug: "authors",
          fields: { name: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export interface PostsDocument extends VexDocument {");
    expect(output).toContain("export interface AuthorsDocument extends VexDocument {");
  });

  it("always includes _id and _creationTime in every interface", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('_id: Id<"posts">');
    expect(output).toContain("extends VexDocument");
    expect(output).not.toContain("_creationTime: number");
  });

  it("generates required fields without ? modifier", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("title: string");
    expect(output).not.toContain("title?: string");
  });

  it("generates optional fields with ? modifier", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { excerpt: text({ required: false }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("excerpt?: string");
  });

  it("generates all field types correctly in one collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({ required: true }),
            views: number({ required: true }),
            published: checkbox({ required: false }),
            publishedAt: date({ required: false }),
            status: select({
              required: true,
              optionInterfaceName: "Status",
              options: [{ label: "Draft", value: "draft" }],
            }),
            tags: select({
              required: false,
              options: [{ label: "News", value: "news" }],
            }),
          },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("title: string");
    expect(output).toContain("views: number");
    expect(output).toContain("published?: boolean");
    expect(output).toContain("publishedAt?: number");
    expect(output).toContain("status: Status[]");
    expect(output).toContain("tags?: PostsDocumentTagsOption[]");
  });

  it("uses PascalCase slug for interface name (underscore slug)", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "blog_posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export interface BlogPostsDocument extends VexDocument {");
  });
});

// ─── CollectionSlug ───────────────────────────────────────────────────────────

describe("generateVexTypes — CollectionSlug", () => {
  it("generates a CollectionSlug union type for all slugs", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export type CollectionSlug =");
    expect(output).toContain('"posts"');
    expect(output).toContain('"authors"');
  });

  it("generates a single-value CollectionSlug for one collection", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "posts", fields: { title: text() } })],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('export type CollectionSlug = "posts"');
  });
});

// ─── DocumentBySlug ───────────────────────────────────────────────────────────

describe("generateVexTypes — DocumentBySlug", () => {
  it("generates a DocumentBySlug mapped type", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export type DocumentBySlug = {");
    expect(output).toContain("posts: PostsDocument");
    expect(output).toContain("authors: AuthorsDocument");
  });
});

describe("collectionConfigToInterface - select emits an array type", () => {
  it("matches the array validator a select field actually stores", () => {
    // `ADMIN_FIELDS.select.validator` is `v.array(v.string())`, so a stored value is
    // always an array. The generated interface previously named the option union bare
    // and promised a scalar, which made `insert({ status: "published" })` a runtime
    // validator error against a type that said it was fine.
    const collection = defineCollection({
      slug: "articles",
      interfaceName: "Article",
      fields: {
        status: select({
          required: true,
          options: [
            { label: "Draft", value: "draft" },
            { label: "Published", value: "published" },
          ],
        }),
      },
    });
    const output = collectionConfigToInterface({ collection });
    expect(output).toContain(`type ArticleStatusOption = "draft" | "published"`);
    expect(output).toContain("status: ArticleStatusOption[]");
  });
});
