import { ADMIN_FIELDS } from "../fields";
import { CollectionConfig } from "./types";
import { slugToPascalCase } from "./utils";

/**
 * Converts a resolved `CollectionConfig` to a TypeScript `export interface` source string.
 *
 * Builds the document interface for one collection, using `collection.interfaceName`
 * as the type name and `field.interfaceType` for each field's TypeScript type. Always
 * includes `_id: string` and `_creationTime: number` as the first two properties.
 * Optional fields (`field.required === false`) are emitted with the `?` modifier.
 *
 * @param props - Input props.
 * @param props.collection - The resolved collection definition to convert.
 * @returns A TypeScript source string for one document interface.
 *
 * @example
 * ```ts
 * const collection = defineCollection({
 *   slug: "posts",
 *   fields: { title: text({ required: true }), excerpt: text({ required: false }) },
 * });
 * collectionConfigToInterface({ collection });
 * // → 'export interface Posts {\n\t_id: string,\n\t_creationTime: number\n\ttitle: string,\n\texcerpt?: string,\n}'
 * ```
 *
 * @see {@link generateVexTypes} for the full-file generator that wraps this function
 */
export function collectionConfigToInterface(props: {
  collection: CollectionConfig;
}): string {
  // TODO: implement
  //
  // 1. Build the header comment (two lines):
  //    Line 1: "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️"
  //    Line 2: "// Run `vex dev` or `vex generate` to update this file."
  //    → Always present, even when there are no collections
  //
  // 2. If props.config.collections is empty, return just the header.
  //
  // 3. For each collection in props.config.collections:
  //    a. Compute the interface name: slugToPascalCase({ slug: collection.slug }) + "Document"
  //       e.g. "posts" → "PostsDocument", "blog_posts" → "BlogPostsDocument"
  //    b. Build field lines:
  //       - Always include: "  _id: string" and "  _creationTime: number"
  //       - For each [fieldKey, field] in Object.entries(collection.fields):
  //         → tsType = ADMIN_FIELDS[field.type as keyof typeof ADMIN_FIELDS].tsType ?? "unknown"
  //         → If field.required: "  fieldKey: tsType"
  //         → If !field.required: "  fieldKey?: tsType"
  //    c. Generate the interface block:
  //       "export interface {InterfaceName} {\n  _id: string\n  _creationTime: number\n{fieldLines}\n}"
  //
  // 4. Generate the CollectionSlug union type:
  //    "export type CollectionSlug = \"posts\" | \"authors\""
  //    → If only one collection: "export type CollectionSlug = \"posts\""
  //    → If no collections: skip (we returned early in step 2)
  //
  // 5. Generate the DocumentBySlug mapped type:
  //    "export type DocumentBySlug = {\n  posts: PostsDocument\n  authors: AuthorsDocument\n}"
  //
  // 6. Assemble and return:
  //    [header, "", ...interfaceBlocks, "", collectionSlugType, "", documentBySlugType].join("\n")
  //    → Use blank lines between sections for readability
  //
  // Edge cases:
  // - Collection with no fields: interface has only _id and _creationTime — valid
  // - Slug with underscores or hyphens: slugToPascalCase handles conversion
  // - Single collection: CollectionSlug is a single-value union (no |) — valid TypeScript
  const { collection } = props;
  const interfaceStart = `export interface ${collection.interfaceName} {\n
    \t_id: string
    \t_creationTime: number`;

  const collectionSubTypes: string[] = [];
  const interfaceFields = Object.entries(collection.fields)
    .map(([fieldKey, field]) => {
      let fieldType = field.interfaceType;
      if (field.type === ADMIN_FIELDS.select.type) {
        fieldType =
          field.optionInterfaceName ??
          `${slugToPascalCase({ slug: fieldKey })}Option`;
        collectionSubTypes.push(
          `type ${fieldType} = ${field.options.map((o) => `"${o.value}"`).join(" | ")}`,
        );
      }
      return `\t${fieldKey}${field.required ? "" : "?"}: ${fieldType}`;
    })
    .join("\n");

  return [
    collectionSubTypes.join("\n"),
    interfaceStart,
    interfaceFields,
    "}",
  ].join("\n");
}
