import { describe, it, expect } from "vitest";
import { defineConfig, defineCollection } from "../index";
import { text } from "../fields/text/config";
import { number } from "../fields/number/config";
import { checkbox } from "../fields/checkbox/config";
import { date } from "../fields/date/config";
import { select } from "../fields/select/config";
import { ADMIN_FIELDS } from "../fields/constants";
import { slugToPascalCase } from "./utils";
import { generateVexTypes } from "../types/generateVexTypes";

const HEADER = "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️";

// ─── slugToPascalCase ─────────────────────────────────────────────────────────

describe("slugToPascalCase", () => {
  it("capitalizes single-word slug", () => {
    expect(slugToPascalCase({ slug: "posts" })).toBe("Posts");
  });

  it("capitalizes and joins underscore-separated slug", () => {
    expect(slugToPascalCase({ slug: "blog_posts" })).toBe("BlogPosts");
  });

  it("capitalizes and joins hyphen-separated slug", () => {
    expect(slugToPascalCase({ slug: "blog-posts" })).toBe("BlogPosts");
  });
});

// ─── ADMIN_FIELDS.interfaceType ──────────────────────────────────────────────

describe("ADMIN_FIELDS — interfaceType", () => {
  it("text maps to string", () => {
    expect(ADMIN_FIELDS.text.interfaceType).toBe("string");
  });

  it("number maps to number", () => {
    expect(ADMIN_FIELDS.number.interfaceType).toBe("number");
  });

  it("checkbox maps to boolean", () => {
    expect(ADMIN_FIELDS.checkbox.interfaceType).toBe("boolean");
  });

  it("date maps to number (stored as Unix ms)", () => {
    expect(ADMIN_FIELDS.date.interfaceType).toBe("number");
  });

  it("select maps to string[] (always array)", () => {
    expect(ADMIN_FIELDS.select.interfaceType).toBe("string[]");
  });
});

// ─── Header ──────────────────────────────────────────────────────────────────

describe("generateVexTypes — header", () => {
  it("always includes the auto-generated header on line 1", () => {
    const config = defineConfig();
    const output = generateVexTypes({ config });
    expect(output.split("\n")[0]).toBe(HEADER);
  });

  it("returns only the header when there are no collections", () => {
    const config = defineConfig();
    const output = generateVexTypes({ config });
    expect(output).not.toContain("export interface");
    expect(output).not.toContain("CollectionSlug");
  });
});

// ─── Document interfaces ──────────────────────────────────────────────────────

describe("generateVexTypes — document interfaces", () => {
  it("generates a document interface for each collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
        defineCollection({
          slug: "authors",
          fields: { name: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export interface PostsDocument extends VexDocument {");
    expect(output).toContain("export interface AuthorsDocument extends VexDocument {");
  });

  it("always includes _id and _creationTime in every interface", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('_id: Id<"posts">');
    expect(output).toContain("extends VexDocument");
    expect(output).not.toContain("_creationTime: number");
  });

  it("generates required fields without ? modifier", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("title: string");
    expect(output).not.toContain("title?: string");
  });

  it("generates optional fields with ? modifier", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { excerpt: text({ required: false }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("excerpt?: string");
  });

  it("generates all field types correctly in one collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({ required: true }),
            views: number({ required: true }),
            published: checkbox({ required: false }),
            publishedAt: date({ required: false }),
            status: select({
              required: true,
              optionInterfaceName: "Status",
              options: [{ label: "Draft", value: "draft" }],
            }),
            tags: select({
              required: false,
              options: [{ label: "News", value: "news" }],
            }),
          },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("title: string");
    expect(output).toContain("views: number");
    expect(output).toContain("published?: boolean");
    expect(output).toContain("publishedAt?: number");
    expect(output).toContain("status: Status");
    expect(output).toContain("tags?: TagsOption");
  });

  it("uses PascalCase slug for interface name (underscore slug)", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "blog_posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export interface BlogPostsDocument extends VexDocument {");
  });
});

// ─── CollectionSlug ───────────────────────────────────────────────────────────

describe("generateVexTypes — CollectionSlug", () => {
  it("generates a CollectionSlug union type for all slugs", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export type CollectionSlug =");
    expect(output).toContain('"posts"');
    expect(output).toContain('"authors"');
  });

  it("generates a single-value CollectionSlug for one collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('export type CollectionSlug = "posts"');
  });
});

// ─── DocumentBySlug ───────────────────────────────────────────────────────────

describe("generateVexTypes — DocumentBySlug", () => {
  it("generates a DocumentBySlug mapped type", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export type DocumentBySlug = {");
    expect(output).toContain("posts: PostsDocument");
    expect(output).toContain("authors: AuthorsDocument");
  });
});
