import type { Metadata } from "next"

import "./globals.css"

import { ThemeScript } from "@vexcms/react"
import { Geist, Geist_Mono } from "next/font/google"

import ClientProviders from "~/components/providers/client"
import ServerProviders from "~/components/providers/server"
import { ThemeLive } from "~/components/ThemeLive"
import { ThemeStyle } from "~/components/ThemeStyle"

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  description: "Generated by create z3 app",
  icons: { icon: "/favicons/favicon.ico" },
  title: "VexCMS",
}

/**
 * Root Next.js layout — applies global fonts, sets metadata, and wraps the app
 * in `ServerProviders` (e.g. colour scheme) and `ClientProviders` (Convex, auth,
 * query).
 *
 * `<ThemeStyle />` is here rather than in a route group on purpose: the site's
 * active theme should reach **everything**, admin panel included. The admin
 * layout then re-emits its own theme at higher specificity, so setting
 * `siteSettings.adminTheme` opts the panel out. The `auth` parallel slot moved
 * to `(frontend)/layout.tsx`, which is the group that declares it.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      lang="en"
      suppressHydrationWarning
    >
      <head>
        <ThemeScript />
        <ThemeStyle />
      </head>
      <body>
        <ServerProviders>
          <ClientProviders>
            <ThemeLive />
            {children}
          </ClientProviders>
        </ServerProviders>
      </body>
    </html>
  )
}
