import type { Metadata } from "next";

import "./globals.css";

import { ThemeScript } from "@vexcms/react";
import { Geist, Geist_Mono } from "next/font/google";

import ClientProviders from "~/components/providers/client";
import ServerProviders from "~/components/providers/server";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create z3 app",
  icons: { icon: "/favicons/favicon.ico" },
  title: "VexCMS",
};

/**
 * Root Next.js layout — applies global fonts, sets metadata, and wraps the
 * app in `ServerProviders` (e.g. theme) and `ClientProviders` (Convex, auth,
 * query). Supports a parallel `auth` slot for modal auth UI.
 */
export default function RootLayout({
  auth,
  children,
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      lang="en"
      suppressHydrationWarning
    >
      <head>
        <ThemeScript />
      </head>
      <body>
        <ServerProviders>
          <ClientProviders>
            {children}
            {auth}
          </ClientProviders>
        </ServerProviders>
      </body>
    </html>
  );
}
