packages:
  - "packages/*"
  - "apps/*"

catalog:
  prettier: "^3.8.1"
  typescript: "^5.9.3"
  next: "^16.1.0"
  react: "^19.2.0"
  react-dom: "^19.2.0"
  "@types/react": "^19.2.0"
  "@types/react-dom": "^19.2.0"
  tsup: "^8.5.1"
  # Testing - Vitest 4.x
  vitest: "^4.0.0"
  "@vitest/coverage-v8": "^4.0.0"
  "@testing-library/react": "^16.3.0"
  "@testing-library/dom": "^10.5.0"
  jsdom: "^26.1.0"
  # Testing - Playwright 1.58.x
  playwright: "^1.58.0"
  "@playwright/test": "^1.58.0"
