import { describe, expect, it } from "vitest";
import { defineCollection, defineConfig, defineGlobal, relationship } from "../index";
import { checkbox } from "../fields/checkbox/config";
import { date } from "../fields/date/config";
import { number } from "../fields/number/config";
import { select } from "../fields/select/config";
import { text } from "../fields/text/config";
import { defineAccess } from "../access/config";
import { generateVexTypes } from "./generateVexTypes";

const HEADER = "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️";

// ─── header ──────────────────────────────────────────────────────────────────

describe("generateVexTypes — header", () => {
  it("always includes the auto-generated header on line 1", () => {
    const config = defineConfig();
    const output = generateVexTypes({ config });
    expect(output.split("\n")[0]).toBe(HEADER);
  });
});

// ─── document interfaces ──────────────────────────────────────────────────────

describe("generateVexTypes — document interfaces", () => {
  it("generates a document interface for each collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
        defineCollection({
          slug: "authors",
          fields: { name: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export interface PostsDocument extends VexDocument {");
    expect(output).toContain("export interface AuthorsDocument extends VexDocument {");
  });

  it("always includes _id and _creationTime in every interface", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('_id: Id<"posts">');
    expect(output).toContain("extends VexDocument");
    expect(output).not.toContain("_creationTime: number");
  });

  it("generates required fields without ? modifier", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("title: string");
    expect(output).not.toContain("title?: string");
  });

  it("generates optional fields with ? modifier", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { excerpt: text({ required: false }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("excerpt?: string");
  });

  it("generates all field types correctly in one collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({ required: true }),
            views: number({ required: true }),
            published: checkbox({ required: false }),
            publishedAt: date({ required: false }),
            status: select({
              required: true,
              optionInterfaceName: "Status",
              options: [{ label: "Draft", value: "draft" }],
            }),
            tags: select({
              required: false,
              options: [{ label: "News", value: "news" }],
            }),
          },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("title: string");
    expect(output).toContain("views: number");
    expect(output).toContain("published?: boolean");
    expect(output).toContain("publishedAt?: number");
    expect(output).toContain("status: Status[]");
    expect(output).toContain("tags?: PostsDocumentTagsOption[]");
  });

  it("uses PascalCase slug for interface name (underscore slug)", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "blog_posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export interface BlogPostsDocument extends VexDocument {");
  });
});

// ─── CollectionSlug ───────────────────────────────────────────────────────────

describe("generateVexTypes — CollectionSlug", () => {
  it("generates a CollectionSlug union type for all slugs", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export type CollectionSlug =");
    expect(output).toContain('"posts"');
    expect(output).toContain('"authors"');
  });

  it("generates a single-value CollectionSlug for one collection", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "posts", fields: { title: text() } })],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('export type CollectionSlug = "posts"');
  });
});

// ─── DocumentBySlug ───────────────────────────────────────────────────────────

describe("generateVexTypes — DocumentBySlug", () => {
  it("generates a DocumentBySlug mapped type", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export type DocumentBySlug = {");
    expect(output).toContain("posts: PostsDocument");
    expect(output).toContain("authors: AuthorsDocument");
  });
});

// ─── declare module augmentation ─────────────────────────────────────────────

describe("generateVexTypes — declare module augmentation", () => {
  it("emits declare module block when collections exist", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain(`declare module "@vexcms/core"`);
    expect(output).toContain("interface GeneratedVexTypes");
  });

  it("includes CollectionSlug in GeneratedVexTypes augmentation", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain(`CollectionSlug: "posts" | "authors"`);
  });

  it("includes DocumentBySlug in GeneratedVexTypes augmentation", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("DocumentBySlug:");
    expect(output).toContain("posts: PostsDocument");
    expect(output).toContain("authors: AuthorsDocument");
  });

  it("sets CollectionSlug type to 'never' when there are no collections", () => {
    const config = defineConfig();
    const output = generateVexTypes({ config });
    expect(output).toContain("type CollectionSlug = never");
  });

  it("emits declare module block for a single collection", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "posts", fields: { title: text() } })],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain(`declare module "@vexcms/core"`);
    expect(output).toContain(`CollectionSlug: "posts"`);
    expect(output).toContain("posts: PostsDocument");
  });

  it("declare module block appears after DocumentBySlug in the output", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "posts", fields: { title: text() } })],
    });
    const output = generateVexTypes({ config });
    const documentBySlugPos = output.indexOf("export type DocumentBySlug");
    const declareModulePos = output.indexOf("declare module");
    expect(declareModulePos).toBeGreaterThan(documentBySlugPos);
  });

  it("uses the collection interfaceName in DocumentBySlug augmentation", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "blog_posts", fields: { title: text() } })],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("blog_posts: BlogPostsDocument");
  });
});

describe("generateVexTypes — globals", () => {
  it("emits SiteSettingsGlobal extending VexDocumentGlobal when globals are present", () => {
    const config = defineConfig({
      globals: [
        defineGlobal({
          slug: "siteSettings",
          label: "Site Settings",
          fields: { siteName: text({ label: "Site Name", required: true }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('extends VexDocumentGlobal<"siteSettings">');
    expect(output).toContain("siteName: string");
    expect(output).toContain('type GlobalSlug = "siteSettings"');
    expect(output).toContain("type GlobalDocumentBySlug = {");
    expect(output).toContain("GlobalsFieldTypeMap: {");
  });

  it("emits type GlobalSlug = never when no globals are registered", () => {
    const config = defineConfig({ globals: [] });
    const output = generateVexTypes({ config });
    expect(output).toContain("type GlobalSlug = never");
  });

  it("respects user-supplied interfaceName", () => {
    const config = defineConfig({
      globals: [
        defineGlobal({
          slug: "nav",
          label: "Nav",
          fields: {} as any,
          interfaceName: "NavConfig",
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("export interface NavConfig");
    expect(output).toContain("NavConfig");
  });

  it("emits optional field with ? modifier", () => {
    const config = defineConfig({
      globals: [
        defineGlobal({
          slug: "nav",
          label: "Nav",
          fields: { title: text({ label: "Title", required: false }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("title?: string");
  });
});

describe("generateVexTypes — IndexFieldsBySlug", () => {
  it("emits an explicit field.index as a readonly one-tuple", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "pages",
          fields: { slug: text({ index: "by_slug" }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain(`IndexFieldsBySlug:`);
    expect(output).toContain(`pages: { by_slug: readonly ["slug"] }`);
  });

  it("groups two fields sharing the same index name into one compound tuple, in declaration order", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "pages",
          fields: {
            authorId: text({ index: "by_author_category" }),
            categoryId: text({ index: "by_author_category" }),
          },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain(`pages: { by_author_category: readonly ["authorId", "categoryId"] }`);
  });

  it("auto-indexes relationship fields as a readonly by_<fieldKey> one-tuple", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "authors", fields: { name: text() } }),
        defineCollection({
          slug: "posts",
          fields: { author: relationship({ collection: { slug: "authors" } }) },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain(`posts: { by_author: readonly ["author"] }`);
  });

  it("joins multiple distinct index names on the same collection into one object", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "pages",
          fields: {
            slug: text({ index: "by_slug" }),
            status: text({ index: "by_status" }),
          },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain(
      `pages: { by_slug: readonly ["slug"]; by_status: readonly ["status"] }`,
    );
  });

  it("emits '{}' — never 'never' — for a collection with no indexed fields", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "pages", fields: { title: text() } })],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain(`pages: {}`);
    expect(output).not.toContain(`pages: never`);
  });
});

// The former `describe("generateVexTypes — AccessIndexBySlug")` block is gone with
// the registry it tested. `AccessIndexBySlug` / `AccessIndexNameFor` existed only to
// type the `range` continuation on the deprecated `AccessIndex`, which is deleted —
// and the emitter that fed them read `check.withIndex.name`, a static property that
// no longer exists now the index is chosen by calling `q.withIndex(…)` inside the
// rule's callback. Nothing consumed either type.

describe("generateVexTypes - select option alias naming", () => {
  it("does not collide when two collections share a select field key", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "articles",
          interfaceName: "Article",
          fields: {
            status: select({
              required: true,
              options: [{ label: "Draft", value: "draft" }],
            }),
          },
        }),
        defineCollection({
          slug: "changelog",
          interfaceName: "ChangelogEntry",
          fields: {
            status: select({
              required: true,
              options: [{ label: "Draft", value: "draft" }],
            }),
          },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    // One alias per collection, each named for its own interface. Before this was
    // qualified, both emitted `type StatusOption` and the file had a duplicate
    // identifier — a TS error in generated code the author cannot edit.
    expect(output).toContain("type ArticleStatusOption");
    expect(output).toContain("type ChangelogEntryStatusOption");
    expect(output).not.toContain("type StatusOption");
    expect(output).toContain("status: ArticleStatusOption[]");
    expect(output).toContain("status: ChangelogEntryStatusOption[]");
  });

  it("honours optionInterfaceName over the qualified default", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "articles",
          interfaceName: "Article",
          fields: {
            status: select({
              required: true,
              optionInterfaceName: "EditorialStatus",
              options: [{ label: "Draft", value: "draft" }],
            }),
          },
        }),
      ],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("type EditorialStatus");
    expect(output).toContain("status: EditorialStatus[]");
    expect(output).not.toContain("ArticleStatusOption");
  });
});

describe("generateVexTypes - AuthSlugs", () => {
  it("emits the slugs defineAccess was configured with", () => {
    // These let core resolve the project's user/org DOCUMENT types on its own, which is
    // what lets `AccessCheck<S>` take one type parameter instead of three — and so a
    // project's composable access checks need no local type aliases.
    const users = defineCollection({ slug: "users", fields: { name: text() } });
    const orgs = defineCollection({ slug: "orgs", fields: { name: text() } });
    const config = defineConfig({
      collections: [users, orgs],
      access: defineAccess({
        roles: ["admin"] as const,
        resources: [users],
        userCollectionSlug: "users",
        orgCollectionSlug: "orgs",
        userRolesField: "roles",
        permissions: { admin: { users: { read: true } } },
      }),
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('user: "users"');
    expect(output).toContain('organization: "orgs"');
  });

  it("emits never for an unconfigured organization", () => {
    // `AuthOrgDocument` resolves to `never`, which is how `ConstraintsCallbackProps`
    // already signals "no `organization` key on the props".
    const users = defineCollection({ slug: "users", fields: { name: text() } });
    const config = defineConfig({
      collections: [users],
      access: defineAccess({
        roles: ["admin"] as const,
        resources: [users],
        userCollectionSlug: "users",
        userRolesField: "roles",
        permissions: { admin: { users: { read: true } } },
      }),
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('user: "users"');
    expect(output).toContain("organization: never");
  });

  it("emits never for both when no access config is present", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "users", fields: { name: text() } })],
    });
    const output = generateVexTypes({ config });
    expect(output).toContain("user: never");
    expect(output).toContain("organization: never");
  });
});

describe("generateVexTypes - CustomActionsBySlug", () => {
  const users = defineCollection({ slug: "users", fields: { name: text(), roles: text() } });
  const articles = defineCollection({
    slug: "articles",
    fields: { title: text({ required: true }) },
  });

  it("emits declared custom actions keyed by slug, under the EXACT consumer key", () => {
    const config = defineConfig({
      collections: [users, articles],
      access: defineAccess({
        roles: ["admin"] as const,
        resources: [users, articles],
        userCollectionSlug: "users",
        userRolesField: "roles",
        customActions: { articles: { query: ["listFeatured"], mutation: ["publish"] } },
        permissions: { admin: { articles: { read: true } } },
      }),
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('articles: { query: "listFeatured"; mutation: "publish" }');
    // The consumer in `generated.ts` matches on this exact member name. A one-character
    // drift ("CustomActionsBySlugs") shipped once: the augmentation key never matched,
    // the registry silently resolved to {}, and every call fell back to the permissive
    // pre-generation union - custom verbs vanished from completions while the
    // mutation-shaped draft verbs appeared. Assert the name, not just the payload.
    expect(output).toContain("CustomActionsBySlug: {");
    expect(output).not.toContain("CustomActionsBySlugs");
  });

  it("emits never for an omitted list, keeping single-list declarations exact", () => {
    const config = defineConfig({
      collections: [users, articles],
      access: defineAccess({
        roles: ["admin"] as const,
        resources: [users, articles],
        userCollectionSlug: "users",
        userRolesField: "roles",
        customActions: { articles: { mutation: ["publish"] } },
        permissions: { admin: { articles: { read: true } } },
      }),
    });
    const output = generateVexTypes({ config });
    expect(output).toContain('articles: { query: never; mutation: "publish" }');
  });

  it("emits an empty block when access declares no custom actions", () => {
    const config = defineConfig({
      collections: [users],
      access: defineAccess({
        roles: ["admin"] as const,
        resources: [users],
        userCollectionSlug: "users",
        userRolesField: "roles",
        permissions: { admin: { users: { read: true } } },
      }),
    });
    const output = generateVexTypes({ config });
    // Empty body between the braces - `Object.entries({}).join("\n")` is "".
    expect(output).toContain("CustomActionsBySlug: {\n\n}");
  });

  it("emits an empty block when RBAC is not configured at all", () => {
    const config = defineConfig({ collections: [users] });
    const output = generateVexTypes({ config });
    expect(output).toContain("CustomActionsBySlug: {\n\n}");
  });
});

describe("generateVexTypes - index-less collections", () => {
  it("emits {} for a collection with no indexed fields, never `never`", () => {
    // Regression: this emitted `site_settings: never` once. `ExtractIndexFields`
    // then resolved to `never`, and `keyof never` is `string | number | symbol` -
    // which broke the whole SubjectMap against `SubjectEntry`'s `indexes: string`
    // and took down every consumer of the concrete access config in the app.
    // `{}` is the contract: `keyof {}` is `never`, so `IndexNameFor` still widens
    // correctly while the entry stays a valid object type to index into.
    const bare = defineCollection({ slug: "site_settings", fields: { name: text() } });
    const config = defineConfig({ collections: [bare] });
    const output = generateVexTypes({ config });
    expect(output).toContain("site_settings: {}");
    expect(output).not.toContain("site_settings: never");
  });
});
