import {
  collectionConfigToFieldTypeMap,
  collectionConfigToInterface,
} from "../collections/interfaceGen";
import type { VexConfig } from "../config/types";

/**
 * Generates the full contents of `vex.types.ts` from a resolved `VexConfig`.
 *
 * When there are no collections, returns only the auto-generated header.
 * When collections are present, the output contains:
 * - Imports for `Id` (from `@convex/_generated/dataModel`) and `VexDocument` (from `@vexcms/core`)
 * - One `export interface` per collection, extending `VexDocument` with a branded `Id<"slug">` for `_id`
 * - `export type CollectionSlug` — union of all collection slugs
 * - `export type DocumentBySlug` — map of slug to document interface
 * - `declare module '@vexcms/core'` block that augments `GeneratedVexTypes`, narrowing
 *   `CollectionSlug` and `DocumentBySlug` inside `@vexcms/core` itself
 *
 * @param props - Input props.
 * @param props.config - The fully resolved Vex configuration.
 * @returns The complete TypeScript source string to write to `vex.types.ts`.
 *
 * @example
 * ```ts
 * const config = defineConfig({
 *   collections: [
 *     defineCollection({ slug: "posts", fields: { title: text({ required: true }) } }),
 *   ],
 * });
 * const contents = generateVexTypes({ config });
 * // Writes to vex.types.ts:
 * // import type { Id } from "@convex/_generated/dataModel"
 * // import type { VexDocument } from "@vexcms/core"
 * // export interface PostsDocument extends VexDocument { _id: Id<"posts">; title: string }
 * // export type CollectionSlug = "posts"
 * // export type DocumentBySlug = { posts: PostsDocument }
 * // declare module "@vexcms/core" { interface GeneratedVexTypes { ... } }
 * ```
 *
 * @see {@link collectionConfigToInterface} for the per-collection interface builder
 * @see {@link VexConfig} for the resolved config shape
 */
export function generateVexTypes(props: { config: VexConfig }): string {
  const { config } = props;
  const typesHeader = `// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
    // Run 'vex dev' or 'vex generate' to update this file.\n
    /* eslint-disable perfectionist/sort-union-types */
    /* eslint-disable perfectionist/sort-interfaces */
    /* eslint-disable perfectionist/sort-modules */\n\n
    import type { Id } from "@convex/_generated/dataModel"
    import type { VexDocument } from "@vexcms/core"\n
  `;

  if (config.collections.length === 0) {
    return typesHeader;
  }

  const interfaceBlocks = config.collections.map((collection) =>
    collectionConfigToInterface({ collection }),
  );

  const collectionSlugs = config.collections
    .map((c) => `"${c.slug}"`)
    .join(" | ");
  const collectionSlugType = `export type CollectionSlug = ${collectionSlugs}`;

  const documentsBySlug = config.collections
    .map((c) => `\t${c.slug}: ${c.interfaceName}`)
    .join("\n");
  const documentBySlugType = `export type DocumentBySlug = {\n${documentsBySlug}\n}`;

  const collectionsFieldTypeMap = config.collections
    .map((c) => collectionConfigToFieldTypeMap({ collection: c }))
    .join("\n");

  const declareModule = `declare module "@vexcms/core" {
    \tinterface GeneratedVexTypes {
    \t\tCollectionSlug: ${collectionSlugs}
    \t\tDocumentBySlug: {\n${documentsBySlug}\n}
    \t\tCollectionsFieldTypeMap: {\n${collectionsFieldTypeMap}\n}
    \t}
  \n}`;

  return [
    typesHeader,
    "",
    ...interfaceBlocks,
    "",
    collectionSlugType,
    "",
    documentBySlugType,
    "",
    declareModule,
  ].join("\n");
}
