import { collectionConfigToInterface } from "../collections/interfaceGen";
import type { VexConfig } from "../config/types";

/**
 * Generates the full contents of `vex.types.ts` from a resolved `VexConfig`.
 *
 * Returns just the auto-generated header when there are no collections.
 * When collections are present, returns a TypeScript source string with one
 * document interface per collection, a `CollectionSlug` union type, and a
 * `DocumentBySlug` mapped type.
 *
 * @param props - Input props.
 * @param props.config - The fully resolved Vex configuration.
 * @returns The complete TypeScript source string for `vex.types.ts`.
 *
 * @example
 * ```ts
 * const config = defineConfig({
 *   collections: [
 *     defineCollection({ slug: "posts", fields: { title: text({ required: true }) } }),
 *   ],
 * });
 * const contents = generateVexTypes({ config });
 * // contents → '// ⚠️ AUTO-GENERATED ...\nexport interface PostsDocument { ... }\n...'
 * ```
 *
 * @see {@link collectionConfigToInterface} for the per-collection interface builder
 * @see {@link VexConfig} for the resolved config shape
 */
export function generateVexTypes(props: { config: VexConfig }): string {
  // TODO: implement
  //
  // 1. Build the header comment (two lines):
  //    Line 1: "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️"
  //    Line 2: "// Run `vex dev` or `vex generate` to update this file."
  //    → Always present, even when there are no collections
  //
  // 2. If props.config.collections is empty, return just the header.
  //
  // 3. For each collection in props.config.collections:
  //    a. Compute the interface name: slugToPascalCase({ slug: collection.slug }) + "Document"
  //       e.g. "posts" → "PostsDocument", "blog_posts" → "BlogPostsDocument"
  //    b. Build field lines:
  //       - Always include: "  _id: string" and "  _creationTime: number"
  //       - For each [fieldKey, field] in Object.entries(collection.fields):
  //         → tsType = ADMIN_FIELDS[field.type as keyof typeof ADMIN_FIELDS].tsType ?? "unknown"
  //         → If field.required: "  fieldKey: tsType"
  //         → If !field.required: "  fieldKey?: tsType"
  //    c. Generate the interface block:
  //       "export interface {InterfaceName} {\n  _id: string\n  _creationTime: number\n{fieldLines}\n}"
  //
  // 4. Generate the CollectionSlug union type:
  //    "export type CollectionSlug = \"posts\" | \"authors\""
  //    → If only one collection: "export type CollectionSlug = \"posts\""
  //    → If no collections: skip (we returned early in step 2)
  //
  // 5. Generate the DocumentBySlug mapped type:
  //    "export type DocumentBySlug = {\n  posts: PostsDocument\n  authors: AuthorsDocument\n}"
  //
  // 6. Assemble and return:
  //    [header, "", ...interfaceBlocks, "", collectionSlugType, "", documentBySlugType].join("\n")
  //    → Use blank lines between sections for readability
  //
  // Edge cases:
  // - Collection with no fields: interface has only _id and _creationTime — valid
  // - Slug with underscores or hyphens: slugToPascalCase handles conversion
  // - Single collection: CollectionSlug is a single-value union (no |) — valid TypeScript
  const { config } = props;
  const typesHeader = `// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
    // Run 'vex dev' or 'vex generate' to update this file.\n
    /* eslint-disable perfectionist/sort-union-types */
    /* eslint-disable perfectionist/sort-interfaces */
    /* eslint-disable perfectionist/sort-modules */\n
  `;

  if (config.collections.length === 0) {
    return typesHeader;
  }

  const interfaceBlocks = config.collections.map((collection) =>
    collectionConfigToInterface({ collection }),
  );

  const collectionSlugType = `export type CollectionSlug = ${config.collections
    .map((c) => `"${c.slug}"`)
    .join(" | ")}`;

  const documentBySlugType = `export type DocumentBySlug = {\n${config.collections
    .map((c) => `  ${c.slug}: ${c.interfaceName}`)
    .join("\n")}\n}`;

  return [
    typesHeader,
    "",
    ...interfaceBlocks,
    "",
    collectionSlugType,
    "",
    documentBySlugType,
  ].join("\n");
}
