import {
  collectionConfigToFieldTypeMap,
  collectionConfigToInterface,
} from "../collections/interfaceGen";
import type { VexConfig } from "../config/types";
import { globalConfigToFieldTypeMap, globalConfigToInterface } from "../globals";
import { STORAGE_ADAPTER_PROTOCOLS } from "../media";
import { collectionConfigToIndexFields } from "../collections/indexFields";
import { CustomActionsInput } from "../access";

/**
 * Formats one collection's `IndexFieldsBySlug` entry: a `readonly`
 * field-tuple per declared index name, or `{}` when the collection
 * declares none — the edge case `IndexNameFor` (`types/generated.ts`)
 * depends on: `keyof {}` still resolves to `never`, so an index-less slug
 * widens identically to the old `never`-union form while staying a valid
 * object type `IndexFieldsFor` can index into.
 *
 * @param props - Input props.
 * @param props.slug - The collection slug this entry is keyed under.
 * @param props.indexFields - This collection's `collectIndexFields()` result.
 * @returns One `\t<slug>: { ... }` (or `\t<slug>: {}`) line for the
 *   `IndexFieldsBySlug` block of the `declare module` augmentation.
 * @internal
 */
function formatIndexFieldsEntry(props: {
  slug: string;
  indexFields: Map<string, string[]>;
}): string {
  // `{}` rather than `never` for an index-less collection: `keyof {}` is
  // `never`, so `IndexNameFor` still widens correctly, while `{}` stays a
  // valid object type that `IndexFieldsFor` can index into.
  if (props.indexFields.size === 0) return `\t${props.slug}: {}`;

  // Map iteration follows insertion order, which is field declaration order,
  // so each tuple is positionally correct. Emitted as a `readonly` TUPLE, not
  // a union — the tuple IS the field-order encoding `ConstraintBuilder`
  // narrows against, so a single-field index stays a 1-tuple.
  const entries = [...props.indexFields.entries()]
    .map(
      ([indexName, fieldKeys]) =>
        `${indexName}: readonly [${fieldKeys.map((f) => `"${f}"`).join(", ")}]`,
    )
    .join("; ");
  return `\t${props.slug}: { ${entries} }`;
}

/**
 * Generates the full contents of `vex.types.ts` from a resolved `VexConfig`.
 *
 * When there are no collections, returns only the auto-generated header.
 * When collections are present, the output contains:
 * - Imports for `Id` (from `@convex/_generated/dataModel`) and `VexDocument` (from `@vexcms/core`)
 * - One `export interface` per collection, extending `VexDocument` with a branded `Id<"slug">` for `_id`
 * - `export type CollectionSlug` — union of all collection slugs
 * - `export type DocumentBySlug` — map of slug to document interface
 * - `declare module '@vexcms/core'` block that augments `GeneratedVexTypes`, narrowing
 *   `CollectionSlug` and `DocumentBySlug` inside `@vexcms/core` itself
 *
 * @param props - Input props.
 * @param props.config - The fully resolved Vex configuration.
 * @returns The complete TypeScript source string to write to `vex.types.ts`.
 *
 * @example
 * ```ts
 * const config = defineConfig({
 *   collections: [
 *     defineCollection({ slug: "posts", fields: { title: text({ required: true }) } }),
 *   ],
 * });
 * const contents = generateVexTypes({ config });
 * // Writes to vex.types.ts:
 * // import type { Id } from "@convex/_generated/dataModel"
 * // import type { VexDocument } from "@vexcms/core"
 * // export interface PostsDocument extends VexDocument { _id: Id<"posts">; title: string }
 * // export type CollectionSlug = "posts"
 * // export type DocumentBySlug = { posts: PostsDocument }
 * // declare module "@vexcms/core" { interface GeneratedVexTypes { ... } }
 * ```
 *
 * @see {@link collectionConfigToInterface} for the per-collection interface builder
 * @see {@link VexConfig} for the resolved config shape
 */
export function generateVexTypes(props: { config: VexConfig }): string {
  const { config } = props;
  const typesHeader = `// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
    // Run 'vex dev' or 'vex generate' to update this file.\n
    /* eslint-disable perfectionist/sort-union-types */
    /* eslint-disable perfectionist/sort-interfaces */
    /* eslint-disable perfectionist/sort-modules */\n\n
    import type { Id } from "@convex/_generated/dataModel"
    import type { VexDocument, VexDocumentGlobal } from "@vexcms/core"\n
  `;

  const allCollections = config.collections.concat(config.mediaCollections);
  const hasCollections = allCollections.length > 0;
  const hasGlobals = config.globals.length > 0;

  const interfaceBlocks = allCollections
    .map((collection) => collectionConfigToInterface({ collection }))
    .concat(config.globals.map((global) => globalConfigToInterface({ global })));

  const collectionSlugs = !hasCollections
    ? "never"
    : allCollections.map((c) => `"${c.slug}"`).join(" | ");
  const collectionSlugType = `export type CollectionSlug = ${collectionSlugs}`;

  const mediaCollectionSlugs = !hasCollections
    ? `""`
    : config.mediaCollections.map((mc) => `"${mc.slug}"`).join(" | ");
  const mediaCollectionSlugType = `export type MediaCollectionSlug = ${mediaCollectionSlugs}`;

  const globalSlugs = !hasGlobals ? "never" : config.globals.map((g) => `"${g.slug}"`).join(" | ");
  const globalSlugType = `export type GlobalSlug = ${globalSlugs}`;

  const globalDocumentsBySlug = config.globals
    .map((g) => `\t${g.slug}: ${g.interfaceName}`)
    .join("\n");
  const globalDocumentBySlugType = !hasGlobals
    ? undefined
    : `export type GlobalDocumentBySlug = {\n${globalDocumentsBySlug}\n}`;

  const documentsBySlug = allCollections.map((c) => `\t${c.slug}: ${c.interfaceName}`).join("\n");
  const documentBySlugType = `export type DocumentBySlug = {\n${documentsBySlug}\n}`;

  const collectionsFieldTypeMap = allCollections
    .map((c) => collectionConfigToFieldTypeMap({ collection: c }))
    .join("\n");

  const globalsFieldTypeMap = config.globals
    .map((g) => globalConfigToFieldTypeMap({ global: g }))
    .join("\n");

  const storageAdapterSlugs =
    config.storage?.adapters
      .filter((a) => a.type === STORAGE_ADAPTER_PROTOCOLS.presignedUrl)
      .map((a) => `"${a.name}"`)
      .join(" | ") ?? "never";
  const storageAdapterSlugType = `export type StorageAdapterSlug = ${storageAdapterSlugs}`;

  // The slugs `defineAccess` was configured with. Emitting them lets core resolve the
  // project's user/organization DOCUMENT types on its own, so a project's access
  // helpers can name a check type without threading those two types by hand.
  // `never` when unset: `AccessCheck` falls back to the wide shapes, exactly as it
  // does before `vex generate` has run at all.
  const userSlug = config.access?.userCollectionSlug;
  const orgSlug = config.access?.orgCollectionSlug;
  const authSlugs = [
    `\t\t\tuser: ${userSlug ? `"${userSlug}"` : "never"}`,
    `\t\t\torganization: ${orgSlug ? `"${orgSlug}"` : "never"}`,
  ].join("\n");

  const indexFieldsBySlug = allCollections
    .map((c) =>
      formatIndexFieldsEntry({
        slug: c.slug,
        indexFields: collectionConfigToIndexFields({ collection: c }),
      }),
    )
    .join("\n");

  const customActionsBySlug = Object.entries(config.access?.customActions ?? {})
    .map(([slug, actions]) => {
      const query =
        ((actions as Partial<CustomActionsInput>).query ?? []).map((a) => `"${a}"`).join(" | ") ||
        "never";
      const mutation =
        ((actions as Partial<CustomActionsInput>).mutation ?? [])
          .map((a) => `"${a}"`)
          .join(" | ") || "never";
      return `\t\t\t${slug}: { query: ${query}; mutation: ${mutation} }`;
    })
    .join("\n");

  const declareModule = `declare module "@vexcms/core" {
    \tinterface GeneratedVexTypes {
    \t\tCollectionSlug: ${collectionSlugs}
    \t\tGlobalSlug: ${globalSlugs}
    \t\tMediaCollectionSlug: ${mediaCollectionSlugs}
    \t\tStorageAdapterSlug: ${storageAdapterSlugs}
    \t\tDocumentBySlug: {\n${documentsBySlug}\n}
    \t\tGlobalDocumentBySlug: {\n${globalDocumentsBySlug}\n}
    \t\tCollectionsFieldTypeMap: {\n${collectionsFieldTypeMap}\n}
    \t\tGlobalsFieldTypeMap: {\n${globalsFieldTypeMap}\n}
    \t\tIndexFieldsBySlug: {\n${indexFieldsBySlug}\n}
    \t\tCustomActionsBySlug: {\n${customActionsBySlug}\n}
    \t\tAuthSlugs: {\n${authSlugs}\n}
    \t}
  \n}`;

  return [
    typesHeader,
    "",
    ...interfaceBlocks,
    "",
    collectionSlugType,
    "",
    globalSlugType,
    "",
    mediaCollectionSlugType,
    "",
    storageAdapterSlugType,
    "",
    documentBySlugType,
    "",
    globalDocumentBySlugType,
    "",
    declareModule,
  ].join("\n");
}
