import type { CollectionKind } from "@vexcms/core"

import { getPreviewSnapshot } from "@vexcms/core"
import { ConvexError } from "convex/values"

// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
import type { Doc, Id } from "../../../_generated/dataModel"
import type { MutationCtx, QueryCtx } from "../../../_generated/server"

export async function deleteDocument(props: {
  ctx: MutationCtx
  documentId: Id<"media">
  kind: CollectionKind
}): Promise<void> {
  if (props.kind === "global") {
    const existing = await props.ctx.db.get(props.documentId)
    if (!existing) {
      throw new ConvexError(`Global "media" document not found. Cannot delete a non-existent global.`)
    }
  }

  await props.ctx.db.delete(props.documentId)
}

export async function getDocument(props: {
  ctx: QueryCtx
  documentId: Id<"media">
  preview?: boolean
}): Promise<Doc<"media"> | null> {
  const doc = await props.ctx.db.get(props.documentId)
  if (!doc) {return null}

  if (props.preview) {
    const snapshot = await getPreviewSnapshot({
      collection: "media",
      ctx: props.ctx,
      documentId: props.documentId,
    })
    if (snapshot) {
      return { ...doc, ...snapshot } as Doc<"media">
    }
  }

  return doc
}

export async function listDocuments(props: {
  ctx: QueryCtx
  order?: "asc" | "desc"
  paginationOpts: { cursor: null | string; numItems: number; }
}) {
  const q = props.order === "desc"
    ? props.ctx.db.query("media").order("desc")
    : props.ctx.db.query("media")
  return await q.paginate(props.paginationOpts)
}
