import type { CollectionKind, VexField } from "@vexcms/core"
import type { WithoutSystemFields } from "convex/server"

import { generateFormSchema, getPreviewSnapshot } from "@vexcms/core"
import { ConvexError } from "convex/values"

// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
import type { Doc, Id } from "../../../_generated/dataModel"
import type { MutationCtx, QueryCtx } from "../../../_generated/server"

export async function createDocument(props: {
  collectionFields: Record<string, VexField>
  ctx: MutationCtx
  fields: unknown
  kind: CollectionKind
}): Promise<Id<"user">> {
  if (props.kind === "global") {
    const existing = await props.ctx.db.query("user").first()
    if (existing) {
      throw new ConvexError(`Global "user" already exists. Globals can only have one document.`)
    }
  }

  const schema = generateFormSchema({ fields: props.collectionFields })
  const parsed = schema.safeParse(props.fields)
  if (!parsed.success) {
    throw new ConvexError({ errors: parsed.error.flatten(), message: "Validation failed" })
  }

  const data = { ...parsed.data }
  data.vex_status ??= "published"
  return await props.ctx.db.insert("user", data as WithoutSystemFields<Doc<"user">>)
}

export async function deleteDocument(props: {
  ctx: MutationCtx
  documentId: Id<"user">
  kind: CollectionKind
}): Promise<void> {
  if (props.kind === "global") {
    const existing = await props.ctx.db.get(props.documentId)
    if (!existing) {
      throw new ConvexError(`Global "user" document not found. Cannot delete a non-existent global.`)
    }
  }

  await props.ctx.db.delete(props.documentId)
}

export async function getDocument(props: {
  ctx: QueryCtx
  documentId: Id<"user">
  preview?: boolean
}): Promise<Doc<"user"> | null> {
  const doc = await props.ctx.db.get(props.documentId)
  if (!doc) {return null}

  if (props.preview) {
    const snapshot = await getPreviewSnapshot({
      collection: "user",
      ctx: props.ctx,
      documentId: props.documentId,
    })
    if (snapshot) {
      return { ...doc, ...snapshot } as Doc<"user">
    }
  }

  return doc
}

export async function listDocuments(props: {
  ctx: QueryCtx
  order?: "asc" | "desc"
  paginationOpts: { cursor: null | string; numItems: number; }
}) {
  const q = props.order === "desc"
    ? props.ctx.db.query("user").order("desc")
    : props.ctx.db.query("user")
  return await q.paginate(props.paginationOpts)
}

export async function updateDocument(props: {
  collectionFields: Record<string, VexField>
  ctx: MutationCtx
  documentId: Id<"user">
  fields: unknown
}): Promise<Id<"user">> {
  const schema = generateFormSchema({ fields: props.collectionFields }).partial()
  const parsed = schema.safeParse(props.fields)
  if (!parsed.success) {
    throw new ConvexError({ errors: parsed.error.flatten(), message: "Validation failed" })
  }

  await props.ctx.db.patch(props.documentId, parsed.data as Partial<Doc<"user">>)
  return props.documentId
}
