// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️

import { defineTable } from "convex/server"
import { v } from "convex/values"

/**
 * USER COLLECTIONS
 **/

export const pages = defineTable({
  title: v.string(),
  slug: v.string(),
  content: v.optional(
    v.array(
      v.union(
        v.object({
          blockType: v.literal("hero"),
          blockName: v.optional(v.string()),
          _key: v.string(),
          badgeText: v.optional(v.string()),
          badgeLink: v.optional(v.string()),
          heading: v.string(),
          subheading: v.optional(v.string()),
          primaryCtaLabel: v.string(),
          primaryCtaHref: v.string(),
          secondaryCtaLabel: v.optional(v.string()),
          secondaryCtaHref: v.optional(v.string()),
        }),
        v.object({
          blockType: v.literal("features"),
          blockName: v.optional(v.string()),
          _key: v.string(),
          heading: v.string(),
          subheading: v.optional(v.string()),
          features: v.array(
            v.object({
              title: v.string(),
              description: v.string(),
              icon: v.optional(v.string()),
            })
          ),
        }),
        v.object({
          blockType: v.literal("cta"),
          blockName: v.optional(v.string()),
          _key: v.string(),
          heading: v.string(),
          subheading: v.optional(v.string()),
          actions: v.optional(v.array(v.object({ label: v.string(), href: v.string() }))),
        }),
        v.object({
          blockType: v.literal("faq"),
          blockName: v.optional(v.string()),
          _key: v.string(),
          heading: v.string(),
          subheading: v.optional(v.string()),
          supportLink: v.optional(v.string()),
          items: v.array(v.object({ question: v.string(), answer: v.string() })),
        })
      )
    )
  ),
  vex_status: v.optional(v.union(v.literal("draft"), v.literal("published"))),
  vex_version: v.optional(v.number()),
  vex_publishedAt: v.optional(v.number()),
})
  .index("by_slug", ["slug"])
  .index("by_title", ["title"])
  .searchIndex("search_title", { searchField: "title" })

export const headers = defineTable({
  name: v.string(),
  content: v.optional(
    v.array(
      v.object({
        blockType: v.literal("header"),
        blockName: v.optional(v.string()),
        _key: v.string(),
        logoText: v.optional(v.string()),
        logoImage: v.optional(v.id("media")),
        logoHref: v.optional(v.string()),
        menuItems: v.optional(v.array(v.object({ label: v.string(), href: v.string() }))),
        actionButtons: v.optional(
          v.array(
            v.object({
              label: v.string(),
              href: v.string(),
              variant: v.optional(
                v.union(v.literal("default"), v.literal("outline"), v.literal("ghost"))
              ),
            })
          )
        ),
      })
    )
  ),
  vex_status: v.optional(v.union(v.literal("draft"), v.literal("published"))),
})
  .index("by_name", ["name"])
  .searchIndex("search_name", { searchField: "name" })

export const footers = defineTable({
  name: v.string(),
  content: v.optional(
    v.array(
      v.object({
        blockType: v.literal("footer"),
        blockName: v.optional(v.string()),
        _key: v.string(),
        logoText: v.optional(v.string()),
        logoImage: v.optional(v.id("media")),
        copyright: v.optional(v.string()),
        links: v.optional(v.array(v.object({ label: v.string(), href: v.string() }))),
        socialLinks: v.optional(
          v.array(
            v.object({
              platform: v.string(),
              href: v.string(),
              icon: v.optional(v.string()),
            })
          )
        ),
      })
    )
  ),
  vex_status: v.optional(v.union(v.literal("draft"), v.literal("published"))),
})
  .index("by_name", ["name"])
  .searchIndex("search_name", { searchField: "name" })

export const themes = defineTable({
  name: v.string(),
  light: v.optional(
    v.object({
      background: v.optional(v.string()),
      foreground: v.optional(v.string()),
      card: v.optional(v.string()),
      cardForeground: v.optional(v.string()),
      popover: v.optional(v.string()),
      popoverForeground: v.optional(v.string()),
      primary: v.optional(v.string()),
      primaryForeground: v.optional(v.string()),
      secondary: v.optional(v.string()),
      secondaryForeground: v.optional(v.string()),
      muted: v.optional(v.string()),
      mutedForeground: v.optional(v.string()),
      accent: v.optional(v.string()),
      accentForeground: v.optional(v.string()),
      destructive: v.optional(v.string()),
      destructiveForeground: v.optional(v.string()),
      border: v.optional(v.string()),
      input: v.optional(v.string()),
      ring: v.optional(v.string()),
      chart1: v.optional(v.string()),
      chart2: v.optional(v.string()),
      chart3: v.optional(v.string()),
      chart4: v.optional(v.string()),
      chart5: v.optional(v.string()),
      sidebar: v.optional(v.string()),
      sidebarForeground: v.optional(v.string()),
      sidebarPrimary: v.optional(v.string()),
      sidebarPrimaryForeground: v.optional(v.string()),
      sidebarAccent: v.optional(v.string()),
      sidebarAccentForeground: v.optional(v.string()),
      sidebarBorder: v.optional(v.string()),
      sidebarRing: v.optional(v.string()),
    })
  ),
  dark: v.optional(
    v.object({
      background: v.optional(v.string()),
      foreground: v.optional(v.string()),
      card: v.optional(v.string()),
      cardForeground: v.optional(v.string()),
      popover: v.optional(v.string()),
      popoverForeground: v.optional(v.string()),
      primary: v.optional(v.string()),
      primaryForeground: v.optional(v.string()),
      secondary: v.optional(v.string()),
      secondaryForeground: v.optional(v.string()),
      muted: v.optional(v.string()),
      mutedForeground: v.optional(v.string()),
      accent: v.optional(v.string()),
      accentForeground: v.optional(v.string()),
      destructive: v.optional(v.string()),
      destructiveForeground: v.optional(v.string()),
      border: v.optional(v.string()),
      input: v.optional(v.string()),
      ring: v.optional(v.string()),
      chart1: v.optional(v.string()),
      chart2: v.optional(v.string()),
      chart3: v.optional(v.string()),
      chart4: v.optional(v.string()),
      chart5: v.optional(v.string()),
      sidebar: v.optional(v.string()),
      sidebarForeground: v.optional(v.string()),
      sidebarPrimary: v.optional(v.string()),
      sidebarPrimaryForeground: v.optional(v.string()),
      sidebarAccent: v.optional(v.string()),
      sidebarAccentForeground: v.optional(v.string()),
      sidebarBorder: v.optional(v.string()),
      sidebarRing: v.optional(v.string()),
    })
  ),
  radius: v.optional(v.string()),
  fontFamily: v.optional(v.string()),
  vex_status: v.optional(v.union(v.literal("draft"), v.literal("published"))),
  vex_version: v.optional(v.number()),
  vex_publishedAt: v.optional(v.number()),
})
  .index("by_name", ["name"])
  .searchIndex("search_name", { searchField: "name" })

export const user = defineTable({
  name: v.string(),
  email: v.string(),
  emailVerified: v.boolean(),
  image: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
  role: v.array(v.union(v.literal("admin"), v.literal("editor"), v.literal("user"))),
  banned: v.optional(v.boolean()),
  banReason: v.optional(v.string()),
  banExpires: v.optional(v.number()),
  userId: v.optional(v.string()),
  vex_onboarding_complete: v.optional(v.boolean()),
  vex_status: v.optional(v.union(v.literal("draft"), v.literal("published"))),
})
  .index("by_name", ["name"])
  .index("by_email", ["email"])
  .searchIndex("search_name", { searchField: "name" })

/**
 * MEDIA COLLECTIONS
 **/

export const media = defineTable({
  storageId: v.id("_storage"),
  filename: v.string(),
  mimeType: v.string(),
  size: v.number(),
  url: v.string(),
  alt: v.optional(v.string()),
  width: v.optional(v.number()),
  height: v.optional(v.number()),
})
  .index("by_mimeType", ["mimeType"])
  .index("by_filename", ["filename"])
  .searchIndex("search_filename", { searchField: "filename" })

/**
 * AUTH TABLES
 **/

export const session = defineTable({
  expiresAt: v.number(),
  token: v.string(),
  createdAt: v.number(),
  updatedAt: v.number(),
  ipAddress: v.optional(v.string()),
  userAgent: v.optional(v.string()),
  userId: v.id("user"),
  impersonatedBy: v.optional(v.string()),
})
  .index("by_token", ["token"])
  .index("by_userId", ["userId"])

export const account = defineTable({
  accountId: v.string(),
  providerId: v.string(),
  userId: v.id("user"),
  accessToken: v.optional(v.string()),
  refreshToken: v.optional(v.string()),
  idToken: v.optional(v.string()),
  accessTokenExpiresAt: v.optional(v.number()),
  refreshTokenExpiresAt: v.optional(v.number()),
  scope: v.optional(v.string()),
  password: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
}).index("by_userId", ["userId"])

export const verification = defineTable({
  identifier: v.string(),
  value: v.string(),
  expiresAt: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
}).index("by_identifier", ["identifier"])

export const apikey = defineTable({
  name: v.optional(v.string()),
  start: v.optional(v.string()),
  prefix: v.optional(v.string()),
  key: v.string(),
  userId: v.id("user"),
  refillInterval: v.optional(v.number()),
  refillAmount: v.optional(v.number()),
  lastRefillAt: v.optional(v.number()),
  enabled: v.optional(v.boolean()),
  rateLimitEnabled: v.optional(v.boolean()),
  rateLimitTimeWindow: v.optional(v.number()),
  rateLimitMax: v.optional(v.number()),
  requestCount: v.optional(v.number()),
  remaining: v.optional(v.number()),
  lastRequest: v.optional(v.number()),
  expiresAt: v.optional(v.number()),
  createdAt: v.number(),
  updatedAt: v.number(),
  permissions: v.optional(v.string()),
  metadata: v.optional(v.string()),
})
  .index("by_key", ["key"])
  .index("by_userId", ["userId"])

export const jwks = defineTable({
  publicKey: v.string(),
  privateKey: v.string(),
  createdAt: v.number(),
  expiresAt: v.optional(v.number()),
})

export const site_settings = defineTable({
  name: v.string(),
  activeTheme: v.optional(v.id("themes")),
  description: v.optional(v.string()),
  favicon: v.optional(v.id("media")),
  googleAnalyticsId: v.optional(v.string()),
  metaDescription: v.optional(v.string()),
  metaTitle: v.optional(v.string()),
  ogImage: v.optional(v.id("media")),
  twitterHandle: v.optional(v.string()),
  vex_status: v.optional(v.union(v.literal("draft"), v.literal("published"))),
  vex_version: v.optional(v.number()),
  vex_publishedAt: v.optional(v.number()),
}).index("by_name", ["name"])

/**
 * VEX SYSTEM TABLES
 **/

export const vex_versions = defineTable({
  collection: v.string(),
  documentId: v.string(),
  version: v.number(),
  status: v.union(
    v.literal("draft"),
    v.literal("published"),
    v.literal("autosave"),
    v.literal("previewSnapshot")
  ),
  snapshot: v.any(),
  createdAt: v.number(),
  createdBy: v.optional(v.string()),
  isAutosave: v.boolean(),
  restoredFrom: v.optional(v.number()),
})
  .index("by_document", ["collection", "documentId"])
  .index("by_document_version", ["collection", "documentId", "version"])
  .index("by_document_latest", ["collection", "documentId", "createdAt"])
  .index("by_document_status", ["collection", "documentId", "status"])
  .index("by_autosave", ["collection", "documentId", "isAutosave"])
