// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️

import type { Id } from "./_generated/dataModel"

export interface Cta {
  blockType: "cta"
  blockName?: string
  _key: string
  /** Heading */
  heading: string
  /** Subheading */
  subheading?: string
  /** Actions */
  actions?: Record<string, unknown>[]
}

export interface Faq {
  blockType: "faq"
  blockName?: string
  _key: string
  /** Heading */
  heading: string
  /** Subheading */
  subheading?: string
  /** Support Link */
  supportLink?: string
  /** FAQ Items */
  items: Record<string, unknown>[]
}

export interface Features {
  blockType: "features"
  blockName?: string
  _key: string
  /** Heading */
  heading: string
  /** Subheading */
  subheading?: string
  /** Features */
  features: Record<string, unknown>[]
}

export interface Footer {
  blockType: "footer"
  blockName?: string
  _key: string
  /** Logo Text */
  logoText?: string
  /** Logo Image */
  logoImage?: Id<"media">
  /** Copyright Text */
  copyright?: string
  /** Links */
  links?: Record<string, unknown>[]
  /** Social Links */
  socialLinks?: Record<string, unknown>[]
}

export interface Header {
  blockType: "header"
  blockName?: string
  _key: string
  /** Logo Text */
  logoText?: string
  /** Logo Image */
  logoImage?: Id<"media">
  /** Logo Link */
  logoHref?: string
  /** Menu Items */
  menuItems?: Record<string, unknown>[]
  /** Action Buttons */
  actionButtons?: Record<string, unknown>[]
}

export interface Hero {
  blockType: "hero"
  blockName?: string
  _key: string
  /** Badge Text */
  badgeText?: string
  /** Badge Link */
  badgeLink?: string
  /** Heading */
  heading: string
  /** Subheading */
  subheading?: string
  /** Primary CTA Label */
  primaryCtaLabel: string
  /** Primary CTA Link */
  primaryCtaHref: string
  /** Secondary CTA Label */
  secondaryCtaLabel?: string
  /** Secondary CTA Link */
  secondaryCtaHref?: string
}

export interface HowItWorks {
  blockType: "how_it_works"
  blockName?: string
  _key: string
  /** Heading */
  heading: string
  /** Subheading */
  subheading?: string
  /** Steps */
  steps: Record<string, unknown>[]
}

export interface Roadmap {
  blockType: "roadmap"
  blockName?: string
  _key: string
  /** Heading */
  heading: string
  /** Subheading */
  subheading?: string
  /** Roadmap Items */
  items: Record<string, unknown>[]
}

export interface Pages {
  _id: Id<"pages">
  _creationTime: number
  vex_status?: "draft" | "published"
  vex_version?: number
  vex_publishedAt?: number
  /** Title */
  title: string
  /** Slug */
  slug: string
  /** Content */
  content?: (Hero | Features | HowItWorks | Roadmap | Cta | Faq)[]
}

export interface Headers {
  _id: Id<"headers">
  _creationTime: number
  /** Name */
  name: string
  /** Header */
  content?: Header[]
}

export interface Footers {
  _id: Id<"footers">
  _creationTime: number
  /** Name */
  name: string
  /** Footer */
  content?: Footer[]
}

export interface Themes {
  _id: Id<"themes">
  _creationTime: number
  vex_status?: "draft" | "published"
  vex_version?: number
  vex_publishedAt?: number
  /** Theme Name */
  name: string
  light?: {
    background?: string
    foreground?: string
    card?: string
    cardForeground?: string
    popover?: string
    popoverForeground?: string
    primary?: string
    primaryForeground?: string
    secondary?: string
    secondaryForeground?: string
    muted?: string
    mutedForeground?: string
    accent?: string
    accentForeground?: string
    destructive?: string
    destructiveForeground?: string
    border?: string
    input?: string
    ring?: string
    chart1?: string
    chart2?: string
    chart3?: string
    chart4?: string
    chart5?: string
    sidebar?: string
    sidebarForeground?: string
    sidebarPrimary?: string
    sidebarPrimaryForeground?: string
    sidebarAccent?: string
    sidebarAccentForeground?: string
    sidebarBorder?: string
    sidebarRing?: string
  }
  dark?: {
    background?: string
    foreground?: string
    card?: string
    cardForeground?: string
    popover?: string
    popoverForeground?: string
    primary?: string
    primaryForeground?: string
    secondary?: string
    secondaryForeground?: string
    muted?: string
    mutedForeground?: string
    accent?: string
    accentForeground?: string
    destructive?: string
    destructiveForeground?: string
    border?: string
    input?: string
    ring?: string
    chart1?: string
    chart2?: string
    chart3?: string
    chart4?: string
    chart5?: string
    sidebar?: string
    sidebarForeground?: string
    sidebarPrimary?: string
    sidebarPrimaryForeground?: string
    sidebarAccent?: string
    sidebarAccentForeground?: string
    sidebarBorder?: string
    sidebarRing?: string
  }
  /** Border Radius */
  radius?: string
  /** Font Family */
  fontFamily?: string
}

export interface User {
  _id: Id<"user">
  _creationTime: number
  /** Name */
  name: string
  email: string
  emailVerified: boolean
  /** Image */
  image?: string
  createdAt: number
  updatedAt: number
  role: ("admin" | "editor" | "user")[]
  banned?: boolean
  banReason?: string
  banExpires?: number
  userId?: string
  /** Onboarding Complete */
  vex_onboarding_complete?: boolean
}

export interface Session {
  _id: Id<"session">
  _creationTime: number
  expiresAt: number
  token: string
  createdAt: number
  updatedAt: number
  ipAddress?: string
  userAgent?: string
  userId: Id<"user">
  impersonatedBy?: string
}

export interface Account {
  _id: Id<"account">
  _creationTime: number
  accountId: string
  providerId: string
  userId: Id<"user">
  accessToken?: string
  refreshToken?: string
  idToken?: string
  accessTokenExpiresAt?: number
  refreshTokenExpiresAt?: number
  scope?: string
  password?: string
  createdAt: number
  updatedAt: number
}

export interface Verification {
  _id: Id<"verification">
  _creationTime: number
  identifier: string
  value: string
  expiresAt: number
  createdAt: number
  updatedAt: number
}

export interface Apikey {
  _id: Id<"apikey">
  _creationTime: number
  name?: string
  start?: string
  prefix?: string
  key: string
  userId: Id<"user">
  refillInterval?: number
  refillAmount?: number
  lastRefillAt?: number
  enabled?: boolean
  rateLimitEnabled?: boolean
  rateLimitTimeWindow?: number
  rateLimitMax?: number
  requestCount?: number
  remaining?: number
  lastRequest?: number
  expiresAt?: number
  createdAt: number
  updatedAt: number
  permissions?: string
  metadata?: string
}

export interface Jwks {
  _id: Id<"jwks">
  _creationTime: number
  publicKey: string
  privateKey: string
  createdAt: number
  expiresAt?: number
}

export interface Media {
  _id: Id<"media">
  _creationTime: number
  storageId: string
  filename: string
  mimeType: string
  size: number
  url?: string
  width?: number
  height?: number
}

export interface SiteSettings {
  _id: Id<"site_settings">
  _creationTime: number
  /** Site Name */
  name: string
  /** Active Theme */
  activeTheme?: Id<"themes">
  /** Site Description */
  description?: string
  /** Favicon */
  favicon?: Id<"media">
  /** Google Analytics ID */
  googleAnalyticsId?: string
  /** Meta Description */
  metaDescription?: string
  /** Meta Title */
  metaTitle?: string
  /** OG Image */
  ogImage?: Id<"media">
  /** Twitter Handle */
  twitterHandle?: string
}

export interface VexCollectionTypes {
  account: Account
  apikey: Apikey
  footers: Footers
  headers: Headers
  jwks: Jwks
  media: Media
  pages: Pages
  session: Session
  themes: Themes
  user: User
  verification: Verification
}

export interface VexGlobalTypes {
  site_settings: SiteSettings
}
