// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️

/**
 * Serialized Vex config for Convex function imports.
 * This file is auto-generated — do not edit.
 * It contains only the data Convex functions need,
 * avoiding app-level dependencies (auth, env, etc).
 */

const config = {
  "basePath": "/admin",
  "collections": [
    {
      "slug": "pages",
      "fields": {
        "title": {
          "type": "text",
          "defaultValue": "",
          "label": "Title",
          "required": true
        },
        "slug": {
          "type": "text",
          "defaultValue": "",
          "admin": {
            "description": "URL-friendly page path"
          },
          "index": "by_slug",
          "label": "Slug",
          "required": true
        },
        "content": {
          "type": "blocks",
          "blocks": [
            {
              "slug": "hero",
              "label": "Hero Section",
              "fields": {
                "badgeText": {
                  "type": "text",
                  "label": "Badge Text",
                  "defaultValue": "Now in public beta",
                  "admin": {
                    "description": "Small text shown in the announcement badge"
                  }
                },
                "badgeLink": {
                  "type": "text",
                  "label": "Badge Link",
                  "defaultValue": "/docs",
                  "admin": {
                    "description": "URL the badge links to"
                  }
                },
                "heading": {
                  "type": "text",
                  "label": "Heading",
                  "required": true,
                  "defaultValue": "The CMS built for Convex"
                },
                "subheading": {
                  "type": "text",
                  "label": "Subheading",
                  "defaultValue": "Vex CMS gives you a full-featured content management system powered by Convex — real-time data, type-safe schemas, and a beautiful admin panel out of the box."
                },
                "primaryCtaLabel": {
                  "type": "text",
                  "label": "Primary CTA Label",
                  "required": true,
                  "defaultValue": "Get Started"
                },
                "primaryCtaHref": {
                  "type": "text",
                  "label": "Primary CTA Link",
                  "required": true,
                  "defaultValue": "/docs"
                },
                "secondaryCtaLabel": {
                  "type": "text",
                  "label": "Secondary CTA Label",
                  "defaultValue": "View on GitHub"
                },
                "secondaryCtaHref": {
                  "type": "text",
                  "label": "Secondary CTA Link",
                  "defaultValue": "https://github.com/vexcms/vex"
                }
              },
              "admin": {
                "icon": "sparkles"
              }
            },
            {
              "slug": "features",
              "label": "Features",
              "fields": {
                "heading": {
                  "type": "text",
                  "label": "Heading",
                  "required": true,
                  "defaultValue": "Everything you need to manage content"
                },
                "subheading": {
                  "type": "text",
                  "label": "Subheading",
                  "defaultValue": "Built on Convex's real-time infrastructure with a developer experience that doesn't compromise on power."
                },
                "features": {
                  "type": "array",
                  "label": "Features",
                  "required": true,
                  "items": {
                    "type": "object",
                    "fields": {
                      "title": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Title",
                        "required": true
                      },
                      "description": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Description",
                        "required": true
                      },
                      "icon": {
                        "type": "text",
                        "label": "Icon",
                        "admin": {
                          "description": "Lucide icon name (e.g. Zap, Shield, Code)"
                        }
                      }
                    }
                  },
                  "defaultValue": [
                    {
                      "title": "Real-Time by Default",
                      "description": "Every query is live. Content updates appear instantly across all connected clients — no polling, no webhooks.",
                      "icon": "Zap"
                    },
                    {
                      "title": "Type-Safe Schemas",
                      "description": "Define your collections with TypeScript. Vex generates Convex schemas, Zod validators, and typed queries automatically.",
                      "icon": "Shield"
                    },
                    {
                      "title": "Developer First",
                      "description": "Code-first configuration, CLI tooling, and a clean API. Build with the tools you already know and love.",
                      "icon": "Code"
                    }
                  ]
                }
              },
              "admin": {
                "icon": "layout-grid"
              }
            },
            {
              "slug": "cta",
              "label": "Call to Action",
              "fields": {
                "heading": {
                  "type": "text",
                  "label": "Heading",
                  "required": true,
                  "defaultValue": "Ready to build with Vex CMS?"
                },
                "subheading": {
                  "type": "text",
                  "label": "Subheading",
                  "defaultValue": "Get started in minutes with create-vexcms. Real-time content management powered by Convex."
                },
                "actions": {
                  "type": "array",
                  "label": "Actions",
                  "items": {
                    "type": "object",
                    "fields": {
                      "label": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Button Label",
                        "required": true
                      },
                      "href": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Button Link",
                        "required": true
                      }
                    }
                  },
                  "defaultValue": [
                    {
                      "label": "Get Started",
                      "href": "/docs"
                    },
                    {
                      "label": "View on GitHub",
                      "href": "https://github.com/vexcms/vex"
                    }
                  ]
                }
              },
              "admin": {
                "icon": "megaphone"
              }
            },
            {
              "slug": "faq",
              "label": "FAQ",
              "fields": {
                "heading": {
                  "type": "text",
                  "label": "Heading",
                  "required": true,
                  "defaultValue": "Frequently Asked Questions"
                },
                "subheading": {
                  "type": "text",
                  "label": "Subheading",
                  "defaultValue": "Everything you need to know about Vex CMS and building with Convex."
                },
                "supportLink": {
                  "type": "text",
                  "label": "Support Link",
                  "defaultValue": "https://github.com/vexcms/vex/issues",
                  "admin": {
                    "description": "URL to contact support page"
                  }
                },
                "items": {
                  "type": "array",
                  "label": "FAQ Items",
                  "required": true,
                  "items": {
                    "type": "object",
                    "fields": {
                      "question": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Question",
                        "required": true
                      },
                      "answer": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Answer",
                        "required": true
                      }
                    }
                  },
                  "defaultValue": [
                    {
                      "question": "What is Vex CMS?",
                      "answer": "Vex CMS is a headless content management system built on Convex. It provides real-time data, type-safe schemas, draft/publish workflows, live preview, and a beautiful admin panel — all configured with TypeScript."
                    },
                    {
                      "question": "How is Vex different from other headless CMS platforms?",
                      "answer": "Unlike traditional headless CMS platforms that use REST or GraphQL APIs, Vex is powered by Convex's real-time database. This means content updates are instant across all clients, with no polling or webhooks needed. Your schema is defined in code, giving you full type safety from database to frontend."
                    },
                    {
                      "question": "Do I need to know Convex to use Vex CMS?",
                      "answer": "Basic familiarity with Convex helps, but Vex handles most of the complexity for you. The CLI generates your Convex schema, queries, and types automatically from your collection definitions. You just define your fields and Vex does the rest."
                    },
                    {
                      "question": "Can I use Vex with any frontend framework?",
                      "answer": "Vex CMS is framework-agnostic at the data layer — any app that can use Convex can use Vex. The admin panel and UI components are built for Next.js, but the core package and generated queries work with any Convex-compatible frontend."
                    },
                    {
                      "question": "Is Vex CMS free?",
                      "answer": "Yes, Vex CMS is open source and free to use. You only pay for your Convex usage, which has a generous free tier for most projects."
                    },
                    {
                      "question": "How do I get started?",
                      "answer": "Run `npx create-vexcms@latest` to scaffold a new project with Vex CMS pre-configured. The CLI sets up your Next.js app, Convex backend, authentication, and admin panel in under a minute."
                    }
                  ]
                }
              },
              "admin": {
                "icon": "help-circle"
              }
            }
          ],
          "labels": {
            "singular": "Block",
            "plural": "Blocks"
          },
          "label": "Content"
        }
      },
      "labels": {
        "plural": "Pages",
        "singular": "Page"
      },
      "versions": {
        "drafts": true
      },
      "admin": {
        "useAsTitle": "title",
        "group": "Site Builder",
        "defaultColumns": [
          "title",
          "slug",
          "vex_status",
          "_id"
        ]
      }
    },
    {
      "slug": "headers",
      "fields": {
        "name": {
          "type": "text",
          "defaultValue": "",
          "label": "Name",
          "required": true
        },
        "content": {
          "type": "blocks",
          "blocks": [
            {
              "slug": "header",
              "label": "Header",
              "fields": {
                "logoText": {
                  "type": "text",
                  "label": "Logo Text",
                  "defaultValue": "Vex CMS",
                  "admin": {
                    "description": "Text to display as the logo"
                  }
                },
                "logoImage": {
                  "type": "upload",
                  "label": "Logo Image",
                  "to": "media",
                  "admin": {
                    "description": "Image to display as the logo (overrides text)"
                  }
                },
                "logoHref": {
                  "type": "text",
                  "label": "Logo Link",
                  "defaultValue": "/"
                },
                "menuItems": {
                  "type": "array",
                  "label": "Menu Items",
                  "items": {
                    "type": "object",
                    "fields": {
                      "label": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Label",
                        "required": true
                      },
                      "href": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Link",
                        "required": true
                      }
                    }
                  },
                  "defaultValue": [
                    {
                      "label": "Features",
                      "href": "#features"
                    },
                    {
                      "label": "FAQ",
                      "href": "#faq"
                    },
                    {
                      "label": "Docs",
                      "href": "/docs"
                    }
                  ]
                },
                "actionButtons": {
                  "type": "array",
                  "label": "Action Buttons",
                  "items": {
                    "type": "object",
                    "fields": {
                      "label": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Button Label",
                        "required": true
                      },
                      "href": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Button Link",
                        "required": true
                      },
                      "variant": {
                        "type": "select",
                        "label": "Variant",
                        "options": [
                          {
                            "label": "Default",
                            "value": "default"
                          },
                          {
                            "label": "Outline",
                            "value": "outline"
                          },
                          {
                            "label": "Ghost",
                            "value": "ghost"
                          }
                        ],
                        "defaultValue": "default"
                      }
                    }
                  },
                  "defaultValue": [
                    {
                      "label": "Sign In",
                      "href": "/auth/sign-in",
                      "variant": "outline"
                    },
                    {
                      "label": "Get Started",
                      "href": "/docs",
                      "variant": "default"
                    }
                  ]
                }
              },
              "admin": {
                "icon": "panel-top"
              }
            }
          ],
          "labels": {
            "singular": "Header",
            "plural": "Headers"
          },
          "max": 1,
          "label": "Header"
        }
      },
      "labels": {
        "plural": "Headers",
        "singular": "Header"
      },
      "admin": {
        "useAsTitle": "name",
        "group": "Site Builder"
      }
    },
    {
      "slug": "footers",
      "fields": {
        "name": {
          "type": "text",
          "defaultValue": "",
          "label": "Name",
          "required": true
        },
        "content": {
          "type": "blocks",
          "blocks": [
            {
              "slug": "footer",
              "label": "Footer",
              "fields": {
                "logoText": {
                  "type": "text",
                  "label": "Logo Text",
                  "defaultValue": "Vex CMS"
                },
                "logoImage": {
                  "type": "upload",
                  "label": "Logo Image",
                  "to": "media"
                },
                "copyright": {
                  "type": "text",
                  "label": "Copyright Text",
                  "defaultValue": "Vex CMS. All rights reserved."
                },
                "links": {
                  "type": "array",
                  "label": "Links",
                  "items": {
                    "type": "object",
                    "fields": {
                      "label": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Label",
                        "required": true
                      },
                      "href": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Link",
                        "required": true
                      }
                    }
                  },
                  "defaultValue": [
                    {
                      "label": "Documentation",
                      "href": "/docs"
                    },
                    {
                      "label": "GitHub",
                      "href": "https://github.com/vexcms/vex"
                    },
                    {
                      "label": "npm",
                      "href": "https://www.npmjs.com/package/create-vexcms"
                    },
                    {
                      "label": "Convex",
                      "href": "https://convex.dev"
                    }
                  ]
                },
                "socialLinks": {
                  "type": "array",
                  "label": "Social Links",
                  "items": {
                    "type": "object",
                    "fields": {
                      "platform": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "Platform",
                        "required": true
                      },
                      "href": {
                        "type": "text",
                        "defaultValue": "",
                        "label": "URL",
                        "required": true
                      },
                      "icon": {
                        "type": "text",
                        "label": "Icon",
                        "admin": {
                          "description": "Lucide icon name (e.g. Twitter, Github, Linkedin)"
                        }
                      }
                    }
                  },
                  "defaultValue": [
                    {
                      "platform": "GitHub",
                      "href": "https://github.com/vexcms/vex",
                      "icon": "Github"
                    },
                    {
                      "platform": "X",
                      "href": "https://x.com/vexcms",
                      "icon": "Twitter"
                    }
                  ]
                }
              },
              "admin": {
                "icon": "panel-bottom"
              }
            }
          ],
          "labels": {
            "singular": "Footer",
            "plural": "Footers"
          },
          "max": 1,
          "label": "Footer"
        }
      },
      "labels": {
        "plural": "Footers",
        "singular": "Footer"
      },
      "admin": {
        "useAsTitle": "name",
        "group": "Site Builder"
      }
    },
    {
      "slug": "themes",
      "fields": {
        "name": {
          "type": "text",
          "defaultValue": "",
          "label": "Theme Name",
          "required": true
        },
        "importTheme": {
          "type": "ui",
          "admin": {
            "components": {}
          }
        },
        "colors": {
          "label": "Theme Colors",
          "tabs": [
            {
              "label": "Light",
              "slug": "light",
              "fields": {
                "background": {
                  "label": "Background",
                  "defaultValue": "#ffffff",
                  "type": "color"
                },
                "foreground": {
                  "label": "Foreground",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                },
                "card": {
                  "label": "Card",
                  "defaultValue": "#ffffff",
                  "type": "color"
                },
                "cardForeground": {
                  "label": "Card Foreground",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                },
                "popover": {
                  "label": "Popover",
                  "defaultValue": "#ffffff",
                  "type": "color"
                },
                "popoverForeground": {
                  "label": "Popover Foreground",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                },
                "primary": {
                  "label": "Primary",
                  "defaultValue": "#171717",
                  "type": "color"
                },
                "primaryForeground": {
                  "label": "Primary Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "secondary": {
                  "label": "Secondary",
                  "defaultValue": "#f5f5f5",
                  "type": "color"
                },
                "secondaryForeground": {
                  "label": "Secondary Foreground",
                  "defaultValue": "#171717",
                  "type": "color"
                },
                "muted": {
                  "label": "Muted",
                  "defaultValue": "#f5f5f5",
                  "type": "color"
                },
                "mutedForeground": {
                  "label": "Muted Foreground",
                  "defaultValue": "#737373",
                  "type": "color"
                },
                "accent": {
                  "label": "Accent",
                  "defaultValue": "#f5f5f5",
                  "type": "color"
                },
                "accentForeground": {
                  "label": "Accent Foreground",
                  "defaultValue": "#171717",
                  "type": "color"
                },
                "destructive": {
                  "label": "Destructive",
                  "defaultValue": "#ef4444",
                  "type": "color"
                },
                "destructiveForeground": {
                  "label": "Destructive Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "border": {
                  "label": "Border",
                  "defaultValue": "#e5e5e5",
                  "type": "color"
                },
                "input": {
                  "label": "Input",
                  "defaultValue": "#e5e5e5",
                  "type": "color"
                },
                "ring": {
                  "label": "Ring",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                },
                "chart1": {
                  "label": "Chart 1",
                  "defaultValue": "#e76e50",
                  "type": "color"
                },
                "chart2": {
                  "label": "Chart 2",
                  "defaultValue": "#2a9d90",
                  "type": "color"
                },
                "chart3": {
                  "label": "Chart 3",
                  "defaultValue": "#264653",
                  "type": "color"
                },
                "chart4": {
                  "label": "Chart 4",
                  "defaultValue": "#e8c468",
                  "type": "color"
                },
                "chart5": {
                  "label": "Chart 5",
                  "defaultValue": "#f4a261",
                  "type": "color"
                },
                "sidebar": {
                  "label": "Sidebar",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "sidebarForeground": {
                  "label": "Sidebar Foreground",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                },
                "sidebarPrimary": {
                  "label": "Sidebar Primary",
                  "defaultValue": "#171717",
                  "type": "color"
                },
                "sidebarPrimaryForeground": {
                  "label": "Sidebar Primary FG",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "sidebarAccent": {
                  "label": "Sidebar Accent",
                  "defaultValue": "#f5f5f5",
                  "type": "color"
                },
                "sidebarAccentForeground": {
                  "label": "Sidebar Accent FG",
                  "defaultValue": "#171717",
                  "type": "color"
                },
                "sidebarBorder": {
                  "label": "Sidebar Border",
                  "defaultValue": "#e5e5e5",
                  "type": "color"
                },
                "sidebarRing": {
                  "label": "Sidebar Ring",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                }
              }
            },
            {
              "label": "Dark",
              "slug": "dark",
              "fields": {
                "background": {
                  "label": "Background",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                },
                "foreground": {
                  "label": "Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "card": {
                  "label": "Card",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                },
                "cardForeground": {
                  "label": "Card Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "popover": {
                  "label": "Popover",
                  "defaultValue": "#0a0a0a",
                  "type": "color"
                },
                "popoverForeground": {
                  "label": "Popover Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "primary": {
                  "label": "Primary",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "primaryForeground": {
                  "label": "Primary Foreground",
                  "defaultValue": "#171717",
                  "type": "color"
                },
                "secondary": {
                  "label": "Secondary",
                  "defaultValue": "#262626",
                  "type": "color"
                },
                "secondaryForeground": {
                  "label": "Secondary Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "muted": {
                  "label": "Muted",
                  "defaultValue": "#262626",
                  "type": "color"
                },
                "mutedForeground": {
                  "label": "Muted Foreground",
                  "defaultValue": "#a3a3a3",
                  "type": "color"
                },
                "accent": {
                  "label": "Accent",
                  "defaultValue": "#262626",
                  "type": "color"
                },
                "accentForeground": {
                  "label": "Accent Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "destructive": {
                  "label": "Destructive",
                  "defaultValue": "#ef4444",
                  "type": "color"
                },
                "destructiveForeground": {
                  "label": "Destructive Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "border": {
                  "label": "Border",
                  "defaultValue": "#262626",
                  "type": "color"
                },
                "input": {
                  "label": "Input",
                  "defaultValue": "#262626",
                  "type": "color"
                },
                "ring": {
                  "label": "Ring",
                  "defaultValue": "#d4d4d4",
                  "type": "color"
                },
                "chart1": {
                  "label": "Chart 1",
                  "defaultValue": "#e76e50",
                  "type": "color"
                },
                "chart2": {
                  "label": "Chart 2",
                  "defaultValue": "#2a9d90",
                  "type": "color"
                },
                "chart3": {
                  "label": "Chart 3",
                  "defaultValue": "#264653",
                  "type": "color"
                },
                "chart4": {
                  "label": "Chart 4",
                  "defaultValue": "#e8c468",
                  "type": "color"
                },
                "chart5": {
                  "label": "Chart 5",
                  "defaultValue": "#f4a261",
                  "type": "color"
                },
                "sidebar": {
                  "label": "Sidebar",
                  "defaultValue": "#171717",
                  "type": "color"
                },
                "sidebarForeground": {
                  "label": "Sidebar Foreground",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "sidebarPrimary": {
                  "label": "Sidebar Primary",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "sidebarPrimaryForeground": {
                  "label": "Sidebar Primary FG",
                  "defaultValue": "#171717",
                  "type": "color"
                },
                "sidebarAccent": {
                  "label": "Sidebar Accent",
                  "defaultValue": "#262626",
                  "type": "color"
                },
                "sidebarAccentForeground": {
                  "label": "Sidebar Accent FG",
                  "defaultValue": "#fafafa",
                  "type": "color"
                },
                "sidebarBorder": {
                  "label": "Sidebar Border",
                  "defaultValue": "#262626",
                  "type": "color"
                },
                "sidebarRing": {
                  "label": "Sidebar Ring",
                  "defaultValue": "#d4d4d4",
                  "type": "color"
                }
              }
            }
          ],
          "type": "tabs"
        },
        "radius": {
          "type": "text",
          "label": "Border Radius",
          "defaultValue": "0.625rem"
        },
        "fontFamily": {
          "type": "text",
          "label": "Font Family",
          "defaultValue": "Inter, sans-serif"
        }
      },
      "labels": {
        "plural": "Themes",
        "singular": "Theme"
      },
      "versions": {
        "drafts": true
      },
      "admin": {
        "useAsTitle": "name",
        "group": "Site Builder",
        "defaultColumns": [
          "name",
          "_id",
          "fontFamily"
        ]
      }
    },
    {
      "slug": "user",
      "fields": {
        "name": {
          "type": "text",
          "defaultValue": "",
          "label": "Name",
          "required": true
        },
        "image": {
          "type": "imageUrl",
          "label": "Image"
        },
        "role": {
          "type": "select",
          "defaultValue": "user",
          "hasMany": true,
          "labels": {
            "plural": "Roles",
            "singular": "Role"
          },
          "options": [
            {
              "badgeColor": "#ff0000",
              "label": "Admin",
              "value": "admin"
            },
            {
              "label": "Editor",
              "value": "editor"
            },
            {
              "badgeColor": "#333333",
              "label": "User",
              "value": "user"
            }
          ],
          "required": true
        },
        "vex_onboarding_complete": {
          "type": "checkbox",
          "admin": {
            "hidden": true
          },
          "defaultValue": false,
          "label": "Onboarding Complete"
        }
      },
      "labels": {
        "plural": "Users",
        "singular": "User"
      },
      "admin": {
        "useAsTitle": "name",
        "group": "Admin",
        "defaultColumns": [
          "name",
          "email",
          "createdAt",
          "role"
        ]
      }
    }
  ],
  "globals": [
    {
      "slug": "site_settings",
      "fields": {
        "name": {
          "type": "text",
          "defaultValue": "",
          "label": "Site Name",
          "required": true
        },
        "activeTheme": {
          "type": "relationship",
          "label": "Active Theme",
          "to": "themes"
        },
        "description": {
          "type": "text",
          "label": "Site Description"
        },
        "favicon": {
          "type": "upload",
          "admin": {
            "description": "Site favicon image"
          },
          "label": "Favicon",
          "to": "media"
        },
        "googleAnalyticsId": {
          "type": "text",
          "admin": {
            "description": "GA4 measurement ID (G-XXXXXXXXXX)"
          },
          "label": "Google Analytics ID"
        },
        "metaDescription": {
          "type": "text",
          "admin": {
            "description": "Default meta description for SEO"
          },
          "label": "Meta Description"
        },
        "metaTitle": {
          "type": "text",
          "admin": {
            "description": "Default <title> tag for the site"
          },
          "label": "Meta Title"
        },
        "ogImage": {
          "type": "upload",
          "admin": {
            "description": "Default Open Graph image for social sharing"
          },
          "label": "OG Image",
          "to": "media"
        },
        "twitterHandle": {
          "type": "text",
          "admin": {
            "description": "@handle for Twitter cards"
          },
          "label": "Twitter Handle"
        }
      },
      "label": "Site Settings",
      "admin": {
        "useAsTitle": "name",
        "group": "Site Builder"
      }
    }
  ],
  "media": {
    "collections": [
      {
        "slug": "media",
        "fields": {
          "storageId": {
            "type": "text",
            "required": true,
            "defaultValue": "",
            "label": "Storage ID",
            "admin": {
              "hidden": true
            }
          },
          "filename": {
            "type": "text",
            "required": true,
            "defaultValue": "",
            "label": "Filename",
            "admin": {
              "readOnly": true
            }
          },
          "mimeType": {
            "type": "text",
            "required": true,
            "defaultValue": "",
            "label": "MIME Type",
            "index": "by_mimeType",
            "admin": {
              "readOnly": true
            }
          },
          "size": {
            "type": "number",
            "required": true,
            "defaultValue": 0,
            "label": "File Size (bytes)",
            "admin": {
              "readOnly": true
            }
          },
          "url": {
            "type": "text",
            "required": true,
            "defaultValue": "",
            "label": "URL",
            "admin": {
              "readOnly": true
            }
          },
          "alt": {
            "type": "text",
            "label": "Alt Text"
          },
          "width": {
            "type": "number",
            "label": "Width (px)"
          },
          "height": {
            "type": "number",
            "label": "Height (px)"
          }
        },
        "labels": {
          "plural": "Media",
          "singular": "Media"
        },
        "admin": {
          "useAsTitle": "filename",
          "group": "Media"
        }
      }
    ]
  },
  "access": {},
  "admin": {
    "user": "user"
  }
}

export default config
