// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️

import type { Id } from "./_generated/dataModel"

export interface Pages {
  _id: Id<"pages">
  _creationTime: number
  vex_status?: "draft" | "published"
  vex_version?: number
  vex_publishedAt?: number
  /** Title */
  title: string
  /** Slug */
  slug: string
  /** Content */
  content?: any
}

export interface Headers {
  _id: Id<"headers">
  _creationTime: number
  /** Name */
  name: string
  /** Logo Text */
  logoText?: string
  /** Logo URL */
  logoUrl?: Id<"media">
  /** Sticky Header */
  sticky?: boolean
}

export interface Footers {
  _id: Id<"footers">
  _creationTime: number
  /** Name */
  name: string
  /** Content */
  content?: any
  /** Copyright Text */
  copyright?: string
}

export interface Themes {
  _id: Id<"themes">
  _creationTime: number
  /** Name */
  name: string
  /** Background Color */
  backgroundColor?: string
  /** Font Family */
  fontFamily?: string
  /** Primary Color */
  primaryColor?: string
  /** Secondary Color */
  secondaryColor?: string
}

export interface SiteSettings {
  _id: Id<"site_settings">
  _creationTime: number
  /** Site Name */
  name: string
  /** Site Description */
  description?: string
  /** Favicon */
  favicon?: Id<"media">
}

export interface User {
  _id: Id<"user">
  _creationTime: number
  /** Name */
  name: string
  email: string
  emailVerified: boolean
  /** Image */
  image?: string
  createdAt: number
  updatedAt: number
  role: ("admin" | "editor" | "user")[]
  banned?: boolean
  banReason?: string
  banExpires?: number
  userId?: string
  /** Onboarding Complete */
  vex_onboarding_complete?: boolean
}

export interface Session {
  _id: Id<"session">
  _creationTime: number
  expiresAt: number
  token: string
  createdAt: number
  updatedAt: number
  ipAddress?: string
  userAgent?: string
  userId: Id<"user">
  impersonatedBy?: string
}

export interface Account {
  _id: Id<"account">
  _creationTime: number
  accountId: string
  providerId: string
  userId: Id<"user">
  accessToken?: string
  refreshToken?: string
  idToken?: string
  accessTokenExpiresAt?: number
  refreshTokenExpiresAt?: number
  scope?: string
  password?: string
  createdAt: number
  updatedAt: number
}

export interface Verification {
  _id: Id<"verification">
  _creationTime: number
  identifier: string
  value: string
  expiresAt: number
  createdAt: number
  updatedAt: number
}

export interface Apikey {
  _id: Id<"apikey">
  _creationTime: number
  name?: string
  start?: string
  prefix?: string
  key: string
  userId: Id<"user">
  refillInterval?: number
  refillAmount?: number
  lastRefillAt?: number
  enabled?: boolean
  rateLimitEnabled?: boolean
  rateLimitTimeWindow?: number
  rateLimitMax?: number
  requestCount?: number
  remaining?: number
  lastRequest?: number
  expiresAt?: number
  createdAt: number
  updatedAt: number
  permissions?: string
  metadata?: string
}

export interface Jwks {
  _id: Id<"jwks">
  _creationTime: number
  publicKey: string
  privateKey: string
  createdAt: number
  expiresAt?: number
}

export interface Media {
  _id: Id<"media">
  _creationTime: number
  storageId: string
  filename: string
  mimeType: string
  size: number
  url?: string
  width?: number
  height?: number
}

export interface VexCollectionTypes {
  account: Account
  apikey: Apikey
  footers: Footers
  headers: Headers
  jwks: Jwks
  media: Media
  pages: Pages
  session: Session
  site_settings: SiteSettings
  themes: Themes
  user: User
  verification: Verification
}
