// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
// Run 'vex dev' or 'vex generate' to update this file.

import { defineTable } from "convex/server"
import { v } from "convex/values"

export const pages = defineTable({
  title: v.string(),
  slug: v.string(),
  content: v.optional(v.string()),
  blocks: v.optional(
    v.array(
      v.union(
        v.object({
          blockType: v.literal("hero"),
          blockName: v.optional(v.string()),
          id: v.string(),
          badge: v.optional(v.string()),
          title: v.string(),
          subtitle: v.optional(v.string()),
          primaryCtaLabel: v.optional(v.string()),
          primaryCtaHref: v.optional(v.string()),
          secondaryCtaLabel: v.optional(v.string()),
          secondaryCtaHref: v.optional(v.string()),
          showImage: v.optional(v.boolean()),
          image: v.optional(v.string()),
        }),
        v.object({
          blockType: v.literal("feature"),
          blockName: v.optional(v.string()),
          id: v.string(),
          icon: v.optional(v.string()),
          title: v.string(),
          description: v.optional(v.string()),
          linkLabel: v.optional(v.string()),
          linkHref: v.optional(v.string()),
        }),
        v.object({
          blockType: v.literal("cta"),
          blockName: v.optional(v.string()),
          id: v.string(),
          title: v.string(),
          description: v.optional(v.string()),
          buttonLabel: v.optional(v.string()),
          buttonHref: v.optional(v.string()),
          variant: v.optional(
            v.array(v.union(v.literal("default"), v.literal("outline"), v.literal("ghost")))
          ),
        }),
        v.object({
          blockType: v.literal("testimonial"),
          blockName: v.optional(v.string()),
          id: v.string(),
          quote: v.string(),
          authorName: v.string(),
          authorRole: v.optional(v.string()),
          authorAvatar: v.optional(v.string()),
          company: v.optional(v.string()),
          rating: v.optional(v.number()),
        }),
        v.object({
          blockType: v.literal("stats"),
          blockName: v.optional(v.string()),
          id: v.string(),
          title: v.optional(v.string()),
          stats: v.optional(v.array(v.object({ value: v.string(), label: v.string() }))),
        }),
        v.object({
          blockType: v.literal("logo-cloud"),
          blockName: v.optional(v.string()),
          id: v.string(),
          title: v.optional(v.string()),
          logos: v.optional(
            v.array(v.object({ name: v.string(), image: v.string(), link: v.optional(v.string()) }))
          ),
        }),
        v.object({
          blockType: v.literal("faq"),
          blockName: v.optional(v.string()),
          id: v.string(),
          title: v.optional(v.string()),
          questions: v.optional(v.array(v.object({ question: v.string(), answer: v.string() }))),
        }),
        v.object({
          blockType: v.literal("pricing"),
          blockName: v.optional(v.string()),
          id: v.string(),
          planName: v.string(),
          price: v.string(),
          period: v.optional(v.string()),
          description: v.optional(v.string()),
          features: v.optional(v.array(v.string())),
          ctaLabel: v.optional(v.string()),
          ctaHref: v.optional(v.string()),
          highlighted: v.optional(v.boolean()),
          badge: v.optional(v.string()),
        }),
        v.object({
          blockType: v.literal("content"),
          blockName: v.optional(v.string()),
          id: v.string(),
          body: v.string(),
          align: v.optional(v.array(v.union(v.literal("left"), v.literal("center")))),
          maxWidth: v.optional(
            v.array(v.union(v.literal("prose"), v.literal("wide"), v.literal("full")))
          ),
        })
      )
    )
  ),
  testImage: v.optional(v.array(v.id("images"))),
  metaTitle: v.optional(v.string()),
  metaDescription: v.optional(v.string()),
  ogImage: v.optional(v.string()),
  themes: v.optional(v.array(v.id("themes"))),
  test: v.optional(v.array(v.string())),
  test2: v.optional(v.array(v.array(v.number()))),
  seo: v.optional(
    v.object({
      metaTitle: v.optional(v.string()),
      metaDescription: v.optional(v.string()),
      ogImage: v.optional(v.string()),
    })
  ),
  anotherTest: v.optional(
    v.object({
      title: v.optional(v.string()),
      subtitle: v.optional(v.string()),
      list: v.optional(
        v.array(
          v.object({
            title: v.optional(v.string()),
            description: v.optional(v.string()),
            queue: v.optional(
              v.array(
                v.object({ title: v.optional(v.string()), description: v.optional(v.string()) })
              )
            ),
          })
        )
      ),
    })
  ),
})
  .index("by_slug_title", ["slug", "title"])
  .index("by_slug", ["slug"])
  .index("by_themes", ["themes"])

export const user = defineTable({
  name: v.string(),
  email: v.string(),
  emailVerified: v.boolean(),
  image: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
  role: v.optional(v.string()),
  banned: v.optional(v.boolean()),
  banReason: v.optional(v.string()),
  banExpires: v.optional(v.number()),
  isAnonymous: v.optional(v.boolean()),
  userId: v.optional(v.string()),
  roles: v.array(v.string()),
  newUserFieldTest: v.optional(v.string()),
}).index("by_email", ["email"])

export const headers = defineTable({
  name: v.string(),
  logoText: v.optional(v.string()),
  logoHref: v.optional(v.string()),
  menuItems: v.optional(v.string()),
  actionButtons: v.optional(v.string()),
}).index("by_name", ["name"])

export const footers = defineTable({
  name: v.string(),
  logoText: v.optional(v.string()),
  copyright: v.optional(v.string()),
  links: v.optional(v.string()),
  socialLinks: v.optional(v.string()),
}).index("by_name", ["name"])

export const themes = defineTable({
  name: v.string(),
  fontFamily: v.optional(v.string()),
  radius: v.optional(v.string()),
  light: v.optional(
    v.object({
      background: v.optional(v.string()),
      foreground: v.optional(v.string()),
      card: v.optional(v.string()),
      cardForeground: v.optional(v.string()),
      popover: v.optional(v.string()),
      popoverForeground: v.optional(v.string()),
      primary: v.optional(v.string()),
      primaryForeground: v.optional(v.string()),
      secondary: v.optional(v.string()),
      secondaryForeground: v.optional(v.string()),
      muted: v.optional(v.string()),
      mutedForeground: v.optional(v.string()),
      accent: v.optional(v.string()),
      accentForeground: v.optional(v.string()),
      destructive: v.optional(v.string()),
      destructiveForeground: v.optional(v.string()),
      border: v.optional(v.string()),
      input: v.optional(v.string()),
      ring: v.optional(v.string()),
      chart1: v.optional(v.string()),
      chart2: v.optional(v.string()),
      chart3: v.optional(v.string()),
      chart4: v.optional(v.string()),
      chart5: v.optional(v.string()),
      sidebar: v.optional(v.string()),
      sidebarForeground: v.optional(v.string()),
      sidebarPrimary: v.optional(v.string()),
      sidebarPrimaryForeground: v.optional(v.string()),
      sidebarAccent: v.optional(v.string()),
      sidebarAccentForeground: v.optional(v.string()),
      sidebarBorder: v.optional(v.string()),
      sidebarRing: v.optional(v.string()),
    })
  ),
  dark: v.optional(
    v.object({
      background: v.optional(v.string()),
      foreground: v.optional(v.string()),
      card: v.optional(v.string()),
      cardForeground: v.optional(v.string()),
      popover: v.optional(v.string()),
      popoverForeground: v.optional(v.string()),
      primary: v.optional(v.string()),
      primaryForeground: v.optional(v.string()),
      secondary: v.optional(v.string()),
      secondaryForeground: v.optional(v.string()),
      muted: v.optional(v.string()),
      mutedForeground: v.optional(v.string()),
      accent: v.optional(v.string()),
      accentForeground: v.optional(v.string()),
      destructive: v.optional(v.string()),
      destructiveForeground: v.optional(v.string()),
      border: v.optional(v.string()),
      input: v.optional(v.string()),
      ring: v.optional(v.string()),
      chart1: v.optional(v.string()),
      chart2: v.optional(v.string()),
      chart3: v.optional(v.string()),
      chart4: v.optional(v.string()),
      chart5: v.optional(v.string()),
      sidebar: v.optional(v.string()),
      sidebarForeground: v.optional(v.string()),
      sidebarPrimary: v.optional(v.string()),
      sidebarPrimaryForeground: v.optional(v.string()),
      sidebarAccent: v.optional(v.string()),
      sidebarAccentForeground: v.optional(v.string()),
      sidebarBorder: v.optional(v.string()),
      sidebarRing: v.optional(v.string()),
    })
  ),
})
  .index("by_name", ["name"])
  .searchIndex("search_name", {
    searchField: "name",

    filterFields: [],
  })

export const articles = defineTable({
  title: v.string(),
  slug: v.string(),
  excerpt: v.optional(v.string()),
  publishedAt: v.optional(v.number()),
  authorId: v.array(v.id("user")),
  status: v.optional(
    v.array(v.union(v.literal("draft"), v.literal("review"), v.literal("published")))
  ),
  body: v.optional(v.string()),
  readingMinutes: v.optional(v.number()),
  featured: v.optional(v.boolean()),
  coverImage: v.optional(v.array(v.id("images"))),
})
  .index("by_slug", ["slug"])
  .index("by_author", ["authorId"])
  .index("by_status", ["status"])
  .index("by_coverImage", ["coverImage"])
  .searchIndex("search_title", {
    searchField: "title",

    filterFields: [],
  })

export const case_studies = defineTable({
  title: v.string(),
  slug: v.string(),
  excerpt: v.optional(v.string()),
  publishedAt: v.optional(v.number()),
  authorId: v.array(v.id("user")),
  status: v.optional(
    v.array(v.union(v.literal("draft"), v.literal("review"), v.literal("published")))
  ),
  clientName: v.string(),
  industry: v.optional(v.string()),
  clientUrl: v.optional(v.string()),
  outcomeSummary: v.optional(v.string()),
  contractValue: v.optional(v.number()),
})
  .index("by_slug", ["slug"])
  .index("by_author", ["authorId"])
  .index("by_status", ["status"])

export const changelog = defineTable({
  title: v.string(),
  slug: v.string(),
  excerpt: v.optional(v.string()),
  publishedAt: v.optional(v.number()),
  authorId: v.array(v.id("user")),
  status: v.optional(
    v.array(v.union(v.literal("draft"), v.literal("review"), v.literal("published")))
  ),
  version: v.string(),
  releaseType: v.optional(
    v.array(v.union(v.literal("major"), v.literal("minor"), v.literal("patch")))
  ),
  breaking: v.optional(v.boolean()),
  notes: v.optional(v.string()),
})
  .index("by_slug", ["slug"])
  .index("by_author", ["authorId"])
  .index("by_status", ["status"])
  .index("by_version", ["version"])

export const comments = defineTable({
  authorId: v.array(v.id("user")),
  body: v.string(),
  article: v.array(v.id("articles")),
  approved: v.optional(v.boolean()),
})
  .index("by_author", ["authorId"])
  .index("by_article", ["article"])

export const session = defineTable({
  expiresAt: v.number(),
  token: v.string(),
  createdAt: v.number(),
  updatedAt: v.number(),
  ipAddress: v.optional(v.string()),
  userAgent: v.optional(v.string()),
  userId: v.string(),
  impersonatedBy: v.optional(v.string()),
  activeOrganizationId: v.optional(v.string()),
  activeTeamId: v.optional(v.string()),
})
  .index("by_token", ["token"])
  .index("by_userId", ["userId"])

export const account = defineTable({
  accountId: v.string(),
  providerId: v.string(),
  userId: v.string(),
  accessToken: v.optional(v.string()),
  refreshToken: v.optional(v.string()),
  idToken: v.optional(v.string()),
  accessTokenExpiresAt: v.optional(v.number()),
  refreshTokenExpiresAt: v.optional(v.number()),
  scope: v.optional(v.string()),
  password: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
}).index("by_userId", ["userId"])

export const verification = defineTable({
  identifier: v.string(),
  value: v.string(),
  expiresAt: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
}).index("by_identifier", ["identifier"])

export const organization = defineTable({
  name: v.string(),
  slug: v.string(),
  logo: v.optional(v.string()),
  createdAt: v.number(),
  metadata: v.optional(v.string()),
  test: v.optional(v.string()),
}).index("by_slug", ["slug"])

export const team = defineTable({
  name: v.string(),
  organizationId: v.string(),
  createdAt: v.number(),
  updatedAt: v.optional(v.number()),
}).index("by_organizationId", ["organizationId"])

export const teamMember = defineTable({
  teamId: v.string(),
  userId: v.string(),
  createdAt: v.optional(v.number()),
})
  .index("by_teamId", ["teamId"])
  .index("by_userId", ["userId"])

export const member = defineTable({
  organizationId: v.string(),
  userId: v.string(),
  role: v.string(),
  createdAt: v.number(),
})
  .index("by_organizationId", ["organizationId"])
  .index("by_userId", ["userId"])

export const invitation = defineTable({
  organizationId: v.string(),
  email: v.string(),
  role: v.optional(v.string()),
  teamId: v.optional(v.string()),
  status: v.string(),
  expiresAt: v.number(),
  createdAt: v.number(),
  inviterId: v.string(),
  roles: v.array(v.string()),
})
  .index("by_organizationId", ["organizationId"])
  .index("by_email", ["email"])

export const apikey = defineTable({
  configId: v.string(),
  name: v.optional(v.string()),
  start: v.optional(v.string()),
  referenceId: v.string(),
  prefix: v.optional(v.string()),
  key: v.string(),
  refillInterval: v.optional(v.number()),
  refillAmount: v.optional(v.number()),
  lastRefillAt: v.optional(v.number()),
  enabled: v.optional(v.boolean()),
  rateLimitEnabled: v.optional(v.boolean()),
  rateLimitTimeWindow: v.optional(v.number()),
  rateLimitMax: v.optional(v.number()),
  requestCount: v.optional(v.number()),
  remaining: v.optional(v.number()),
  lastRequest: v.optional(v.number()),
  expiresAt: v.optional(v.number()),
  createdAt: v.number(),
  updatedAt: v.number(),
  permissions: v.optional(v.string()),
  metadata: v.optional(v.string()),
})
  .index("by_configId", ["configId"])
  .index("by_referenceId", ["referenceId"])
  .index("by_key", ["key"])

export const jwks = defineTable({
  publicKey: v.string(),
  privateKey: v.string(),
  createdAt: v.number(),
  expiresAt: v.optional(v.number()),
})

export const images = defineTable({
  filename: v.string(),
  alt: v.string(),
  mimeType: v.string(),
  size: v.number(),
  storageId: v.string(),
  deleted: v.optional(v.boolean()),
  src: v.string(),
  width: v.optional(v.number()),
  height: v.optional(v.number()),
})
  .index("by_deleted", ["deleted"])
  .searchIndex("search_filename", {
    searchField: "filename",
    filterFields: ["alt"],
  })

/**
 * VEX GLOBALS — singleton documents, one row per registered global slug
 **/

export const vex_globals = defineTable({
  slug: v.string(),
  data: v.any(),
}).index("by_slug", ["slug"])
