import { findCollectionBySlug, hasPermission } from "@vexcms/core"
import { paginationOptsValidator } from "convex/server"
// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
import { v } from "convex/values"
import { ConvexError } from "convex/values"

import type { MutationCtx, QueryCtx } from "../../_generated/server"

import vexConfig from "../../../vex.config"
import { mutation, query } from "../../_generated/server"
import { getUser } from "../auth"
import { deleteDocument, getDocument, listDocuments } from "../model/api/media"

const SLUG = "media" as const

async function requireAuth(ctx: MutationCtx | QueryCtx) {
  const auth = await getUser(ctx)
  if (!auth) {throw new ConvexError("Not authenticated")}
  return auth
}

export const get = query({
  args: {
    id: v.id("media"),
    _vexDrafts: v.optional(v.union(v.literal("snapshot"), v.boolean())),
  },
  handler: async (ctx, args) => {
    const preview = (args._vexDrafts ?? "snapshot") === "snapshot"
    const doc = await getDocument({
      ctx,
      documentId: args.id,
      preview,
    })
    if (!doc) {return null}
    const auth = await getUser(ctx)
    if (auth) {
      const allowed = hasPermission({
        access: vexConfig.access,
        action: "read",
        data: doc,
        resource: SLUG,
        user: auth.user,
        userRoles: auth.roles,
      })
      if (!allowed) {return null}
    }
    return doc
  },
})

export const list = query({
  args: {
    order: v.optional(v.union(v.literal("asc"), v.literal("desc"))),
    paginationOpts: paginationOptsValidator,
  },
  handler: async (ctx, args) => {
    const result = await listDocuments({
      ctx,
      order: args.order,
      paginationOpts: args.paginationOpts,
    })
    const auth = await getUser(ctx)
    if (!auth) {return result}
    const filteredPage = result.page.filter((doc) =>
      hasPermission({
        access: vexConfig.access,
        action: "read",
        data: doc,
        resource: SLUG,
        user: auth.user,
        userRoles: auth.roles,
      }) === true,
    )
    return { ...result, page: filteredPage }
  },
})

export const remove = mutation({
  args: { id: v.id("media") },
  handler: async (ctx, args) => {
    const { roles, user } = await requireAuth(ctx)
    hasPermission({
      access: vexConfig.access,
      action: "delete",
      resource: SLUG,
      throwOnDenied: true,
      user,
      userRoles: roles,
    })
    await deleteDocument({
      ctx,
      documentId: args.id,
      kind: "collection",
    })
  },
})
