import type { VexConfig, VexCollection } from "../types";

/** Sentinel string placed at the top of every generated file. */
export const GENERATED_HEADER =
  "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️";

/**
 * Relative import paths used inside generated files.
 * Computed by the CLI from cwd + convexDir; passed in so this function
 * stays pure and testable.
 */
export interface CollectionQueryImports {
  /** Import path for vex.config.ts from api/ dir. e.g. `"../../../vex.config"` */
  vexConfigFromApi: string;
  /** Import path for _generated/ from api/ dir. e.g. `"../../_generated"` */
  generatedDirFromApi: string;
  /** Import path for the user's auth helper from api/ dir. e.g. `"../auth"` */
  authFromApi: string;
  /** Import path for _generated/ from model/api/ dir. e.g. `"../../../_generated"` */
  generatedDirFromModel: string;
}

/**
 * Result of generating all collection files.
 * Keys are relative paths from the vex/ directory.
 * e.g. `"api/articles.ts"`, `"model/api/articles.ts"`, `"api/index.ts"`
 */
export type GeneratedFiles = Record<string, string>;

/**
 * Generate typed Convex query/mutation files for all collections in `config`.
 *
 * Produces two files per collection:
 * - `model/api/{slug}.ts` — typed model functions (DB logic)
 * - `api/{slug}.ts` — Convex query/mutation exports (auth + RBAC + calls model)
 * Plus a barrel `api/index.ts`.
 */
export function generateCollectionQueries(props: {
  config: VexConfig;
  imports: CollectionQueryImports;
}): GeneratedFiles {
  const { config, imports } = props;
  const result: GeneratedFiles = {};
  const slugs: string[] = [];

  // Regular collections
  for (const collection of config.collections) {
    const { apiFile, modelFile } = generateCollectionPair({
      collection,
      isMedia: false,
      imports,
    });
    result[`api/${collection.slug}.ts`] = apiFile;
    result[`model/api/${collection.slug}.ts`] = modelFile;
    slugs.push(collection.slug);
  }

  // Media collections
  if (config.media?.collections) {
    for (const collection of config.media.collections) {
      const { apiFile, modelFile } = generateCollectionPair({
        collection,
        isMedia: true,
        imports,
      });
      result[`api/${collection.slug}.ts`] = apiFile;
      result[`model/api/${collection.slug}.ts`] = modelFile;
      slugs.push(collection.slug);
    }
  }

  // Barrel index
  result["api/index.ts"] = generateIndexFile({ slugs });

  return result;
}

// ─── Per-collection pair generation ──────────────────────────────────────────

/**
 * Generate both the model file and the API file for a single collection.
 */
export function generateCollectionPair(props: {
  collection: VexCollection;
  isMedia: boolean;
  imports: CollectionQueryImports;
}): { apiFile: string; modelFile: string } {
  const { collection, isMedia, imports } = props;
  const slug = collection.slug;
  const tableName = collection.tableName ?? collection.slug;
  const firstSearchIndex = collection.searchIndexes?.[0] ?? null;

  const modelFile = generateModelFile({ slug, tableName, isMedia, firstSearchIndex, imports });
  const apiFile = generateApiFile({ slug, tableName, isMedia, firstSearchIndex, imports });

  return { apiFile, modelFile };
}

// ─── Model file generation ──────────────────────────────────────────────────

export function generateModelFile(props: {
  slug: string;
  tableName: string;
  isMedia: boolean;
  firstSearchIndex: { name: string; searchField: string } | null;
  imports: CollectionQueryImports;
}): string {
  const { tableName, isMedia, firstSearchIndex, imports } = props;
  const parts: string[] = [];

  // Header + imports
  const coreImports = ["getPreviewSnapshot"];
  if (!isMedia) {
    coreImports.push("generateFormSchema");
  }

  const coreTypeImports: string[] = ["CollectionKind"];
  if (!isMedia) {
    coreTypeImports.push("VexField");
  }

  const coreTypeImportLine = coreTypeImports.length > 0
    ? `\nimport type { ${coreTypeImports.join(", ")} } from "@vexcms/core"`
    : "";

  const convexTypeImports = isMedia ? "" : `\nimport type { WithoutSystemFields } from "convex/server"`;

  parts.push(`${GENERATED_HEADER}
import type { Doc, Id } from "${imports.generatedDirFromModel}/dataModel"
import type { QueryCtx, MutationCtx } from "${imports.generatedDirFromModel}/server"${convexTypeImports}
import { ConvexError } from "convex/values"
import { ${coreImports.join(", ")} } from "@vexcms/core"${coreTypeImportLine}`);

  // getDocument
  parts.push(buildModelGetDocument({ tableName }));

  // listDocuments
  parts.push(buildModelListDocuments({ tableName }));

  // createDocument (not for media)
  if (!isMedia) {
    parts.push(buildModelCreateDocument({ tableName }));
  }

  // updateDocument (not for media)
  if (!isMedia) {
    parts.push(buildModelUpdateDocument({ tableName }));
  }

  // deleteDocument
  parts.push(buildModelDeleteDocument({ tableName }));

  // searchDocuments (only if search index)
  if (firstSearchIndex) {
    parts.push(buildModelSearchDocuments({
      tableName,
      searchIndexName: firstSearchIndex.name,
      searchField: firstSearchIndex.searchField as string,
    }));
  }

  return parts.join("\n\n") + "\n";
}

export function buildModelGetDocument(props: { tableName: string }): string {
  const { tableName } = props;
  return `export async function getDocument(props: {
  ctx: QueryCtx
  documentId: Id<"${tableName}">
  preview?: boolean
}): Promise<Doc<"${tableName}"> | null> {
  const doc = await props.ctx.db.get(props.documentId)
  if (!doc) return null

  if (props.preview) {
    const snapshot = await getPreviewSnapshot({
      ctx: props.ctx,
      collection: "${tableName}",
      documentId: props.documentId,
    })
    if (snapshot) {
      return { ...doc, ...snapshot } as Doc<"${tableName}">
    }
  }

  return doc
}`;
}

export function buildModelListDocuments(props: { tableName: string }): string {
  const { tableName } = props;
  return `export async function listDocuments(props: {
  ctx: QueryCtx
  paginationOpts: { numItems: number; cursor: string | null }
  order?: "asc" | "desc"
}) {
  const q = props.order === "desc"
    ? props.ctx.db.query("${tableName}").order("desc")
    : props.ctx.db.query("${tableName}")
  return await q.paginate(props.paginationOpts)
}`;
}

export function buildModelCreateDocument(props: { tableName: string }): string {
  const { tableName } = props;
  return `export async function createDocument(props: {
  collectionFields: Record<string, VexField>
  ctx: MutationCtx
  fields: unknown
  kind: CollectionKind
}): Promise<Id<"${tableName}">> {
  if (props.kind === "global") {
    const existing = await props.ctx.db.query("${tableName}").first()
    if (existing) {
      throw new ConvexError(\`Global "${tableName}" already exists. Globals can only have one document.\`)
    }
  }

  const schema = generateFormSchema({ fields: props.collectionFields })
  const parsed = schema.safeParse(props.fields)
  if (!parsed.success) {
    throw new ConvexError({ message: "Validation failed", errors: parsed.error.flatten() })
  }

  const data = { ...parsed.data }
  data.vex_status ??= "published"
  return await props.ctx.db.insert("${tableName}", data as WithoutSystemFields<Doc<"${tableName}">>)
}`;
}

export function buildModelUpdateDocument(props: { tableName: string }): string {
  const { tableName } = props;
  return `export async function updateDocument(props: {
  collectionFields: Record<string, VexField>
  ctx: MutationCtx
  documentId: Id<"${tableName}">
  fields: unknown
}): Promise<Id<"${tableName}">> {
  const schema = generateFormSchema({ fields: props.collectionFields }).partial()
  const parsed = schema.safeParse(props.fields)
  if (!parsed.success) {
    throw new ConvexError({ message: "Validation failed", errors: parsed.error.flatten() })
  }

  await props.ctx.db.patch(props.documentId, parsed.data as Partial<Doc<"${tableName}">>)
  return props.documentId
}`;
}

export function buildModelDeleteDocument(props: { tableName: string }): string {
  const { tableName } = props;
  return `export async function deleteDocument(props: {
  ctx: MutationCtx
  documentId: Id<"${tableName}">
  kind: CollectionKind
}): Promise<void> {
  if (props.kind === "global") {
    const existing = await props.ctx.db.get(props.documentId)
    if (!existing) {
      throw new ConvexError(\`Global "${tableName}" document not found. Cannot delete a non-existent global.\`)
    }
  }

  await props.ctx.db.delete(props.documentId)
}`;
}

export function buildModelSearchDocuments(props: {
  tableName: string;
  searchIndexName: string;
  searchField: string;
}): string {
  const { tableName, searchIndexName, searchField } = props;
  return `export async function searchDocuments(props: {
  ctx: QueryCtx
  query: string
}): Promise<Doc<"${tableName}">[]> {
  return await props.ctx.db.query("${tableName}")
    .withSearchIndex("${searchIndexName}", (q) => q.search("${searchField}", props.query))
    .take(50)
}`;
}

// ─── API file generation ─────────────────────────────────────────────────────

export function generateApiFile(props: {
  slug: string;
  tableName: string;
  isMedia: boolean;
  firstSearchIndex: { name: string; searchField: string } | null;
  imports: CollectionQueryImports;
}): string {
  const { slug, tableName, isMedia, firstSearchIndex, imports } = props;
  const parts: string[] = [];

  // Model imports
  const modelFns = [
    "getDocument",
    "listDocuments",
    ...(isMedia ? [] : ["createDocument", "updateDocument"]),
    "deleteDocument",
    ...(firstSearchIndex ? ["searchDocuments"] : []),
  ];

  parts.push(`${GENERATED_HEADER}
import { v } from "convex/values"
import { paginationOptsValidator } from "convex/server"
import { ConvexError } from "convex/values"
import { query, mutation } from "${imports.generatedDirFromApi}/server"
import type { QueryCtx, MutationCtx } from "${imports.generatedDirFromApi}/server"
import { hasPermission, findCollectionBySlug } from "@vexcms/core"
import { getUser } from "${imports.authFromApi}"
import vexConfig from "${imports.vexConfigFromApi}"
import { ${modelFns.join(", ")} } from "../model/api/${slug}"`);

  // SLUG constant + requireAuth helper
  parts.push(`const SLUG = "${slug}" as const

async function requireAuth(ctx: QueryCtx | MutationCtx) {
  const auth = await getUser(ctx)
  if (!auth) throw new ConvexError("Not authenticated")
  return auth
}`);

  // getDocument
  parts.push(buildApiGetDocument({ tableName }));

  // listDocuments
  parts.push(buildApiListDocuments({ tableName }));

  // createDocument (not for media)
  if (!isMedia) {
    parts.push(buildApiCreateDocument({ slug, tableName }));
  }

  // updateDocument (not for media)
  if (!isMedia) {
    parts.push(buildApiUpdateDocument({ slug, tableName }));
  }

  // deleteDocument
  parts.push(buildApiDeleteDocument({ tableName }));

  // searchDocuments (only if search index)
  if (firstSearchIndex) {
    parts.push(buildApiSearchDocuments());
  }

  return parts.join("\n\n") + "\n";
}

export function buildApiGetDocument(props: { tableName: string }): string {
  const { tableName } = props;
  return `export const get = query({
  args: {
    id: v.id("${tableName}"),
    _vexDrafts: v.optional(v.union(v.literal("snapshot"), v.boolean())),
  },
  handler: async (ctx, args) => {
    const preview = (args._vexDrafts ?? "snapshot") === "snapshot"
    const doc = await getDocument({
      ctx,
      documentId: args.id,
      preview,
    })
    if (!doc) return null
    const auth = await getUser(ctx)
    if (auth) {
      const allowed = hasPermission({
        access: vexConfig.access,
        user: auth.user,
        userRoles: auth.roles,
        resource: SLUG,
        action: "read",
        data: doc,
      })
      if (!allowed) return null
    }
    return doc
  },
})`;
}

export function buildApiListDocuments(_props: { tableName: string }): string {
  return `export const list = query({
  args: {
    paginationOpts: paginationOptsValidator,
    order: v.optional(v.union(v.literal("asc"), v.literal("desc"))),
  },
  handler: async (ctx, args) => {
    const result = await listDocuments({
      ctx,
      paginationOpts: args.paginationOpts,
      order: args.order,
    })
    const auth = await getUser(ctx)
    if (!auth) return result
    const filteredPage = result.page.filter((doc) =>
      hasPermission({
        access: vexConfig.access,
        user: auth.user,
        userRoles: auth.roles,
        resource: SLUG,
        action: "read",
        data: doc,
      }) === true,
    )
    return { ...result, page: filteredPage }
  },
})`;
}

export function buildApiCreateDocument(_props: {
  slug: string;
  tableName: string;
}): string {
  return `export const create = mutation({
  args: { fields: v.any() },
  handler: async (ctx, args) => {
    const { user, roles } = await requireAuth(ctx)
    hasPermission({
      access: vexConfig.access,
      user,
      userRoles: roles,
      resource: SLUG,
      action: "create",
      throwOnDenied: true,
    })
    const collection = findCollectionBySlug({ slug: SLUG, config: vexConfig })
    if (!collection) throw new ConvexError(\`Collection "\${SLUG}" not found in vex config\`)
    return createDocument({
      collectionFields: collection.fields,
      ctx,
      fields: args.fields as unknown,
      kind: "collection",
    })
  },
})`;
}

export function buildApiUpdateDocument(props: {
  slug: string;
  tableName: string;
}): string {
  const { tableName } = props;
  return `export const update = mutation({
  args: { id: v.id("${tableName}"), fields: v.any() },
  handler: async (ctx, args) => {
    const { user, roles } = await requireAuth(ctx)
    hasPermission({
      access: vexConfig.access,
      user,
      userRoles: roles,
      resource: SLUG,
      action: "update",
      throwOnDenied: true,
    })
    const collection = findCollectionBySlug({ slug: SLUG, config: vexConfig })
    if (!collection) throw new ConvexError(\`Collection "\${SLUG}" not found in vex config\`)
    return updateDocument({
      collectionFields: collection.fields,
      ctx,
      documentId: args.id,
      fields: args.fields,
    })
  },
})`;
}

export function buildApiDeleteDocument(props: { tableName: string }): string {
  const { tableName } = props;
  return `export const remove = mutation({
  args: { id: v.id("${tableName}") },
  handler: async (ctx, args) => {
    const { user, roles } = await requireAuth(ctx)
    hasPermission({
      access: vexConfig.access,
      user,
      userRoles: roles,
      resource: SLUG,
      action: "delete",
      throwOnDenied: true,
    })
    await deleteDocument({
      ctx,
      documentId: args.id,
      kind: "collection",
    })
  },
})`;
}

export function buildApiSearchDocuments(): string {
  return `export const search = query({
  args: { query: v.string() },
  handler: async (ctx, args) => {
    const results = await searchDocuments({
      ctx,
      query: args.query,
    })
    const auth = await getUser(ctx)
    if (!auth) return results
    return results.filter((doc) =>
      hasPermission({
        access: vexConfig.access,
        user: auth.user,
        userRoles: auth.roles,
        resource: SLUG,
        action: "read",
        data: doc,
      }) === true,
    )
  },
})`;
}

// ─── Barrel index ────────────────────────────────────────────────────────────

/**
 * Generate the barrel `index.ts` that namespace-re-exports all collection files.
 */
export function generateIndexFile(props: { slugs: string[] }): string {
  const sorted = [...props.slugs].sort();
  if (sorted.length === 0) {
    return GENERATED_HEADER + "\n";
  }
  const exports = sorted
    .map((slug) => `export * as ${slug} from "./${slug}"`)
    .join("\n");
  return `${GENERATED_HEADER}\n${exports}\n`;
}
