import type { ResolvedIndex, VexConfig } from "../types";
import { fieldToValueType } from "./extract";
import { collectIndexes } from "./indexes";
import { mergeAuthTableWithCollection } from "./merge";
import { buildSlugRegistry } from "./slugs";

/**
 * Generates the full TypeScript source content for `convex/vex.schema.ts`.
 *
 * This is the main entry point for schema generation. It:
 * 1. Validates all slugs are unique (via SlugRegistry) — auth table slugs
 *    that overlap with user collection slugs are expected (merge, not conflict)
 * 2. For each auth table, checks if a matching user collection exists (by slug):
 *    a. If yes: merges auth table fields with collection fields (auth validators
 *       win for schema, user admin config wins for UI)
 *    b. If no matching collection: generates the auth table as-is
 * 3. User collections that don't match any auth table: generates from collection fields only
 * 4. Collects indexes from per-field `index` properties and collection-level `indexes`
 * 5. Generates defineTable() calls for each table with chained .index() calls
 * 6. Generates defineTable() calls for system tables (vex_globals if globals exist)
 *
 * The output is a complete, valid TypeScript file that can be written to disk.
 * Users import these named exports in their own `schema.ts` and can chain
 * additional Convex methods (e.g., `.index()`, `.searchIndex()`) before
 * passing to `defineSchema()`.
 *
 * @param config - The resolved VexConfig from defineConfig()
 * @returns TypeScript source code string for vex.schema.ts
 *
 * Output format:
 * ```typescript
 * // ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT
 * // This file is regenerated when your vex config changes.
 * // To customize tables, edit convex/schema.ts instead.
 *
 * import { defineTable } from "convex/server";
 * import { v } from "convex/values";
 *
 * export const posts = defineTable({
 *   title: v.string(),
 *   slug: v.optional(v.string()),
 * })
 *   .index("by_slug", ["slug"]);
 *
 * export const user = defineTable({
 *   name: v.string(),
 *   email: v.string(),
 *   emailVerified: v.boolean(),
 *   ...
 * });
 *
 * export const account = defineTable({
 *   userId: v.id("user"),
 *   ...
 * })
 *   .index("by_userId", ["userId"]);
 * ```
 *
 * User's schema.ts can then extend:
 * ```typescript
 * import { posts, account, user } from "./vex.schema";
 * import { defineSchema } from "convex/server";
 *
 * export default defineSchema({
 *   posts: posts.index("by_author_date", ["author", "_creationTime"]),
 *   account,
 *   user,
 *   // custom tables...
 * });
 * ```
 *
 * Edge cases:
 * - Empty collections + no auth tables: generate file with only the header comment and imports
 * - Collection with no fields: generate `defineTable({})` (valid but unusual)
 * - Auth adapter with no tables: skip auth table section
 * - Auth table matches user collection: merge fields (auth validators win)
 * - Auth table with no matching collection: generate as standalone table
 * - Globals configured: add vex_globals system table
 * - No globals: skip vex_globals table
 * - Field with quotes in select option values: escape properly in literals
 * - Slug validation fails: throw before generating any output
 * - Per-field indexes + collection-level indexes: both appear as chained .index() calls
 * - Auth table indexes: appear as chained .index() calls on auth tables
 * - Duplicate index names within a collection: error at generation time
 */
export function generateVexSchema(props: { config: VexConfig }): string {
  const config = props.config;
  buildSlugRegistry({ config });
  const authTableMap = new Map(config.auth.tables.map((t) => [t.slug, t]));
  const mergedAuthSlugs = new Set<string>();

  const lines: string[] = [
    "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️",
    "",
    'import { defineTable } from "convex/server";',
    'import { v } from "convex/values";',
  ];

  if (config.collections.length > 0) {
    lines.push("", "/**", " * USER COLLECTIONS", " **/");
  }

  for (const collection of config.collections) {
    const authTable = authTableMap.get(collection.slug);
    const fields: { name: string; valueType: string }[] = [];
    const indexes: ResolvedIndex[] = collectIndexes({ collection });

    if (authTable) {
      mergedAuthSlugs.add(authTable.slug);
      const merged = mergeAuthTableWithCollection({ authTable, collection });
      for (const [name, valueType] of Object.entries(merged.fields)) {
        fields.push({ name, valueType });
      }
      for (const index of authTable.indexes ?? []) {
        if (indexes.find((ui) => ui.name === index.name)) continue;
        indexes.push(index);
      }
    } else {
      for (const [fieldName, field] of Object.entries(
        collection.config.fields,
      )) {
        fields.push({
          name: fieldName,
          valueType: fieldToValueType({
            fieldName,
            field,
            collectionSlug: collection.slug,
          }),
        });
      }
    }

    lines.push(
      "",
      `export const ${collection.config.tableName ?? collection.slug} = defineTable({`,
    );
    for (const f of fields) {
      lines.push(`  ${f.name}: ${f.valueType},`);
    }
    lines.push("})");
    for (const i of indexes) {
      const fieldList = i.fields.map((f) => `"${f}"`).join(", ");
      lines.push(`  .index("${i.name}", [${fieldList}])`);
    }
  }

  const unmergedAuthTables = config.auth.tables.filter(
    (t) => !mergedAuthSlugs.has(t.slug),
  );

  if (unmergedAuthTables.length > 0) {
    lines.push("", "/**", " * AUTH TABLES", " **/");
  }

  for (const table of unmergedAuthTables) {
    const indexes = table.indexes ?? [];
    lines.push("", `export const ${table.slug} = defineTable({`);
    for (const [name, f] of Object.entries(table.fields)) {
      lines.push(`  ${name}: ${f.valueType},`);
    }
    lines.push("})");
    for (const i of indexes) {
      const fieldList = i.fields.map((f) => `"${f}"`).join(", ");
      lines.push(`  .index("${i.name}", [${fieldList}])`);
    }
  }

  for (const global of config.globals) {
    const fields: { name: string; valueType: string }[] = [];
    const indexes: ResolvedIndex[] = collectIndexes({ collection: global });
    for (const [fieldName, field] of Object.entries(global.config.fields)) {
      fields.push({
        name: fieldName,
        valueType: fieldToValueType({
          fieldName,
          field,
          collectionSlug: global.slug,
        }),
      });
    }

    lines.push(
      "",
      `export const ${global.config.tableName ?? global.slug} = defineTable({`,
    );
    for (const f of fields) {
      lines.push(`  ${f.name}: ${f.valueType},`);
    }
    lines.push("})");
    for (const i of indexes) {
      const fieldList = i.fields.map((f) => `"${f}"`).join(", ");
      lines.push(`  .index("${i.name}", [${fieldList}])`);
    }
  }

  return lines.join("\n") + "\n";
}
