import type { ResolvedIndex, ResolvedSearchIndex, VexConfig, VexField } from "../types";
import { fieldToValueType } from "./extract";
import { collectIndexes } from "./indexes";
import { collectSearchIndexes } from "./searchIndexes";
import { mergeAuthCollectionWithUserCollection } from "./merge";
import { buildSlugRegistry } from "./slugs";

/**
 * Generates the full TypeScript source content for `convex/vex.schema.ts`.
 *
 * This is the main entry point for schema generation. It:
 * 1. Validates all slugs are unique (via SlugRegistry)
 * 2. For each auth collection, checks if a matching user collection exists (by slug):
 *    a. If yes: merges auth collection fields with user collection fields
 *    b. If no matching collection: generates the auth collection as-is
 * 3. User collections that don't match any auth collection: generates from collection fields only
 * 4. Collects indexes from per-field `index` properties and collection-level `indexes`
 * 5. Generates defineTable() calls for each table with chained .index() calls
 * 6. Generates defineTable() calls for system tables (vex_globals if globals exist)
 *
 * All fields go through fieldToValueType() uniformly — no dual path for auth vs user.
 */
export function generateVexSchema(props: { config: VexConfig }): string {
  const config = props.config;
  buildSlugRegistry({ config });
  const authCollectionMap = new Map(
    config.auth.collections.map((c) => [c.slug, c]),
  );
  const mergedAuthSlugs = new Set<string>();

  const lines: string[] = [
    "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️",
    "",
    'import { defineTable } from "convex/server";',
    'import { v } from "convex/values";',
  ];

  if (config.collections.length > 0) {
    lines.push("", "/**", " * USER COLLECTIONS", " **/");
  }

  for (const collection of config.collections) {
    const authCollection = authCollectionMap.get(collection.slug);
    const fields: { name: string; valueType: string }[] = [];
    const indexes: ResolvedIndex[] = collectIndexes({ collection });
    const searchIndexes: ResolvedSearchIndex[] = collectSearchIndexes({
      collection,
    });

    if (authCollection) {
      mergedAuthSlugs.add(authCollection.slug);
      const merged = mergeAuthCollectionWithUserCollection({
        authCollection,
        userCollection: collection,
      });

      // All merged fields go through fieldToValueType uniformly
      for (const [name, field] of Object.entries(merged.fields)) {
        fields.push({
          name,
          valueType: fieldToValueType({
            field,
            collectionSlug: collection.slug,
            fieldName: name,
          }),
        });
      }

      // Add merged indexes (deduplicated)
      for (const index of merged.indexes) {
        if (indexes.find((ui) => ui.name === index.name)) continue;
        indexes.push(index);
      }

      // Add merged search indexes
      for (const si of merged.searchIndexes) {
        if (searchIndexes.find((existing) => existing.name === si.name))
          continue;
        searchIndexes.push(si);
      }
    } else {
      for (const [fieldName, field] of Object.entries(
        collection.fields,
      ) as [string, VexField][]) {
        fields.push({
          name: fieldName,
          valueType: fieldToValueType({
            fieldName,
            field,
            collectionSlug: collection.slug,
          }),
        });
      }
    }

    lines.push(
      "",
      `export const ${collection.tableName ?? collection.slug} = defineTable({`,
    );
    for (const f of fields) {
      lines.push(`  ${f.name}: ${f.valueType},`);
    }
    // vex_status on all user collections — defaults to "published"
    lines.push(`  vex_status: v.optional(v.union(v.literal("draft"), v.literal("published"))),`);
    if (collection.versions?.drafts) {
      lines.push(`  vex_version: v.optional(v.number()),`);
      lines.push(`  vex_publishedAt: v.optional(v.number()),`);
    }
    lines.push("})");
    for (const i of indexes) {
      const fieldList = i.fields.map((f) => `"${f}"`).join(", ");
      lines.push(`  .index("${i.name}", [${fieldList}])`);
    }
    for (const si of searchIndexes) {
      const filterList =
        si.filterFields.length > 0
          ? `, filterFields: [${si.filterFields.map((f) => `"${f}"`).join(", ")}]`
          : "";
      lines.push(
        `  .searchIndex("${si.name}", { searchField: "${si.searchField}"${filterList} })`,
      );
    }
  }

  // --- MEDIA COLLECTIONS ---
  if (config.media && config.media.collections.length > 0) {
    lines.push("", "/**", " * MEDIA COLLECTIONS", " **/");

    for (const mediaCollection of config.media.collections) {
      const fields: { name: string; valueType: string }[] = [];
      const indexes: ResolvedIndex[] = collectIndexes({ collection: mediaCollection });
      const searchIndexes: ResolvedSearchIndex[] = collectSearchIndexes({
        collection: mediaCollection,
      });

      for (const [fieldName, field] of Object.entries(
        mediaCollection.fields,
      ) as [string, VexField][]) {
        if (fieldName === "storageId") {
          // Use adapter's storageIdValueType instead of fieldToValueType
          fields.push({
            name: fieldName,
            valueType: config.media.storageAdapter.storageIdValueType,
          });
        } else {
          fields.push({
            name: fieldName,
            valueType: fieldToValueType({
              fieldName,
              field,
              collectionSlug: mediaCollection.slug,
            }),
          });
        }
      }

      lines.push(
        "",
        `export const ${mediaCollection.tableName ?? mediaCollection.slug} = defineTable({`,
      );
      for (const f of fields) {
        lines.push(`  ${f.name}: ${f.valueType},`);
      }
      lines.push("})");
      for (const i of indexes) {
        const fieldList = i.fields.map((f) => `"${f}"`).join(", ");
        lines.push(`  .index("${i.name}", [${fieldList}])`);
      }
      for (const si of searchIndexes) {
        const filterList =
          si.filterFields.length > 0
            ? `, filterFields: [${si.filterFields.map((f) => `"${f}"`).join(", ")}]`
            : "";
        lines.push(
          `  .searchIndex("${si.name}", { searchField: "${si.searchField}"${filterList} })`,
        );
      }
    }
  }

  const unmergedAuthCollections = config.auth.collections.filter(
    (c) => !mergedAuthSlugs.has(c.slug),
  );

  if (unmergedAuthCollections.length > 0) {
    lines.push("", "/**", " * AUTH TABLES", " **/");
  }

  for (const authCollection of unmergedAuthCollections) {
    const indexes: ResolvedIndex[] = collectIndexes({
      collection: authCollection,
    });
    lines.push(
      "",
      `export const ${authCollection.tableName ?? authCollection.slug} = defineTable({`,
    );
    for (const [name, field] of Object.entries(authCollection.fields) as [string, VexField][]) {
      lines.push(
        `  ${name}: ${fieldToValueType({
          field,
          collectionSlug: authCollection.slug,
          fieldName: name,
        })},`,
      );
    }
    lines.push("})");
    for (const i of indexes) {
      const fieldList = i.fields.map((f) => `"${f}"`).join(", ");
      lines.push(`  .index("${i.name}", [${fieldList}])`);
    }
  }

  for (const global of config.globals) {
    const fields: { name: string; valueType: string }[] = [];
    const indexes: ResolvedIndex[] = collectIndexes({ collection: global });
    for (const [fieldName, field] of Object.entries(global.fields)) {
      fields.push({
        name: fieldName,
        valueType: fieldToValueType({
          fieldName,
          field,
          collectionSlug: global.slug,
        }),
      });
    }

    lines.push(
      "",
      `export const ${global.tableName ?? global.slug} = defineTable({`,
    );
    for (const f of fields) {
      lines.push(`  ${f.name}: ${f.valueType},`);
    }
    lines.push("})");
    for (const i of indexes) {
      const fieldList = i.fields.map((f) => `"${f}"`).join(", ");
      lines.push(`  .index("${i.name}", [${fieldList}])`);
    }
  }

  // Always generate vex_versions so removing versioning from a collection
  // doesn't break schema.ts imports that reference vex_versions.
  {
    lines.push("", "/**", " * VEX SYSTEM TABLES", " **/");
    lines.push("");
    lines.push("export const vex_versions = defineTable({");
    lines.push("  collection: v.string(),");
    lines.push("  documentId: v.string(),");
    lines.push("  version: v.number(),");
    lines.push(`  status: v.union(v.literal("draft"), v.literal("published"), v.literal("autosave")),`);
    lines.push("  snapshot: v.any(),");
    lines.push("  createdAt: v.number(),");
    lines.push("  createdBy: v.optional(v.string()),");
    lines.push("  isAutosave: v.boolean(),");
    lines.push("  restoredFrom: v.optional(v.number()),");
    lines.push("})");
    lines.push(`  .index("by_document", ["collection", "documentId"])`);
    lines.push(`  .index("by_document_version", ["collection", "documentId", "version"])`);
    lines.push(`  .index("by_document_latest", ["collection", "documentId", "createdAt"])`);
    lines.push(`  .index("by_document_status", ["collection", "documentId", "status"])`);
    lines.push(`  .index("by_autosave", ["collection", "documentId", "isAutosave"])`);
  }

  return lines.join("\n") + "\n";
}
