import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  mkdirSync,
  mkdtempSync,
  rmSync,
  writeFileSync,
  readFileSync,
  existsSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { defineCollection, defineConfig, text } from "@vexcms/core";
import {
  deriveConvexDir,
  computeImportPaths,
  generateAndWriteCollectionFiles,
} from "./generateCollectionFiles";

const stubAuth = { name: "stub", collections: [] as any[], plugin: {} as any, tables: {}, options: {} as any };

// ─── deriveConvexDir ─────────────────────────────────────────────────────────

describe("deriveConvexDir", () => {
  it("returns convex for default outputPath", () => {
    expect(deriveConvexDir({ outputPath: "/convex/vex.schema.ts" })).toBe(
      "convex",
    );
  });

  it("handles nested convex dir", () => {
    expect(deriveConvexDir({ outputPath: "/src/convex/generated.ts" })).toBe(
      "src/convex",
    );
  });

  it("handles path without leading slash", () => {
    expect(deriveConvexDir({ outputPath: "convex/vex.schema.ts" })).toBe(
      "convex",
    );
  });
});

// ─── computeImportPaths ──────────────────────────────────────────────────────

describe("computeImportPaths", () => {
  it("returns correct paths for default convex dir", () => {
    const paths = computeImportPaths({ cwd: "/project", convexDir: "convex" });
    // api/ is at /project/convex/vex/api/
    expect(paths.vexConfigFromApi).toBe("../../../vex.config");
    expect(paths.generatedDirFromApi).toBe("../../_generated");
    expect(paths.authFromApi).toBe("../auth");
    // model/api/ is at /project/convex/vex/model/api/
    expect(paths.generatedDirFromModel).toBe("../../../_generated");
  });

  it("returns correct paths for nested convex dir", () => {
    const paths = computeImportPaths({
      cwd: "/project",
      convexDir: "src/convex",
    });
    expect(paths.vexConfigFromApi).toBe("../../../../vex.config");
    expect(paths.generatedDirFromApi).toBe("../../_generated");
    expect(paths.authFromApi).toBe("../auth");
    expect(paths.generatedDirFromModel).toBe("../../../_generated");
  });

  it("all paths start with ./ or ../", () => {
    const paths = computeImportPaths({ cwd: "/project", convexDir: "convex" });
    for (const p of Object.values(paths)) {
      expect(p.startsWith("./") || p.startsWith("../")).toBe(true);
    }
  });

  it("uses forward slashes (cross-platform)", () => {
    const paths = computeImportPaths({ cwd: "/project", convexDir: "convex" });
    for (const p of Object.values(paths)) {
      expect(p).not.toContain("\\");
    }
  });
});

// ─── generateAndWriteCollectionFiles ─────────────────────────────────────────

describe("generateAndWriteCollectionFiles", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "vex-test-"));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("creates api and model/api files for each collection", async () => {
    const articles = defineCollection({
      slug: "articles",
      fields: { title: text({ required: true }) },
    });
    const config = defineConfig({ auth: stubAuth, collections: [articles] });

    await generateAndWriteCollectionFiles({ config, cwd: tmpDir });

    expect(existsSync(join(tmpDir, "convex/vex/api/articles.ts"))).toBe(true);
    expect(existsSync(join(tmpDir, "convex/vex/model/api/articles.ts"))).toBe(true);
  });

  it("always creates api/index.ts", async () => {
    const config = defineConfig({ auth: stubAuth, collections: [] });
    await generateAndWriteCollectionFiles({ config, cwd: tmpDir });

    expect(existsSync(join(tmpDir, "convex/vex/api/index.ts"))).toBe(true);
  });

  it("deletes stale generated files from both directories", async () => {
    // Pre-create stale files
    const apiDir = join(tmpDir, "convex/vex/api");
    const modelDir = join(tmpDir, "convex/vex/model/api");
    mkdirSync(apiDir, { recursive: true });
    mkdirSync(modelDir, { recursive: true });

    const staleApi = join(apiDir, "old_collection.ts");
    const staleModel = join(modelDir, "old_collection.ts");
    const header = "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️\nexport const get = null";
    writeFileSync(staleApi, header);
    writeFileSync(staleModel, header);

    const config = defineConfig({ auth: stubAuth, collections: [] });
    const { deleted } = await generateAndWriteCollectionFiles({
      config,
      cwd: tmpDir,
    });

    expect(existsSync(staleApi)).toBe(false);
    expect(existsSync(staleModel)).toBe(false);
    expect(deleted).toContain("api/old_collection.ts");
    expect(deleted).toContain("model/api/old_collection.ts");
  });

  it("does NOT delete user-created files", async () => {
    const apiDir = join(tmpDir, "convex/vex/api");
    mkdirSync(apiDir, { recursive: true });
    const userFile = join(apiDir, "my_custom.ts");
    writeFileSync(userFile, "// User file\nexport const custom = null");

    const config = defineConfig({ auth: stubAuth, collections: [] });
    await generateAndWriteCollectionFiles({ config, cwd: tmpDir });

    expect(existsSync(userFile)).toBe(true);
  });

  it("skips re-writing files with identical content", async () => {
    const articles = defineCollection({
      slug: "articles",
      fields: { title: text({ required: true }) },
    });
    const config = defineConfig({ auth: stubAuth, collections: [articles] });

    const { written: firstWritten } = await generateAndWriteCollectionFiles({
      config,
      cwd: tmpDir,
    });
    const { written: secondWritten } = await generateAndWriteCollectionFiles({
      config,
      cwd: tmpDir,
    });

    expect(firstWritten.length).toBeGreaterThan(0);
    expect(secondWritten.length).toBe(0);
  });

  it("api file imports from model/api/", async () => {
    const articles = defineCollection({
      slug: "articles",
      fields: { title: text({ required: true }) },
    });
    const config = defineConfig({ auth: stubAuth, collections: [articles] });

    await generateAndWriteCollectionFiles({ config, cwd: tmpDir });

    const apiContent = readFileSync(
      join(tmpDir, "convex/vex/api/articles.ts"),
      "utf-8",
    );
    expect(apiContent).toContain('from "../model/api/articles"');
  });

  it("model file uses typed Doc and Id", async () => {
    const articles = defineCollection({
      slug: "articles",
      fields: { title: text({ required: true }) },
    });
    const config = defineConfig({ auth: stubAuth, collections: [articles] });

    await generateAndWriteCollectionFiles({ config, cwd: tmpDir });

    const modelContent = readFileSync(
      join(tmpDir, "convex/vex/model/api/articles.ts"),
      "utf-8",
    );
    expect(modelContent).toContain('Doc<"articles">');
    expect(modelContent).toContain('Id<"articles">');
  });
});
