import { describe, it, expect } from "vitest";
import { diffSchema, addRemovedFieldsAsOptional } from "./diffSchema";

// Helper: minimal valid schema with given tables
function schema(tables: string): string {
  return [
    '// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️',
    "",
    'import { defineTable } from "convex/server";',
    'import { v } from "convex/values";',
    "",
    tables,
    "",
  ].join("\n");
}

describe("diffSchema", () => {
  it("returns diff when old schema is empty", () => {
    const newSchema = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.optional(v.string()),
})`);

    const diff = diffSchema("", newSchema);

    expect(diff.addedRequired).toEqual([
      { table: "posts", field: "title", valueType: "v.string()", isOptional: false },
    ]);
    expect(diff.addedOptional).toEqual([
      { table: "posts", field: "slug", valueType: "v.optional(v.string())", isOptional: true },
    ]);
    expect(diff.newRequired).toEqual([]);
    expect(diff.removedFields).toEqual([]);
    expect(diff.needsMigration).toHaveLength(2);
  });

  it("returns empty diff when schemas are identical", () => {
    const s = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.optional(v.string()),
})`);

    const diff = diffSchema(s, s);

    expect(diff.addedRequired).toEqual([]);
    expect(diff.addedOptional).toEqual([]);
    expect(diff.newRequired).toEqual([]);
    expect(diff.removedFields).toEqual([]);
    expect(diff.needsMigration).toEqual([]);
  });

  it("detects new optional field as addedOptional", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
  description: v.optional(v.string()),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.addedOptional).toEqual([
      { table: "posts", field: "description", valueType: "v.optional(v.string())", isOptional: true },
    ]);
    expect(diff.addedRequired).toEqual([]);
    expect(diff.needsMigration).toHaveLength(1);
  });

  it("detects new required field as addedRequired", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.string(),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.addedRequired).toEqual([
      { table: "posts", field: "slug", valueType: "v.string()", isOptional: false },
    ]);
    expect(diff.newRequired).toEqual([]);
    expect(diff.needsMigration).toHaveLength(1);
  });

  it("detects field changed from optional to required as newRequired", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.optional(v.string()),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.string(),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.newRequired).toEqual([
      { table: "posts", field: "slug", valueType: "v.string()", isOptional: false },
    ]);
    expect(diff.addedRequired).toEqual([]);
    expect(diff.needsMigration).toHaveLength(1);
  });

  it("does not flag field changed from required to optional", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.string(),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.optional(v.string()),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.needsMigration).toEqual([]);
  });

  it("handles multiple tables with mixed changes", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
})

export const users = defineTable({
  email: v.string(),
  name: v.optional(v.string()),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
  views: v.number(),
})

export const users = defineTable({
  email: v.string(),
  name: v.string(),
  role: v.optional(v.string()),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.addedRequired).toEqual([
      { table: "posts", field: "views", valueType: "v.number()", isOptional: false },
    ]);
    expect(diff.addedOptional).toEqual([
      { table: "users", field: "role", valueType: "v.optional(v.string())", isOptional: true },
    ]);
    expect(diff.newRequired).toEqual([
      { table: "users", field: "name", valueType: "v.string()", isOptional: false },
    ]);
    expect(diff.needsMigration).toHaveLength(3);
  });

  it("handles auth tables correctly (required fields detected)", () => {
    const old = schema(`export const account = defineTable({
  userId: v.id("users"),
  providerId: v.string(),
})`);

    const newS = schema(`export const account = defineTable({
  userId: v.id("users"),
  providerId: v.string(),
  scope: v.string(),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.addedRequired).toEqual([
      { table: "account", field: "scope", valueType: "v.string()", isOptional: false },
    ]);
  });

  it("detects removed fields", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
  deprecated: v.string(),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.needsMigration).toEqual([]);
    expect(diff.removedFields).toEqual([
      { table: "posts", field: "deprecated", valueType: "v.string()", wasOptional: false },
    ]);
  });

  it("detects multiple removed fields across tables", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
  subtitle: v.string(),
  views: v.number(),
})

export const users = defineTable({
  email: v.string(),
  nickname: v.optional(v.string()),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
})

export const users = defineTable({
  email: v.string(),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.removedFields).toEqual([
      { table: "posts", field: "subtitle", valueType: "v.string()", wasOptional: false },
      { table: "posts", field: "views", valueType: "v.number()", wasOptional: false },
      { table: "users", field: "nickname", valueType: "v.optional(v.string())", wasOptional: true },
    ]);
  });

  it("does not flag removed fields when entire table is removed", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
})

export const tags = defineTable({
  name: v.string(),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const diff = diffSchema(old, newS);

    // tags table was entirely removed — we don't list individual fields
    expect(diff.removedFields).toEqual([]);
  });

  it("ignores index-only changes", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.string(),
})`);

    // Same fields, different indexes — the regex extracts fields inside defineTable({ ... })
    const newS = schema(`export const posts = defineTable({
  title: v.string(),
  slug: v.string(),
})
  .index("by_slug", ["slug"])`);

    const diff = diffSchema(old, newS);

    expect(diff.needsMigration).toEqual([]);
  });

  it("detects new table with all required fields", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
})

export const categories = defineTable({
  name: v.string(),
  order: v.number(),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.addedRequired).toEqual([
      { table: "categories", field: "name", valueType: "v.string()", isOptional: false },
      { table: "categories", field: "order", valueType: "v.number()", isOptional: false },
    ]);
  });

  it("detects new table with all optional fields as addedOptional", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
})

export const settings = defineTable({
  theme: v.optional(v.string()),
  language: v.optional(v.string()),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.addedRequired).toEqual([]);
    expect(diff.addedOptional).toEqual([
      { table: "settings", field: "theme", valueType: "v.optional(v.string())", isOptional: true },
      { table: "settings", field: "language", valueType: "v.optional(v.string())", isOptional: true },
    ]);
    expect(diff.needsMigration).toHaveLength(2);
  });

  it("handles select union value types", () => {
    const old = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const newS = schema(`export const posts = defineTable({
  title: v.string(),
  status: v.union(v.literal("draft"),v.literal("published")),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.addedRequired).toEqual([
      {
        table: "posts",
        field: "status",
        valueType: 'v.union(v.literal("draft"),v.literal("published"))',
        isOptional: false,
      },
    ]);
  });

  it("handles v.id() value types", () => {
    const old = schema(`export const account = defineTable({
  providerId: v.string(),
})`);

    const newS = schema(`export const account = defineTable({
  providerId: v.string(),
  userId: v.id("users"),
})`);

    const diff = diffSchema(old, newS);

    expect(diff.addedRequired).toEqual([
      {
        table: "account",
        field: "userId",
        valueType: 'v.id("users")',
        isOptional: false,
      },
    ]);
  });
});

describe("addRemovedFieldsAsOptional", () => {
  it("re-inserts a removed required field as optional", () => {
    const newSchema = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const result = addRemovedFieldsAsOptional(newSchema, [
      { table: "posts", field: "subtitle", valueType: "v.string()", wasOptional: false },
    ]);

    expect(result).toContain("subtitle: v.optional(v.string()),");
    expect(result).toContain("title: v.string(),");
  });

  it("re-inserts a removed optional field as-is", () => {
    const newSchema = schema(`export const posts = defineTable({
  title: v.string(),
})`);

    const result = addRemovedFieldsAsOptional(newSchema, [
      { table: "posts", field: "views", valueType: "v.optional(v.number())", wasOptional: true },
    ]);

    expect(result).toContain("views: v.optional(v.number()),");
  });

  it("handles multiple removed fields in the same table", () => {
    const newSchema = schema(`export const user = defineTable({
  email: v.string(),
})`);

    const result = addRemovedFieldsAsOptional(newSchema, [
      { table: "user", field: "zip", valueType: "v.string()", wasOptional: false },
      { table: "user", field: "nickname", valueType: "v.optional(v.string())", wasOptional: true },
    ]);

    expect(result).toContain("zip: v.optional(v.string()),");
    expect(result).toContain("nickname: v.optional(v.string()),");
    expect(result).toContain("email: v.string(),");
  });
});
