// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
import { v } from "convex/values"
import { paginationOptsValidator } from "convex/server"
import { ConvexError } from "convex/values"
import { query, mutation } from "../../_generated/server"
import type { QueryCtx, MutationCtx } from "../../_generated/server"
import { hasPermission, findCollectionBySlug } from "@vexcms/core"
import { getUser } from "../auth"
import vexConfig from "../../../vex.config"
import { getDocument, listDocuments, createDocument, updateDocument, deleteDocument } from "../model/api/pages"

const SLUG = "pages" as const

async function requireAuth(ctx: QueryCtx | MutationCtx) {
  const auth = await getUser(ctx)
  if (!auth) throw new ConvexError("Not authenticated")
  return auth
}

export const get = query({
  args: {
    id: v.id("pages"),
    _vexDrafts: v.optional(v.union(v.literal("snapshot"), v.boolean())),
  },
  handler: async (ctx, args) => {
    const preview = (args._vexDrafts ?? "snapshot") === "snapshot"
    const doc = await getDocument({
      ctx,
      documentId: args.id,
      preview,
    })
    if (!doc) return null
    const auth = await getUser(ctx)
    if (auth) {
      const allowed = hasPermission({
        access: vexConfig.access,
        user: auth.user,
        userRoles: auth.roles,
        resource: SLUG,
        action: "read",
        data: doc,
      })
      if (!allowed) return null
    }
    return doc
  },
})

export const list = query({
  args: {
    paginationOpts: paginationOptsValidator,
    order: v.optional(v.union(v.literal("asc"), v.literal("desc"))),
  },
  handler: async (ctx, args) => {
    const result = await listDocuments({
      ctx,
      paginationOpts: args.paginationOpts,
      order: args.order,
    })
    const auth = await getUser(ctx)
    if (!auth) return result
    const filteredPage = result.page.filter((doc) =>
      hasPermission({
        access: vexConfig.access,
        user: auth.user,
        userRoles: auth.roles,
        resource: SLUG,
        action: "read",
        data: doc,
      }) === true,
    )
    return { ...result, page: filteredPage }
  },
})

export const create = mutation({
  args: { fields: v.any() },
  handler: async (ctx, args) => {
    const { user, roles } = await requireAuth(ctx)
    hasPermission({
      access: vexConfig.access,
      user,
      userRoles: roles,
      resource: SLUG,
      action: "create",
      throwOnDenied: true,
    })
    const collection = findCollectionBySlug({ slug: SLUG, config: vexConfig })
    if (!collection) throw new ConvexError(`Collection "${SLUG}" not found in vex config`)
    return createDocument({
      collectionFields: collection.fields,
      ctx,
      fields: args.fields as unknown,
      kind: "collection",
    })
  },
})

export const update = mutation({
  args: { id: v.id("pages"), fields: v.any() },
  handler: async (ctx, args) => {
    const { user, roles } = await requireAuth(ctx)
    hasPermission({
      access: vexConfig.access,
      user,
      userRoles: roles,
      resource: SLUG,
      action: "update",
      throwOnDenied: true,
    })
    const collection = findCollectionBySlug({ slug: SLUG, config: vexConfig })
    if (!collection) throw new ConvexError(`Collection "${SLUG}" not found in vex config`)
    return updateDocument({
      collectionFields: collection.fields,
      ctx,
      documentId: args.id,
      fields: args.fields,
    })
  },
})

export const remove = mutation({
  args: { id: v.id("pages") },
  handler: async (ctx, args) => {
    const { user, roles } = await requireAuth(ctx)
    hasPermission({
      access: vexConfig.access,
      user,
      userRoles: roles,
      resource: SLUG,
      action: "delete",
      throwOnDenied: true,
    })
    await deleteDocument({
      ctx,
      documentId: args.id,
      kind: "collection",
    })
  },
})
