// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
import type { Doc, Id } from "../../../_generated/dataModel"
import type { QueryCtx, MutationCtx } from "../../../_generated/server"
import type { WithoutSystemFields } from "convex/server"
import { ConvexError } from "convex/values"
import { getPreviewSnapshot, generateFormSchema } from "@vexcms/core"
import type { CollectionKind, VexField } from "@vexcms/core"

export async function getDocument(props: {
  ctx: QueryCtx
  documentId: Id<"headers">
  preview?: boolean
}): Promise<Doc<"headers"> | null> {
  const doc = await props.ctx.db.get(props.documentId)
  if (!doc) return null

  if (props.preview) {
    const snapshot = await getPreviewSnapshot({
      ctx: props.ctx,
      collection: "headers",
      documentId: props.documentId,
    })
    if (snapshot) {
      return { ...doc, ...snapshot } as Doc<"headers">
    }
  }

  return doc
}

export async function listDocuments(props: {
  ctx: QueryCtx
  paginationOpts: { numItems: number; cursor: string | null }
  order?: "asc" | "desc"
}) {
  const q = props.order === "desc"
    ? props.ctx.db.query("headers").order("desc")
    : props.ctx.db.query("headers")
  return await q.paginate(props.paginationOpts)
}

export async function createDocument(props: {
  collectionFields: Record<string, VexField>
  ctx: MutationCtx
  fields: unknown
  kind: CollectionKind
}): Promise<Id<"headers">> {
  if (props.kind === "global") {
    const existing = await props.ctx.db.query("headers").first()
    if (existing) {
      throw new ConvexError(`Global "headers" already exists. Globals can only have one document.`)
    }
  }

  const schema = generateFormSchema({ fields: props.collectionFields })
  const parsed = schema.safeParse(props.fields)
  if (!parsed.success) {
    throw new ConvexError({ message: "Validation failed", errors: parsed.error.flatten() })
  }

  const data = { ...parsed.data }
  data.vex_status ??= "published"
  return await props.ctx.db.insert("headers", data as WithoutSystemFields<Doc<"headers">>)
}

export async function updateDocument(props: {
  collectionFields: Record<string, VexField>
  ctx: MutationCtx
  documentId: Id<"headers">
  fields: unknown
}): Promise<Id<"headers">> {
  const schema = generateFormSchema({ fields: props.collectionFields }).partial()
  const parsed = schema.safeParse(props.fields)
  if (!parsed.success) {
    throw new ConvexError({ message: "Validation failed", errors: parsed.error.flatten() })
  }

  await props.ctx.db.patch(props.documentId, parsed.data as Partial<Doc<"headers">>)
  return props.documentId
}

export async function deleteDocument(props: {
  ctx: MutationCtx
  documentId: Id<"headers">
  kind: CollectionKind
}): Promise<void> {
  if (props.kind === "global") {
    const existing = await props.ctx.db.get(props.documentId)
    if (!existing) {
      throw new ConvexError(`Global "headers" document not found. Cannot delete a non-existent global.`)
    }
  }

  await props.ctx.db.delete(props.documentId)
}
