import { describe, it, expect } from "vitest";
import { defineConfig, defineCollection, defineGlobal } from "../index";
import { url, text, number, checkbox, date, select } from "../fields";
import { generateVexSchema } from "./generateVexSchema";

const HEADER = "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️";

// ─── Header ──────────────────────────────────────────────────────────────────

describe("generateVexSchema — header", () => {
  it("always includes the auto-generated header on line 1", () => {
    const config = defineConfig();
    const output = generateVexSchema({ config });
    expect(output.contents.split("\n")[0]).toBe(HEADER);
  });

  it("returns only the header when there are no collections", () => {
    const config = defineConfig();
    const output = generateVexSchema({ config });
    expect(output.contents).not.toContain("defineTable");
    expect(output.contents).not.toContain("import");
  });

  it("returns update: false when there are no collections", () => {
    const config = defineConfig();
    const output = generateVexSchema({ config });
    expect(output.update).toBe(false);
  });
});

// ─── Imports ─────────────────────────────────────────────────────────────────

describe("generateVexSchema — imports", () => {
  it("includes convex/server and convex/values imports when there are collections", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "posts", fields: { title: url() } })],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain('import { defineTable } from "convex/server"');
    expect(output.contents).toContain('import { v } from "convex/values"');
  });

  it("returns update: true when there are collections", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "posts", fields: { title: url() } })],
    });
    const output = generateVexSchema({ config });
    expect(output.update).toBe(true);
  });
});

// ─── Fields ──────────────────────────────────────────────────────────────────

describe("generateVexSchema — field validators", () => {
  it("generates required text field as v.string()", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: url({ required: true }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("title: v.string()");
  });

  it("generates optional text field as v.optional(v.string())", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { excerpt: url({ required: false }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("excerpt: v.optional(v.string())");
  });

  it("generates required number field as v.number()", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { views: number({ required: true }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("views: v.number()");
  });

  it("generates optional checkbox field as v.optional(v.boolean())", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { published: checkbox({ required: false }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("published: v.optional(v.boolean())");
  });

  it("generates optional date field as v.optional(v.number())", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { publishedAt: date({ required: false }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("publishedAt: v.optional(v.number())");
  });

  it("generates required select field as v.array(v.union(...))", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            status: select({
              required: true,
              options: [
                { label: "Draft", value: "draft" },
                { label: "Published", value: "published" },
              ],
            }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain(
      'status: v.array(v.union(v.literal("draft"), v.literal("published")))',
    );
  });
});

// ─── Exports ─────────────────────────────────────────────────────────────────

describe("generateVexSchema — collection exports", () => {
  it("exports each collection using its slug as the const name", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: url() } }),
        defineCollection({ slug: "authors", fields: { name: url() } }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("export const posts = defineTable({");
    expect(output.contents).toContain("export const authors = defineTable({");
  });

  it("generates a separate export block for each collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: url({ required: true }),
            views: number({ required: true }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("export const posts = defineTable({");
    expect(output.contents).toContain("title: v.string()");
    expect(output.contents).toContain("views: v.number()");
  });
});

// ─── Indexes ─────────────────────────────────────────────────────────────────

describe("generateVexSchema — indexes", () => {
  it("appends .index() chain for fields with an index property", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { slug: url({ required: true, index: "by_slug" }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain('.index("by_slug", ["slug"])');
  });

  it("appends multiple .index() chains for multiple indexed fields", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            slug: url({ required: true, index: "by_slug" }),
            authorId: url({ required: true, index: "by_author" }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain('.index("by_slug", ["slug"])');
    expect(output.contents).toContain('.index("by_author", ["authorId"])');
  });

  it("does not append .index() for fields without an index property", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: url({ required: true }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    // Scoped to `posts`' own block: `vex_versions` is emitted unconditionally
    // and always carries `.index("by_document_version", ...)`, so a whole-file
    // assertion can no longer hold.
    const postsStart = output.contents.indexOf("export const posts = defineTable({");
    const postsBlock = output.contents.slice(
      postsStart,
      output.contents.indexOf("export const", postsStart + 1),
    );
    expect(postsBlock).not.toContain(".index(");
  });
});

// ─── Search indexes ───────────────────────────────────────────────────────────

describe("generateVexSchema — searchIndex", () => {
  it("appends .searchIndex() chain for text fields with a searchIndex config", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({
              required: true,
              searchIndex: { name: "search_title", filterFields: ["status"] },
            }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain('.searchIndex("search_title",');
    expect(output.contents).toContain('searchField: "title"');
    expect(output.contents).toContain('filterFields: ["status"]');
  });

  it("generates empty filterFields array when filterFields is []", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({
              required: true,
              searchIndex: { name: "search_title", filterFields: [] },
            }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("filterFields: []");
  });
});

// ─── Integration ─────────────────────────────────────────────────────────────

describe("generateVexSchema — integration (full collection)", () => {
  it("generates a complete valid schema for a realistic collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: url({ required: true }),
            slug: url({ required: true, index: "by_slug" }),
            excerpt: url({ required: false }),
            views: number({ required: true }),
            published: checkbox({ required: false }),
            publishedAt: date({ required: false }),
            status: select({
              required: true,
              options: [
                { label: "Draft", value: "draft" },
                { label: "Published", value: "published" },
              ],
            }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });

    // update flag
    expect(output.update).toBe(true);

    // Header present
    expect(output.contents.split("\n")[0]).toBe(HEADER);

    // Imports
    expect(output.contents).toContain('import { defineTable } from "convex/server"');
    expect(output.contents).toContain('import { v } from "convex/values"');

    // Table export
    expect(output.contents).toContain("export const posts = defineTable({");

    // All fields
    expect(output.contents).toContain("title: v.string()");
    expect(output.contents).toContain("slug: v.string()");
    expect(output.contents).toContain("excerpt: v.optional(v.string())");
    expect(output.contents).toContain("views: v.number()");
    expect(output.contents).toContain("published: v.optional(v.boolean())");
    expect(output.contents).toContain("publishedAt: v.optional(v.number())");
    expect(output.contents).toContain(
      'status: v.array(v.union(v.literal("draft"), v.literal("published")))',
    );

    // Index
    expect(output.contents).toContain('.index("by_slug", ["slug"])');
  });
});

describe("generateVexSchema — versioned collections", () => {
  it("emits vex_status, vex_publishedAt, vex_publishedId, and both indexes for a collection with versions.drafts: true", () => {
    const posts = defineCollection({
      slug: "posts",
      fields: { title: text() },
      versions: { drafts: true },
    });
    const config = defineConfig({ collections: [posts] });
    const { contents } = generateVexSchema({ config });

    expect(contents).toContain(
      'vex_status: v.optional(v.union(v.literal("draft"), v.literal("published")))',
    );
    expect(contents).toContain("vex_publishedAt: v.optional(v.number())");
    expect(contents).toContain('vex_publishedId: v.optional(v.id("posts"))');
    expect(contents).toContain('.index("by_status", ["vex_status"])');
    expect(contents).toContain('.index("by_published", ["vex_publishedId"])');
  });

  it("does not emit versioning fields for a non-versioned collection in the same config", () => {
    const posts = defineCollection({
      slug: "posts",
      fields: { title: text() },
      versions: { drafts: true },
    });
    const authors = defineCollection({
      slug: "authors",
      fields: { name: text() },
    });
    const config = defineConfig({ collections: [posts, authors] });
    const { contents } = generateVexSchema({ config });

    // Scope to "authors"' own table block — asserting on `contents` as a
    // whole would pass vacuously since "posts" DOES emit these fields.
    const marker = "export const authors = defineTable({";
    const authorsStart = contents.indexOf(marker);
    expect(authorsStart).toBeGreaterThan(-1);
    const nextExportStart = contents.indexOf("export const", authorsStart + marker.length);
    const authorsBlock =
      nextExportStart === -1
        ? contents.slice(authorsStart)
        : contents.slice(authorsStart, nextExportStart);

    expect(authorsBlock).not.toContain("vex_status");
    expect(authorsBlock).not.toContain("vex_publishedAt");
    expect(authorsBlock).not.toContain("vex_publishedId");
    expect(authorsBlock).not.toContain("by_status");
    expect(authorsBlock).not.toContain("by_published");
  });

  it("emits vex_versions unconditionally, even when no collection or global declares drafts", () => {
    const config = defineConfig({
      collections: [defineCollection({ slug: "posts", fields: { title: text() } })],
    });
    const { contents } = generateVexSchema({ config });

    expect(contents).toContain("export const vex_versions = defineTable({");
    expect(contents).toContain("collection: v.string(),");
    expect(contents).toContain("documentId: v.string(),");
    expect(contents).toContain("version: v.number(),");
    expect(contents).toContain('status: v.union(v.literal("draft"), v.literal("published")),');
    expect(contents).toContain("snapshot: v.any(),");
    expect(contents).toContain("createdBy: v.optional(v.string()),");
    expect(contents).toContain("parentVersion: v.optional(v.number()),");
    expect(contents).toContain("restoredFrom: v.optional(v.number()),");
    expect(contents).toContain("publishedAt: v.optional(v.number()),");
    expect(contents).toContain(
      '.index("by_document_version", ["collection", "documentId", "version"])',
    );
  });
});

describe("generateVexSchema — globals", () => {
  it("emits vex_globals table when globals are registered", () => {
    const config = defineConfig({
      globals: [defineGlobal({ slug: "nav", label: "Nav", fields: {} as any })],
    });
    const { update, contents } = generateVexSchema({ config });
    expect(update).toBe(true);
    expect(contents).toContain("export const vex_globals = defineTable({");
    expect(contents).toContain("slug: v.string(),");
    expect(contents).toContain("data: v.any(),");
    expect(contents).toContain('.index("by_slug", ["slug"])');
  });

  it("does not emit vex_globals when no globals registered", () => {
    const config = defineConfig({ collections: [] });
    const { contents } = generateVexSchema({ config });
    expect(contents).not.toContain("vex_globals");
  });

  it("returns update: true when only globals are registered (no collections)", () => {
    const config = defineConfig({
      globals: [defineGlobal({ slug: "nav", label: "Nav", fields: {} as any })],
    });
    const { update } = generateVexSchema({ config });
    expect(update).toBe(true);
  });

  it("emits vex_status, vex_publishedAt, vex_publishedId, and both indexes on vex_globals when a registered global declares versions.drafts: true", () => {
    const nav = defineGlobal({
      slug: "nav",
      label: "Nav",
      fields: {} as any,
      versions: { drafts: true },
    });
    const config = defineConfig({ globals: [nav] });
    const { contents } = generateVexSchema({ config });

    // Scope to "vex_globals"' own table block — the unrelated `status`-shaped
    // field on the vex_versions block would otherwise false-pass a bare
    // `contents`-wide assertion.
    const marker = "export const vex_globals = defineTable({";
    const globalsStart = contents.indexOf(marker);
    expect(globalsStart).toBeGreaterThan(-1);
    const nextExportStart = contents.indexOf("export const", globalsStart + marker.length);
    const globalsBlock =
      nextExportStart === -1
        ? contents.slice(globalsStart)
        : contents.slice(globalsStart, nextExportStart);

    expect(globalsBlock).toContain(
      'vex_status: v.optional(v.union(v.literal("draft"), v.literal("published")))',
    );
    expect(globalsBlock).toContain("vex_publishedAt: v.optional(v.number())");
    expect(globalsBlock).toContain('vex_publishedId: v.optional(v.id("vex_globals"))');
    expect(globalsBlock).toContain('.index("by_status", ["vex_status"])');
    expect(globalsBlock).toContain('.index("by_published", ["vex_publishedId"])');
  });
});
