import type { VexConfig } from "../config/types";
import { collectionConfigToVexSchema } from "../collections";

function fail(contents: string) {
  return { update: false, contents };
}

function success(contents: string) {
  return { update: true, contents };
}

/**
 * Generates the full contents of `vex.schema.ts` from a resolved `VexConfig`.
 *
 * Returns `{ update: false, contents }` when there are no collections — the output
 * contains only the auto-generated header and no imports or table declarations.
 * Returns `{ update: true, contents }` when collections are present — the output
 * includes the header, `convex/server` and `convex/values` imports, and one
 * `export const` block per collection.
 *
 * @param props - Input props.
 * @param props.config - The fully resolved Vex configuration.
 * @returns An object with `update` (whether the file should be written to disk) and `contents` (the file string).
 *
 * @example
 * ```ts
 * const config = defineConfig({
 *   collections: [
 *     defineCollection({ slug: "posts", fields: { title: text() } }),
 *   ],
 * });
 * const { update, contents } = generateVexSchema({ config });
 * // update   → true
 * // contents → '// ⚠️ AUTO-GENERATED BY VEX CMS ...\nimport { defineTable } from "convex/server"\n...'
 * ```
 *
 * @see {@link collectionConfigToVexSchema} for the per-collection string builder
 * @see {@link VexConfig} for the resolved config shape
 */
export function generateVexSchema(props: { config: VexConfig }): {
  update: boolean;
  contents: string;
} {
  let header = `// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️\n// Run 'vex dev' or 'vex generate' to update this file.\n`;
  if (props.config.collections.length < 1) {
    return fail(header);
  }

  let imports = `import { defineTable } from "convex/server"\nimport { v } from "convex/values"\n`;
  let collections = props.config.collections
    .map((collection) => {
      return collectionConfigToVexSchema({ collection, config: props.config });
    })
    .join("\n");

  return success([header, imports, collections].join("\n"));
}
