import type { VexConfig } from "../config/types";
import { collectionConfigToVexSchema } from "../collections";

function fail(contents: string) {
  return { update: false, contents };
}

function success(contents: string) {
  return { update: true, contents };
}

/**
 * Generates the full contents of `vex.schema.ts` from a resolved `VexConfig`.
 *
 * Returns `{ update: false, contents }` when there are no collections — the output
 * contains only the auto-generated header and no imports or table declarations.
 * Returns `{ update: true, contents }` when collections are present — the output
 * includes the header, `convex/server` and `convex/values` imports, and one
 * `export const` block per collection.
 *
 * @param props - Input props.
 * @param props.config - The fully resolved Vex configuration.
 * @returns An object with `update` (whether the file should be written to disk) and `contents` (the file string).
 *
 * @example
 * ```ts
 * const config = defineConfig({
 *   collections: [
 *     defineCollection({ slug: "posts", fields: { title: text() } }),
 *   ],
 * });
 * const { update, contents } = generateVexSchema({ config });
 * // update   → true
 * // contents → '// ⚠️ AUTO-GENERATED BY VEX CMS ...\nimport { defineTable } from "convex/server"\n...'
 * ```
 *
 * @see {@link collectionConfigToVexSchema} for the per-collection string builder
 * @see {@link VexConfig} for the resolved config shape
 */
export function generateVexSchema(props: { config: VexConfig }): {
  update: boolean;
  contents: string;
} {
  // TODO: implement
  //
  // 1. Build the header comment (two lines):
  //    Line 1: "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️"
  //    Line 2: "// Run `vex dev` or `vex generate` to update this file."
  //    → Always present, even when there are no collections
  //
  // 2. If props.config.collections is empty, return just the header.
  //    → No imports, no table definitions needed
  //
  // 3. Build imports:
  //    import { defineTable } from "convex/server"
  //    import { v } from "convex/values"
  //    → Always include both when there are collections
  //
  // 4. For each collection in props.config.collections:
  //    a. Build the field entries block:
  //       - Iterate Object.entries(collection.fields) for [fieldKey, field]
  //       - Call adminFieldToValidator({ field }) to get the validator string
  //       - Format as: "  fieldKey: validatorString,"
  //       - Join with "\n"
  //    b. Build index chains (string[]):
  //       - For each [fieldKey, field] where field.index is defined:
  //         Push `.index("${field.index}", ["${fieldKey}"])`
  //       - Order: natural iteration order of fields
  //    c. Build searchIndex chains (string[]):
  //       - For each [fieldKey, field] where field.type === "text":
  //         Cast field to TextField
  //         If textField.searchIndex is defined:
  //           Push `.searchIndex("${textField.searchIndex.name}", {
  //             searchField: "${fieldKey}",
  //             filterFields: ${JSON.stringify(textField.searchIndex.filterFields)},
  //           })`
  //       - Append after index chains
  //    d. Build the table declaration:
  //       "export const {slug} = defineTable({\n{fieldBlock}\n})" + chains.join("")
  //
  // 5. Join all table declarations with "\n\n" and assemble the final string:
  //    [header, "", imports, "", ...tableDecls].join("\n")
  //    → Blank lines between header, imports, and each table
  //
  // Edge cases:
  // - Collection with no fields: generates "export const {slug} = defineTable({})" — valid but unusual
  // - Field with empty filterFields in searchIndex: generates filterFields: [] — valid
  // - Multiple indexes on the same collection: each becomes its own .index() chain
  // - Trailing comma on last field entry: always include — Prettier will normalize
  let header = `// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️\n// Run 'vex dev' or 'vex generate' to update this file.\n`;
  if (props.config.collections.length < 1) {
    return fail(header);
  }

  let imports = `import { defineTable } from "convex/server"\nimport { v } from "convex/values"\n`;
  let collections = props.config.collections
    .map((collection) => {
      return collectionConfigToVexSchema({ collection, config: props.config });
    })
    .join("\n");

  return success([header, imports, collections].join("\n"));
}
