/** Prefix written as line 1 of every file generated by `generateCollectionQueries`. Used by the CLI to detect and clean up stale generated files. */
export const GENERATED_HEADER = "// ⚠️ AUTO-GENERATED BY VEX CMS";

/** Relative import paths the CLI computes and passes to `generateCollectionQueries`. */
export interface CollectionQueryImports {
  generatedDirFromApi: string;
  generatedDirFromModel: string;
}

/**
 * Generates per-collection typed Convex API and model files.
 *
 * @returns A `Record<relativePath, fileContents>` map for the CLI to write under `convex/vex/`.
 */
export function generateCollectionQueries(_props: {
  config: import("../config/types").VexConfig;
  imports: CollectionQueryImports;
}): Record<string, string> {
  return {};
}
