import { describe, it, expect } from "vitest";
import { defineConfig, defineCollection } from "../index";
import { text, number, checkbox, date, select } from "../fields";
import { generateVexSchema } from "./generateVexSchema";

const HEADER = "// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️";

// ─── Header ──────────────────────────────────────────────────────────────────

describe("generateVexSchema — header", () => {
  it("always includes the auto-generated header on line 1", () => {
    const config = defineConfig();
    const output = generateVexSchema({ config });
    expect(output.contents.split("\n")[0]).toBe(HEADER);
  });

  it("returns only the header when there are no collections", () => {
    const config = defineConfig();
    const output = generateVexSchema({ config });
    expect(output.contents).not.toContain("defineTable");
    expect(output.contents).not.toContain("import");
  });

  it("returns update: false when there are no collections", () => {
    const config = defineConfig();
    const output = generateVexSchema({ config });
    expect(output.update).toBe(false);
  });
});

// ─── Imports ─────────────────────────────────────────────────────────────────

describe("generateVexSchema — imports", () => {
  it("includes convex/server and convex/values imports when there are collections", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain('import { defineTable } from "convex/server"');
    expect(output.contents).toContain('import { v } from "convex/values"');
  });

  it("returns update: true when there are collections", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.update).toBe(true);
  });
});

// ─── Fields ──────────────────────────────────────────────────────────────────

describe("generateVexSchema — field validators", () => {
  it("generates required text field as v.string()", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("title: v.string()");
  });

  it("generates optional text field as v.optional(v.string())", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { excerpt: text({ required: false }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("excerpt: v.optional(v.string())");
  });

  it("generates required number field as v.number()", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { views: number({ required: true }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("views: v.number()");
  });

  it("generates optional checkbox field as v.optional(v.boolean())", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { published: checkbox({ required: false }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("published: v.optional(v.boolean())");
  });

  it("generates optional date field as v.optional(v.number())", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { publishedAt: date({ required: false }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("publishedAt: v.optional(v.number())");
  });

  it("generates required select field as v.array(v.union(...))", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            status: select({
              required: true,
              options: [
                { label: "Draft", value: "draft" },
                { label: "Published", value: "published" },
              ],
            }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain(
      'status: v.array(v.union(v.literal("draft"), v.literal("published")))',
    );
  });
});

// ─── Exports ─────────────────────────────────────────────────────────────────

describe("generateVexSchema — collection exports", () => {
  it("exports each collection using its slug as the const name", () => {
    const config = defineConfig({
      collections: [
        defineCollection({ slug: "posts", fields: { title: text() } }),
        defineCollection({ slug: "authors", fields: { name: text() } }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("export const posts = defineTable({");
    expect(output.contents).toContain("export const authors = defineTable({");
  });

  it("generates a separate export block for each collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({ required: true }),
            views: number({ required: true }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("export const posts = defineTable({");
    expect(output.contents).toContain("title: v.string()");
    expect(output.contents).toContain("views: v.number()");
  });
});

// ─── Indexes ─────────────────────────────────────────────────────────────────

describe("generateVexSchema — indexes", () => {
  it("appends .index() chain for fields with an index property", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { slug: text({ required: true, index: "by_slug" }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain('.index("by_slug", ["slug"])');
  });

  it("appends multiple .index() chains for multiple indexed fields", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            slug: text({ required: true, index: "by_slug" }),
            authorId: text({ required: true, index: "by_author" }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain('.index("by_slug", ["slug"])');
    expect(output.contents).toContain('.index("by_author", ["authorId"])');
  });

  it("does not append .index() for fields without an index property", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: { title: text({ required: true }) },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).not.toContain(".index(");
  });
});

// ─── Search indexes ───────────────────────────────────────────────────────────

describe("generateVexSchema — searchIndex", () => {
  it("appends .searchIndex() chain for text fields with a searchIndex config", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({
              required: true,
              searchIndex: { name: "search_title", filterFields: ["status"] },
            }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain('.searchIndex("search_title",');
    expect(output.contents).toContain('searchField: "title"');
    expect(output.contents).toContain('filterFields: ["status"]');
  });

  it("generates empty filterFields array when filterFields is []", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({
              required: true,
              searchIndex: { name: "search_title", filterFields: [] },
            }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });
    expect(output.contents).toContain("filterFields: []");
  });
});

// ─── Integration ─────────────────────────────────────────────────────────────

describe("generateVexSchema — integration (full collection)", () => {
  it("generates a complete valid schema for a realistic collection", () => {
    const config = defineConfig({
      collections: [
        defineCollection({
          slug: "posts",
          fields: {
            title: text({ required: true }),
            slug: text({ required: true, index: "by_slug" }),
            excerpt: text({ required: false }),
            views: number({ required: true }),
            published: checkbox({ required: false }),
            publishedAt: date({ required: false }),
            status: select({
              required: true,
              options: [
                { label: "Draft", value: "draft" },
                { label: "Published", value: "published" },
              ],
            }),
          },
        }),
      ],
    });
    const output = generateVexSchema({ config });

    // update flag
    expect(output.update).toBe(true);

    // Header present
    expect(output.contents.split("\n")[0]).toBe(HEADER);

    // Imports
    expect(output.contents).toContain('import { defineTable } from "convex/server"');
    expect(output.contents).toContain('import { v } from "convex/values"');

    // Table export
    expect(output.contents).toContain("export const posts = defineTable({");

    // All fields
    expect(output.contents).toContain("title: v.string()");
    expect(output.contents).toContain("slug: v.string()");
    expect(output.contents).toContain("excerpt: v.optional(v.string())");
    expect(output.contents).toContain("views: v.number()");
    expect(output.contents).toContain("published: v.optional(v.boolean())");
    expect(output.contents).toContain("publishedAt: v.optional(v.number())");
    expect(output.contents).toContain(
      'status: v.array(v.union(v.literal("draft"), v.literal("published")))',
    );

    // Index
    expect(output.contents).toContain('.index("by_slug", ["slug"])');
  });
});
