import type { Metadata } from "next"

import { Geist, Geist_Mono, Inter } from "next/font/google"

import "./globals.css"
import Head from "next/head"

import ClientProviders from "~/components/providers/client"
import ServerProviders from "~/components/providers/server"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  auth,
  children,
}: Readonly<{
  auth: React.ReactNode
  children: React.ReactNode
}>) {
  return (
    <html className={inter.variable} lang="en">
      <Head>
        <link href="/favicons/favicon.ico" rel="shortcut icon" type="image/x-icon" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ServerProviders>
          <ClientProviders>
            {children}
            {auth}
          </ClientProviders>
        </ServerProviders>
      </body>
    </html>
  )
}
