"use client";

import { useRef } from "react";
import { useForm } from "@tanstack/react-form";
import type { ZodObject, ZodTypeAny } from "zod";
import type { VexField } from "@vexcms/core";
import {
  TextField,
  NumberField,
  CheckboxFieldForm,
  SelectField,
  DateField,
  ImageUrlField,
  MultiSelectField,
  UploadField,
} from "./fields";
import type { MediaDocument } from "../ui/media-picker";

interface MediaPickerState {
  results: MediaDocument[];
  searchTerm: string;
  setSearchTerm: (s: string) => void;
  canLoadMore: boolean;
  loadMore: () => void;
  isLoading: boolean;
  isSearching?: boolean;
  selectedMedia: MediaDocument | null;
}

interface FieldEntry {
  /** Field key name (e.g., "title", "status") */
  name: string;
  /** The VexField definition */
  field: VexField;
  /** Whether this field is read-only (e.g., user lacks update permission) */
  readOnly?: boolean;
}

interface AppFormProps {
  /** The Zod schema generated by generateFormSchema */
  schema: ZodObject<Record<string, ZodTypeAny>>;
  /** Ordered list of field entries to render */
  fieldEntries: FieldEntry[];
  /** Current document values (used as default/initial values) */
  defaultValues: Record<string, unknown>;
  /**
   * Called on valid form submit with only the changed fields
   * (or all fields when `submitAllFields` is true).
   * Return a promise — the form shows a loading state while it resolves.
   */
  onSubmit: (fields: Record<string, unknown>) => Promise<void>;
  /**
   * When true, submit sends all field values instead of only changed ones.
   * Use this for versioned collections where full snapshots are needed.
   */
  submitAllFields?: boolean;
  /** Optional form ID so an external button can submit via form="id" */
  formId?: string;
  /** Map of fieldName → MediaPickerState for upload fields */
  uploadFieldStates?: Record<string, MediaPickerState>;
  /** Called when an upload field's "Upload new" button is clicked */
  onOpenUploadModal?: (fieldName: string, collectionSlug: string) => void;
  /**
   * Custom renderer for upload fields.
   * When provided, this is used instead of the built-in UploadField component.
   * Allows the parent to wrap each upload field with its own hook-based state.
   */
  renderUploadField?: (props: {
    field: any;
    fieldDef: any;
    name: string;
    onUploadNew: () => void;
    defaultValue: unknown;
  }) => React.ReactNode;
  /**
   * Ref callback that receives a function to get current form values.
   * Use this to read form state without triggering a submit.
   */
  getValuesRef?: React.MutableRefObject<(() => Record<string, unknown>) | null>;
  /**
   * Called whenever the form's dirty state changes.
   * A form is dirty when any field value differs from its default value.
   */
  onDirtyChange?: (isDirty: boolean) => void;
}

/**
 * Subscribes to form value changes and calls onDirtyChange when
 * the dirty state changes. Uses form.Subscribe for reactive updates.
 */
function DirtyWatcher({
  form,
  fieldEntries,
  defaultValues,
  onDirtyChange,
}: {
  form: any;
  fieldEntries: FieldEntry[];
  defaultValues: Record<string, unknown>;
  onDirtyChange: (isDirty: boolean) => void;
}) {
  const prevDirtyRef = useRef(false);
  return (
    <form.Subscribe selector={(state: any) => state.values}>
      {(values: Record<string, unknown>) => {
        const isDirty = fieldEntries.some(
          (entry) => values[entry.name] !== defaultValues[entry.name],
        );
        if (isDirty !== prevDirtyRef.current) {
          prevDirtyRef.current = isDirty;
          // Defer to avoid setState during render
          setTimeout(() => onDirtyChange(isDirty), 0);
        }
        return null;
      }}
    </form.Subscribe>
  );
}

function AppForm({
  schema,
  fieldEntries,
  defaultValues,
  onSubmit,
  submitAllFields,
  formId,
  uploadFieldStates,
  onOpenUploadModal,
  renderUploadField,
  getValuesRef,
  onDirtyChange,
}: AppFormProps) {
  const form = useForm({
    defaultValues: defaultValues as Record<string, any>,
    validators: {
      onSubmit: schema,
    },
    onSubmit: async ({ value }) => {
      if (submitAllFields) {
        const allFields: Record<string, unknown> = {};
        for (const entry of fieldEntries) {
          allFields[entry.name] = value[entry.name];
        }
        await onSubmit(allFields);
        return;
      }
      const changedFields: Record<string, unknown> = {};
      for (const entry of fieldEntries) {
        const current = value[entry.name];
        const original = defaultValues[entry.name];
        if (current !== original) {
          changedFields[entry.name] = current;
        }
      }
      if (Object.keys(changedFields).length === 0) return;
      await onSubmit(changedFields);
    },
  });

  // Expose a getValues function so the parent can read current form state
  if (getValuesRef) {
    getValuesRef.current = () => {
      const values: Record<string, unknown> = {};
      for (const entry of fieldEntries) {
        values[entry.name] = form.state.values[entry.name];
      }
      return values;
    };
  }

  return (
    <form
      id={formId}
      onSubmit={(e) => {
        e.preventDefault();
        e.stopPropagation();
        form.handleSubmit();
      }}
    >
      {onDirtyChange && (
        <DirtyWatcher
          form={form}
          fieldEntries={fieldEntries}
          defaultValues={defaultValues}
          onDirtyChange={onDirtyChange}
        />
      )}
      <div className="space-y-6">
        {fieldEntries.map((entry) => (
          <form.Field key={entry.name} name={entry.name}>
            {(field) => {
              const fieldDef = entry.field;
              const readOnlyWrapper = (node: React.ReactNode) =>
                entry.readOnly ? (
                  <div className="opacity-60 pointer-events-none" aria-disabled="true">
                    {node}
                  </div>
                ) : node;

              switch (fieldDef.type) {
                case "text":
                  return readOnlyWrapper(
                    <TextField field={field} fieldDef={fieldDef} name={entry.name} />
                  );
                case "number":
                  return readOnlyWrapper(
                    <NumberField field={field} fieldDef={fieldDef} name={entry.name} />
                  );
                case "checkbox":
                  return readOnlyWrapper(
                    <CheckboxFieldForm
                      field={field}
                      fieldDef={fieldDef}
                      name={entry.name}
                    />
                  );
                case "select":
                  if (fieldDef.hasMany) {
                    return readOnlyWrapper(
                      <MultiSelectField
                        field={field}
                        fieldDef={fieldDef}
                        name={entry.name}
                      />
                    );
                  }
                  return readOnlyWrapper(
                    <SelectField field={field} fieldDef={fieldDef} name={entry.name} />
                  );
                case "date":
                  return readOnlyWrapper(
                    <DateField field={field} fieldDef={fieldDef} name={entry.name} />
                  );
                case "imageUrl":
                  return readOnlyWrapper(
                    <ImageUrlField
                      field={field}
                      fieldDef={fieldDef}
                      name={entry.name}
                    />
                  );
                case "upload": {
                  const uploadNew = () =>
                    onOpenUploadModal?.(entry.name, fieldDef.to);

                  if (renderUploadField) {
                    return readOnlyWrapper(renderUploadField({
                      field,
                      fieldDef,
                      name: entry.name,
                      onUploadNew: uploadNew,
                      defaultValue: defaultValues[entry.name],
                    }));
                  }

                  const pickerState = uploadFieldStates?.[entry.name];
                  return readOnlyWrapper(
                    <UploadField
                      field={field}
                      fieldDef={fieldDef}
                      name={entry.name}
                      mediaResults={pickerState?.results ?? []}
                      searchTerm={pickerState?.searchTerm ?? ""}
                      onSearchChange={pickerState?.setSearchTerm ?? (() => {})}
                      canLoadMore={pickerState?.canLoadMore ?? false}
                      onLoadMore={pickerState?.loadMore ?? (() => {})}
                      isLoading={pickerState?.isLoading ?? false}
                      onUploadNew={uploadNew}
                      selectedMedia={pickerState?.selectedMedia}
                    />
                  );
                }
                default:
                  return null;
              }
            }}
          </form.Field>
        ))}
      </div>
    </form>
  );
}

export { AppForm, type AppFormProps, type FieldEntry, type MediaPickerState };
