"use client";

import { useForm } from "@tanstack/react-form";
import type { ZodObject, ZodTypeAny } from "zod";
import type { VexField } from "@vexcms/core";
import { Button } from "../ui/button";
import {
  TextField,
  NumberField,
  CheckboxFieldForm,
  SelectField,
  DateField,
  ImageUrlField,
} from "./fields";

interface FieldEntry {
  /** Field key name (e.g., "title", "status") */
  name: string;
  /** The VexField definition */
  field: VexField;
}

interface AppFormProps {
  /** The Zod schema generated by generateFormSchema */
  schema: ZodObject<Record<string, ZodTypeAny>>;
  /** Ordered list of field entries to render */
  fieldEntries: FieldEntry[];
  /** Current document values (used as default/initial values) */
  defaultValues: Record<string, unknown>;
  /**
   * Called on valid form submit with only the changed fields.
   * Return a promise — the form shows a loading state while it resolves.
   */
  onSubmit: (changedFields: Record<string, unknown>) => Promise<void>;
  /** Whether the form is currently saving */
  isSaving?: boolean;
}

function AppForm({
  schema,
  fieldEntries,
  defaultValues,
  onSubmit,
  isSaving,
}: AppFormProps) {
  const form = useForm({
    defaultValues: defaultValues as Record<string, any>,
    validators: {
      onSubmit: schema,
    },
    onSubmit: async ({ value }) => {
      const changedFields: Record<string, unknown> = {};
      for (const entry of fieldEntries) {
        const current = value[entry.name];
        const original = defaultValues[entry.name];
        if (current !== original) {
          changedFields[entry.name] = current;
        }
      }
      if (Object.keys(changedFields).length === 0) return;
      await onSubmit(changedFields);
    },
  });

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        e.stopPropagation();
        form.handleSubmit();
      }}
    >
      <div className="space-y-6">
        {fieldEntries.map((entry) => (
          <form.Field key={entry.name} name={entry.name}>
            {(field) => {
              const meta = entry.field._meta;

              switch (meta.type) {
                case "text":
                  return (
                    <TextField field={field} meta={meta} name={entry.name} />
                  );
                case "number":
                  return (
                    <NumberField field={field} meta={meta} name={entry.name} />
                  );
                case "checkbox":
                  return (
                    <CheckboxFieldForm
                      field={field}
                      meta={meta}
                      name={entry.name}
                    />
                  );
                case "select":
                  return (
                    <SelectField field={field} meta={meta} name={entry.name} />
                  );
                case "date":
                  return (
                    <DateField field={field} meta={meta} name={entry.name} />
                  );
                case "imageUrl":
                  return (
                    <ImageUrlField
                      field={field}
                      meta={meta}
                      name={entry.name}
                    />
                  );
                default:
                  return null;
              }
            }}
          </form.Field>
        ))}
      </div>

      <div className="mt-8">
        <Button type="submit" disabled={isSaving || fieldEntries.length === 0}>
          {isSaving ? "Saving..." : "Save"}
        </Button>
      </div>
    </form>
  );
}

export { AppForm, type AppFormProps, type FieldEntry };
