"use client";

import { useRef, useEffect } from "react";
import { useForm } from "@tanstack/react-form";
import type { ZodObject, ZodTypeAny } from "zod";
import type { VexField } from "@vexcms/core";
import {
  TextField,
  NumberField,
  CheckboxFieldForm,
  SelectField,
  DateField,
  ImageUrlField,
  MultiSelectField,
  UploadField,
  ObjectField,
  ArrayField,
  BlocksField,
  ColorField,
  TabsField,
  RelationshipField,
} from "./fields";
import { VexFormProvider } from "./VexFormProvider";
import type { MediaDocument } from "../ui/media-picker";

const CUSTOM_FIELD_ELIGIBLE_TYPES = new Set(["text", "number", "checkbox", "select"]);

interface MediaPickerState {
  results: MediaDocument[];
  searchTerm: string;
  setSearchTerm: (s: string) => void;
  canLoadMore: boolean;
  loadMore: () => void;
  isLoading: boolean;
  isSearching?: boolean;
  selectedMedia: MediaDocument | null;
}

interface FieldEntry {
  /** Field key name (e.g., "title", "status") */
  name: string;
  /** The VexField definition */
  field: VexField;
  /** Whether this field is read-only (e.g., user lacks update permission) */
  readOnly?: boolean;
}

interface AppFormProps {
  /** The Zod schema generated by generateFormSchema */
  schema: ZodObject<Record<string, ZodTypeAny>>;
  /** Ordered list of field entries to render */
  fieldEntries: FieldEntry[];
  /** Current document values (used as default/initial values) */
  defaultValues: Record<string, unknown>;
  /**
   * Called on valid form submit with only the changed fields
   * (or all fields when `submitAllFields` is true).
   * Return a promise — the form shows a loading state while it resolves.
   */
  onSubmit: (fields: Record<string, unknown>) => Promise<void>;
  /**
   * When true, submit sends all field values instead of only changed ones.
   * Use this for versioned collections where full snapshots are needed.
   */
  submitAllFields?: boolean;
  /** Optional form ID so an external button can submit via form="id" */
  formId?: string;
  /** Map of fieldName → MediaPickerState for upload fields */
  uploadFieldStates?: Record<string, MediaPickerState>;
  /** Called when an upload field's "Upload new" button is clicked */
  onOpenUploadModal?: (fieldName: string, collectionSlug: string) => void;
  /**
   * Custom renderer for upload fields.
   * When provided, this is used instead of the built-in UploadField component.
   * Allows the parent to wrap each upload field with its own hook-based state.
   */
  renderUploadField?: (props: {
    field: any;
    fieldDef: any;
    name: string;
    onUploadNew: () => void;
    defaultValue: unknown;
  }) => React.ReactNode;
  /**
   * Ref callback that receives a function to get current form values.
   * Use this to read form state without triggering a submit.
   */
  getValuesRef?: React.MutableRefObject<(() => Record<string, unknown>) | null>;
  /**
   * Called whenever the form's dirty state changes.
   * A form is dirty when any field value differs from its default value.
   */
  onDirtyChange?: (isDirty: boolean) => void;
  /**
   * Called whenever any form field value changes.
   * Receives all current form values. Use this for live preview snapshot writes.
   */
  onValuesChange?: (values: Record<string, unknown>) => void;
  /**
   * Custom renderer for richtext fields.
   * The admin panel provides this to inject the editor adapter component.
   * If not provided, richtext fields render as a JSON textarea fallback.
   */
  renderRichTextField?: (props: {
    field: any;
    fieldDef: any;
    name: string;
    /** Media picker results from the media collection. */
    mediaResults?: MediaDocument[];
    mediaSearchTerm?: string;
    onMediaSearchChange?: (term: string) => void;
    mediaCanLoadMore?: boolean;
    onMediaLoadMore?: () => void;
    mediaIsLoading?: boolean;
    /** Opens the upload modal for the media collection. */
    onUploadNew?: () => void;
    /** Generates a presigned upload URL for direct file upload. */
    generateUploadUrl?: () => Promise<string>;
    /** Creates a media document after upload. Returns the document ID. */
    createMediaDocument?: (props: {
      collectionSlug: string;
      fields: Record<string, unknown>;
    }) => Promise<string>;
  }) => React.ReactNode;
  /**
   * VEX config — passed to RelationshipField so it can look up
   * the target collection's useAsTitle for display labels.
   */
  config?: any;
  /**
   * Renders a create document dialog for a given collection slug.
   * Used by RelationshipField to create new related documents inline.
   */
  renderCreateDialog?: (props: {
    collectionSlug: string;
    open: boolean;
    onClose: () => void;
    onCreated: (documentId: string) => void;
  }) => React.ReactNode;
}

/**
 * Subscribes to form value changes and calls onDirtyChange when
 * the dirty state changes. Uses form.Subscribe for reactive updates.
 */
function DirtyWatcher({
  form,
  fieldEntries,
  defaultValues,
  onDirtyChange,
}: {
  form: any;
  fieldEntries: FieldEntry[];
  defaultValues: Record<string, unknown>;
  onDirtyChange: (isDirty: boolean) => void;
}) {
  const prevDirtyRef = useRef(false);
  return (
    <form.Subscribe selector={(state: any) => state.values}>
      {(values: Record<string, unknown>) => {
        const isDirty = fieldEntries.some(
          (entry) => values[entry.name] !== defaultValues[entry.name],
        );
        if (isDirty !== prevDirtyRef.current) {
          prevDirtyRef.current = isDirty;
          // Defer to avoid setState during render
          setTimeout(() => onDirtyChange(isDirty), 0);
        }
        return null;
      }}
    </form.Subscribe>
  );
}

function AppForm({
  schema,
  fieldEntries,
  defaultValues,
  onSubmit,
  submitAllFields,
  formId,
  uploadFieldStates,
  onOpenUploadModal,
  renderUploadField,
  getValuesRef,
  onDirtyChange,
  onValuesChange,
  renderRichTextField,
  config,
  renderCreateDialog,
}: AppFormProps) {
  const form = useForm({
    defaultValues: defaultValues as Record<string, any>,
    validators: {
      onSubmit: ({ value }: { value: Record<string, any> }) => {
        const result = schema.safeParse(value);
        if (!result.success) {
          console.error("[VEX] Form validation failed:", result.error.issues);
          return result.error.issues.map((i: any) => i.message).join(", ");
        }
        return undefined;
      },
    },
    onSubmit: async ({ value }) => {
      const collected = collectFormValues(value);
      if (submitAllFields) {
        await onSubmit(collected);
        return;
      }
      const changedFields: Record<string, unknown> = {};
      for (const [key, current] of Object.entries(collected)) {
        const original = defaultValues[key];
        if (JSON.stringify(current) !== JSON.stringify(original)) {
          changedFields[key] = current;
        }
      }
      if (Object.keys(changedFields).length === 0) return;
      await onSubmit(changedFields);
    },
  });

  /**
   * Collect form values from field entries, expanding tabs into their slug keys.
   * Used by onSubmit, getValuesRef, and onValuesChange.
   */
  function collectFormValues(values: Record<string, any>): Record<string, unknown> {
    const result: Record<string, unknown> = {};
    for (const entry of fieldEntries) {
      if (entry.field.type === "ui") continue;
      if (entry.field.type === "tabs") {
        // Tabs expand: collect each tab's slug key from form values
        for (const tab of (entry.field as any).tabs) {
          result[tab.slug] = values[tab.slug];
        }
      } else {
        result[entry.name] = values[entry.name];
      }
    }
    return result;
  }

  // Dev-mode validation for custom components on ineligible field types
  if (process.env.NODE_ENV !== "production") {
    for (const entry of fieldEntries) {
      const fieldDef = entry.field;
      if (
        fieldDef.admin?.components?.Field &&
        !CUSTOM_FIELD_ELIGIBLE_TYPES.has(fieldDef.type) &&
        fieldDef.type !== "ui"
      ) {
        console.error(
          `[VEX] admin.components.Field on "${entry.name}" (type: "${fieldDef.type}") ` +
            `will be ignored. Custom Field components are only supported on: ` +
            `text, number, checkbox, select, and ui fields.`,
        );
      }
    }
  }

  // Expose a getValues function so the parent can read current form state
  if (getValuesRef) {
    getValuesRef.current = () => collectFormValues(form.state.values);
  }

  // Subscribe to form value changes for live preview.
  // The subscription is always active — onValuesChangeRef is checked inside
  // the callback so it works when preview is toggled on after mount.
  const onValuesChangeRef = useRef(onValuesChange);
  onValuesChangeRef.current = onValuesChange;
  useEffect(() => {
    const unsubscribe = form.store.subscribe(() => {
      if (!onValuesChangeRef.current) return;
      onValuesChangeRef.current(collectFormValues(form.state.values));
    });
    return unsubscribe;
  }, [form, fieldEntries]);

  return (
    <form
      id={formId}
      onSubmit={(e) => {
        e.preventDefault();
        e.stopPropagation();
        form.handleSubmit();
      }}
    >
      <VexFormProvider form={form} fieldEntries={fieldEntries}>
        {onDirtyChange && (
          <DirtyWatcher
            form={form}
            fieldEntries={fieldEntries}
            defaultValues={defaultValues}
            onDirtyChange={onDirtyChange}
          />
        )}
        <div className="space-y-6">
          {fieldEntries.map((entry) => {
            const fieldDef = entry.field;

            // Tabs render outside form.Field — they create their own form fields
            if (fieldDef.type === "tabs") {
              return (
                <TabsField
                  key={entry.name}
                  fieldDef={fieldDef as any}
                  name={entry.name}
                  renderField={({ fieldName, fieldPath, field: subFieldDef }) => (
                    <form.Field key={fieldPath} name={fieldPath as any}>
                      {(subField: any) => renderFieldByType(subField, subFieldDef, fieldName)}
                    </form.Field>
                  )}
                />
              );
            }

            // Custom Field component (ui fields and eligible types)
            if (fieldDef.admin?.components?.Field) {
              if (
                CUSTOM_FIELD_ELIGIBLE_TYPES.has(fieldDef.type) ||
                fieldDef.type === "ui"
              ) {
                const CustomField = fieldDef.admin.components.Field;
                return (
                  <CustomField
                    key={entry.name}
                    name={entry.name}
                    fieldDef={fieldDef}
                    readOnly={
                      entry.readOnly ?? fieldDef.admin?.readOnly ?? false
                    }
                  />
                );
              }
            }

            // ui fields without custom component
            if (fieldDef.type === "ui") {
              return null;
            }

            return (
            <form.Field key={entry.name} name={entry.name}>
              {(field) => renderFieldByType(field, fieldDef, entry.name, entry.readOnly)}
            </form.Field>
            );
          })}
        </div>
      </VexFormProvider>
    </form>
  );

  // Centralized field renderer — used by top-level and recursively by tabs
  function renderFieldByType(
                  renderField: any,
                  renderFieldDef: any,
                  renderName: string,
                  renderReadOnly?: boolean,
                ): React.ReactNode {
                  const wrap = (node: React.ReactNode) =>
                    renderReadOnly ? (
                      <div className="opacity-60 pointer-events-none" aria-disabled="true">
                        {node}
                      </div>
                    ) : (
                      node
                    );

                  switch (renderFieldDef.type) {
                    case "text":
                      return wrap(<TextField field={renderField} fieldDef={renderFieldDef} name={renderName} />);
                    case "number":
                      return wrap(<NumberField field={renderField} fieldDef={renderFieldDef} name={renderName} />);
                    case "checkbox":
                      return wrap(<CheckboxFieldForm field={renderField} fieldDef={renderFieldDef} name={renderName} />);
                    case "select":
                      if (renderFieldDef.hasMany) {
                        return wrap(<MultiSelectField field={renderField} fieldDef={renderFieldDef} name={renderName} />);
                      }
                      return wrap(<SelectField field={renderField} fieldDef={renderFieldDef} name={renderName} />);
                    case "date":
                      return wrap(<DateField field={renderField} fieldDef={renderFieldDef} name={renderName} />);
                    case "imageUrl":
                      return wrap(<ImageUrlField field={renderField} fieldDef={renderFieldDef} name={renderName} />);
                    case "upload": {
                      const uploadNew = () => onOpenUploadModal?.(renderName, renderFieldDef.to);
                      if (renderUploadField) {
                        return wrap(renderUploadField({
                          field: renderField, fieldDef: renderFieldDef, name: renderName,
                          onUploadNew: uploadNew, defaultValue: defaultValues[renderName],
                        }));
                      }
                      const pickerState = uploadFieldStates?.[renderName];
                      return wrap(
                        <UploadField
                          field={renderField} fieldDef={renderFieldDef} name={renderName}
                          mediaResults={pickerState?.results ?? []} searchTerm={pickerState?.searchTerm ?? ""}
                          onSearchChange={pickerState?.setSearchTerm ?? (() => {})}
                          canLoadMore={pickerState?.canLoadMore ?? false}
                          onLoadMore={pickerState?.loadMore ?? (() => {})}
                          isLoading={pickerState?.isLoading ?? false}
                          onUploadNew={uploadNew} selectedMedia={pickerState?.selectedMedia}
                        />,
                      );
                    }
                    case "object":
                      return wrap(
                        <ObjectField
                          field={renderField}
                          fieldDef={renderFieldDef}
                          name={renderName}
                          renderField={({ fieldName, fieldPath, field: subFieldDef }) => (
                            <form.Field key={fieldPath} name={fieldPath as any}>
                              {(subField: any) => renderFieldByType(subField, subFieldDef, fieldName)}
                            </form.Field>
                          )}
                        />,
                      );
                    case "array":
                      return wrap(
                        <ArrayField
                          field={renderField}
                          fieldDef={renderFieldDef}
                          name={renderName}
                          renderField={({ field: syntheticField, fieldDef: subFieldDef, name: subName }) =>
                            renderFieldByType(syntheticField, subFieldDef, subName)
                          }
                        />,
                      );
                    case "blocks":
                      return wrap(
                        <BlocksField
                          field={renderField}
                          fieldDef={renderFieldDef}
                          name={renderName}
                          renderField={({ field: syntheticField, fieldDef: subFieldDef, name: subName }) =>
                            renderFieldByType(syntheticField, subFieldDef, subName)
                          }
                        />,
                      );
                    case "color":
                      return wrap(<ColorField field={renderField} fieldDef={renderFieldDef} name={renderName} />);
                    case "tabs":
                      return (
                        <TabsField
                          fieldDef={renderFieldDef}
                          name={renderName}
                          renderField={({ fieldName, fieldPath, field: subFieldDef }) => (
                            <form.Field key={fieldPath} name={fieldPath as any}>
                              {(subField: any) => renderFieldByType(subField, subFieldDef, fieldName)}
                            </form.Field>
                          )}
                        />
                      );
                    case "relationship":
                      return wrap(
                        <RelationshipField
                          field={renderField}
                          fieldDef={renderFieldDef}
                          name={renderName}
                          config={config}
                          renderCreateDialog={renderCreateDialog}
                        />,
                      );
                    case "richtext": {
                      if (renderRichTextField) {
                        return wrap(
                          renderRichTextField({
                            field: renderField,
                            fieldDef: renderFieldDef,
                            name: renderName,
                          }),
                        );
                      }
                      return wrap(
                        <div className="space-y-2">
                          <label className="text-sm font-medium">
                            {renderFieldDef.label ?? renderName}
                          </label>
                          <textarea
                            className="w-full min-h-[200px] rounded-md border p-3 font-mono text-sm"
                            value={JSON.stringify(renderField.state.value, null, 2)}
                            onChange={(e: any) => {
                              try {
                                renderField.handleChange(JSON.parse(e.target.value));
                              } catch {
                                // Invalid JSON
                              }
                            }}
                          />
                        </div>,
                      );
                    }
                    default:
                      return null;
                  }
                }

}

export { AppForm, type AppFormProps, type FieldEntry, type MediaPickerState };
