// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️
// Run 'vex dev' or 'vex generate' to update this file.

/* eslint-disable perfectionist/sort-union-types */
/* eslint-disable perfectionist/sort-interfaces */
/* eslint-disable perfectionist/sort-modules */

import type { Id } from "@convex/_generated/dataModel"
import type { VexDocument, VexDocumentGlobal } from "@vexcms/core"

export interface UserDocument extends VexDocument {
  _id: Id<"user">
  name: string
  email: string
  emailVerified: boolean
  image?: string
  createdAt: number
  updatedAt: number
  role?: string
  banned?: boolean
  banReason?: string
  banExpires?: number
  isAnonymous?: boolean
  userId?: string
  roles: string[]
}
export type HeroBlock = {
  blockType: "hero"
  blockName?: string
  id: string
  badgeText?: string
  badgeLink?: string
  heading: string
  subheading?: string
  primaryCtaLabel: string
  primaryCtaHref: string
  secondaryCtaLabel?: string
  secondaryCtaHref?: string
}

export type FeaturesBlock = {
  blockType: "features"
  blockName?: string
  id: string
  heading: string
  subheading?: string
  features: {
    title: string
    description: string
    /**
     * Lucide icon name
     */
    icon?: string
  }[]
}

export type HowItWorksBlock = {
  blockType: "how_it_works"
  blockName?: string
  id: string
  heading: string
  subheading?: string
  steps: {
    /**
     * Lucide icon name
     */
    icon?: string
    title: string
    description: string
  }[]
}

export type RoadmapBlock = {
  blockType: "roadmap"
  blockName?: string
  id: string
  heading: string
  subheading?: string
  items: {
    feature: string
    description?: string
    status: string[]
  }[]
}

export type CtaBlock = {
  blockType: "cta"
  blockName?: string
  id: string
  heading: string
  subheading?: string
  actions?: {
    label: string
    href: string
  }[]
}

export type FaqBlock = {
  blockType: "faq"
  blockName?: string
  id: string
  heading: string
  subheading?: string
  supportLink?: string
  items: {
    question: string
    answer: string
  }[]
}

export type PageBlock =
  HeroBlock | FeaturesBlock | HowItWorksBlock | RoadmapBlock | CtaBlock | FaqBlock

export interface PagesDocument extends VexDocument {
  _id: Id<"pages">
  title: string
  /**
   * URL-friendly page path
   */
  slug: string
  blocks?: PageBlock[]
  /**
   * Custom <title> tag. Falls back to page title if empty.
   */
  metaTitle?: string
  /**
   * Custom meta description for search results.
   */
  metaDescription?: string
  ogImage?: Id<"images">[]
}
export type HeaderBlock = {
  blockType: "header"
  blockName?: string
  id: string
  logoText?: string
  logoImage?: Id<"images">[]
  logoHref?: string
  menuItems?: {
    label: string
    href: string
  }[]
  actionButtons?: {
    label: string
    href: string
    variant?: string[]
  }[]
}

export interface HeadersDocument extends VexDocument {
  _id: Id<"headers">
  name: string
  content?: HeaderBlock[]
}
export type FooterBlock = {
  blockType: "footer"
  blockName?: string
  id: string
  logoText?: string
  logoImage?: Id<"images">[]
  copyright?: string
  links?: {
    label: string
    href: string
  }[]
  socialLinks?: {
    platform: string
    href: string
    /**
     * Lucide icon name
     */
    icon?: string
  }[]
}

export interface FootersDocument extends VexDocument {
  _id: Id<"footers">
  name: string
  content?: FooterBlock[]
}

export interface Theme extends VexDocument {
  _id: Id<"themes">
  /**
   * Internal identifier for this theme. Used for idempotent lookups and admin
   * display.
   */
  name: string
  /**
   * CSS font-family stack applied to --font-sans. The first available font wins, so
   * a stack naming an unloaded font degrades rather than breaking.
   */
  fontFamily?: string
  /**
   * Applied to the --radius custom property. Any CSS length.
   */
  radius?: string
  /**
   * Tokens emitted under :root.
   */
  light?: {
    background?: string
    foreground?: string
    card?: string
    cardForeground?: string
    popover?: string
    popoverForeground?: string
    primary?: string
    primaryForeground?: string
    secondary?: string
    secondaryForeground?: string
    muted?: string
    mutedForeground?: string
    accent?: string
    accentForeground?: string
    destructive?: string
    destructiveForeground?: string
    border?: string
    input?: string
    ring?: string
    chart1?: string
    chart2?: string
    chart3?: string
    chart4?: string
    chart5?: string
    sidebar?: string
    sidebarForeground?: string
    sidebarPrimary?: string
    sidebarPrimaryForeground?: string
    sidebarAccent?: string
    sidebarAccentForeground?: string
    sidebarBorder?: string
    sidebarRing?: string
  }
  /**
   * Tokens emitted under .dark.
   */
  dark?: {
    background?: string
    foreground?: string
    card?: string
    cardForeground?: string
    popover?: string
    popoverForeground?: string
    primary?: string
    primaryForeground?: string
    secondary?: string
    secondaryForeground?: string
    muted?: string
    mutedForeground?: string
    accent?: string
    accentForeground?: string
    destructive?: string
    destructiveForeground?: string
    border?: string
    input?: string
    ring?: string
    chart1?: string
    chart2?: string
    chart3?: string
    chart4?: string
    chart5?: string
    sidebar?: string
    sidebarForeground?: string
    sidebarPrimary?: string
    sidebarPrimaryForeground?: string
    sidebarAccent?: string
    sidebarAccentForeground?: string
    sidebarBorder?: string
    sidebarRing?: string
  }
}

export interface SessionDocument extends VexDocument {
  _id: Id<"session">
  expiresAt: number
  token: string
  createdAt: number
  updatedAt: number
  ipAddress?: string
  userAgent?: string
  userId: string
  impersonatedBy?: string
  activeOrganizationId?: string
}

export interface AccountDocument extends VexDocument {
  _id: Id<"account">
  accountId: string
  providerId: string
  userId: string
  accessToken?: string
  refreshToken?: string
  idToken?: string
  accessTokenExpiresAt?: number
  refreshTokenExpiresAt?: number
  scope?: string
  password?: string
  createdAt: number
  updatedAt: number
}

export interface VerificationDocument extends VexDocument {
  _id: Id<"verification">
  identifier: string
  value: string
  expiresAt: number
  createdAt: number
  updatedAt: number
}

export interface ApikeyDocument extends VexDocument {
  _id: Id<"apikey">
  configId: string
  name?: string
  start?: string
  referenceId: string
  prefix?: string
  key: string
  refillInterval?: number
  refillAmount?: number
  lastRefillAt?: number
  enabled?: boolean
  rateLimitEnabled?: boolean
  rateLimitTimeWindow?: number
  rateLimitMax?: number
  requestCount?: number
  remaining?: number
  lastRequest?: number
  expiresAt?: number
  createdAt: number
  updatedAt: number
  permissions?: string
  metadata?: string
}

export interface JwksDocument extends VexDocument {
  _id: Id<"jwks">
  publicKey: string
  privateKey: string
  createdAt: number
  expiresAt?: number
}

export interface OrganizationDocument extends VexDocument {
  _id: Id<"organization">
  name: string
  slug: string
  logo?: string
  createdAt: number
  metadata?: string
}

export interface MemberDocument extends VexDocument {
  _id: Id<"member">
  organizationId: string
  userId: string
  role: string
  createdAt: number
}

export interface InvitationDocument extends VexDocument {
  _id: Id<"invitation">
  organizationId: string
  email: string
  role?: string
  status: string
  expiresAt: number
  createdAt: number
  inviterId: string
}

export interface Image extends VexDocument {
  _id: Id<"images">
  filename: string
  alt: string
  mimeType: string
  size: number
  storageId: string
  deleted?: boolean
  src: string
  width?: number
  height?: number
}

export interface SiteSettingsGlobal extends VexDocumentGlobal<"siteSettings"> {
  /**
   * Used as fallback for logo text, page titles, and meta tags.
   */
  name: string
  description?: string
  /**
   * The theme applied to the public site.
   */
  activeTheme?: Id<"themes">[]
  /**
   * Optional. Leave empty and the admin panel uses the Active Theme.
   */
  adminTheme?: Id<"themes">[]
  /**
   * Site favicon image
   */
  favicon?: Id<"images">[]
  /**
   * Default <title> tag for the site
   */
  metaTitle?: string
  /**
   * Default meta description for SEO
   */
  metaDescription?: string
  /**
   * Default Open Graph image for social sharing
   */
  ogImage?: Id<"images">[]
  /**
   * @handle for Twitter cards
   */
  twitterHandle?: string
  /**
   * GA4 measurement ID (G-XXXXXXXXXX)
   */
  googleAnalyticsId?: string
}

export type CollectionSlug =
  | "user"
  | "pages"
  | "headers"
  | "footers"
  | "themes"
  | "session"
  | "account"
  | "verification"
  | "apikey"
  | "jwks"
  | "organization"
  | "member"
  | "invitation"
  | "images"

export type GlobalSlug = "siteSettings"

export type MediaCollectionSlug = "images"

export type StorageAdapterSlug = "convex"

export type DocumentBySlug = {
  user: UserDocument
  pages: PagesDocument
  headers: HeadersDocument
  footers: FootersDocument
  themes: Theme
  session: SessionDocument
  account: AccountDocument
  verification: VerificationDocument
  apikey: ApikeyDocument
  jwks: JwksDocument
  organization: OrganizationDocument
  member: MemberDocument
  invitation: InvitationDocument
  images: Image
}

export type GlobalDocumentBySlug = {
  siteSettings: SiteSettingsGlobal
}

declare module "@vexcms/core" {
  interface GeneratedVexTypes {
    CollectionSlug:
      | "user"
      | "pages"
      | "headers"
      | "footers"
      | "themes"
      | "session"
      | "account"
      | "verification"
      | "apikey"
      | "jwks"
      | "organization"
      | "member"
      | "invitation"
      | "images"
    GlobalSlug: "siteSettings"
    MediaCollectionSlug: "images"
    StorageAdapterSlug: "convex"
    DocumentBySlug: {
      user: UserDocument
      pages: PagesDocument
      headers: HeadersDocument
      footers: FootersDocument
      themes: Theme
      session: SessionDocument
      account: AccountDocument
      verification: VerificationDocument
      apikey: ApikeyDocument
      jwks: JwksDocument
      organization: OrganizationDocument
      member: MemberDocument
      invitation: InvitationDocument
      images: Image
    }
    GlobalDocumentBySlug: {
      siteSettings: SiteSettingsGlobal
    }
    CollectionsFieldTypeMap: {
      user: {
        text: "name" | "email" | "image" | "role" | "banReason" | "userId"
        checkbox: "emailVerified" | "banned" | "isAnonymous"
        date: "createdAt" | "updatedAt" | "banExpires"
        array: "roles"
      }
      pages: {
        text: "title" | "slug" | "metaTitle" | "metaDescription"
        blocks: "blocks"
        upload: "ogImage"
      }
      headers: {
        text: "name"
        blocks: "content"
      }
      footers: {
        text: "name"
        blocks: "content"
      }
      themes: {
        text: "name" | "fontFamily" | "radius"
        group: "light" | "dark"
      }
      session: {
        date: "expiresAt" | "createdAt" | "updatedAt"
        text:
          "token" | "ipAddress" | "userAgent" | "userId" | "impersonatedBy" | "activeOrganizationId"
      }
      account: {
        text:
          | "accountId"
          | "providerId"
          | "userId"
          | "accessToken"
          | "refreshToken"
          | "idToken"
          | "scope"
          | "password"
        date: "accessTokenExpiresAt" | "refreshTokenExpiresAt" | "createdAt" | "updatedAt"
      }
      verification: {
        text: "identifier" | "value"
        date: "expiresAt" | "createdAt" | "updatedAt"
      }
      apikey: {
        text:
          | "configId"
          | "name"
          | "start"
          | "referenceId"
          | "prefix"
          | "key"
          | "permissions"
          | "metadata"
        number:
          | "refillInterval"
          | "refillAmount"
          | "rateLimitTimeWindow"
          | "rateLimitMax"
          | "requestCount"
          | "remaining"
        date: "lastRefillAt" | "lastRequest" | "expiresAt" | "createdAt" | "updatedAt"
        checkbox: "enabled" | "rateLimitEnabled"
      }
      jwks: {
        text: "publicKey" | "privateKey"
        date: "createdAt" | "expiresAt"
      }
      organization: {
        text: "name" | "slug" | "logo" | "metadata"
        date: "createdAt"
      }
      member: {
        text: "organizationId" | "userId" | "role"
        date: "createdAt"
      }
      invitation: {
        text: "organizationId" | "email" | "role" | "status" | "inviterId"
        date: "expiresAt" | "createdAt"
      }
      images: {
        text: "filename" | "alt" | "mimeType" | "storageId" | "src"
        number: "size" | "width" | "height"
        checkbox: "deleted"
      }
    }
    GlobalsFieldTypeMap: {
      siteSettings: {
        text:
          | "name"
          | "description"
          | "metaTitle"
          | "metaDescription"
          | "twitterHandle"
          | "googleAnalyticsId"
        relationship: "activeTheme" | "adminTheme"
        upload: "favicon" | "ogImage"
      }
    }
    IndexFieldsBySlug: {
      user: { by_email: readonly ["email"] }
      pages: { by_slug: readonly ["slug"] }
      headers: { by_name: readonly ["name"] }
      footers: { by_name: readonly ["name"] }
      themes: { by_name: readonly ["name"] }
      session: { by_token: readonly ["token"]; by_userId: readonly ["userId"] }
      account: { by_userId: readonly ["userId"] }
      verification: { by_identifier: readonly ["identifier"] }
      apikey: {
        by_configId: readonly ["configId"]
        by_referenceId: readonly ["referenceId"]
        by_key: readonly ["key"]
      }
      jwks: {}
      organization: { by_slug: readonly ["slug"] }
      member: { by_organizationId: readonly ["organizationId"]; by_userId: readonly ["userId"] }
      invitation: { by_organizationId: readonly ["organizationId"]; by_email: readonly ["email"] }
      images: { by_deleted: readonly ["deleted"] }
    }
    CustomActionsBySlug: {}
    AuthSlugs: {
      user: "user"
      organization: "organization"
    }
  }
}
