// ⚠️ AUTO-GENERATED BY VEX CMS — DO NOT EDIT ⚠️

import { defineTable } from "convex/server"
import { v } from "convex/values"

/**
 * USER COLLECTIONS
 **/

export const articles = defineTable({
  name: v.string(),
  slug: v.string(),
  index: v.optional(v.number()),
}).index("by_name", ["name"])

export const posts = defineTable({
  slug: v.string(),
  featured: v.optional(v.boolean()),
  status: v.union(v.literal("draft"), v.literal("published"), v.literal("archived")),
  subtitle: v.string(),
  title: v.string(),
}).index("by_title", ["title"])

export const user = defineTable({
  name: v.string(),
  email: v.string(),
  emailVerified: v.boolean(),
  image: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
  role: v.array(v.string()),
  banned: v.optional(v.boolean()),
  banReason: v.optional(v.string()),
  banExpires: v.optional(v.number()),
  postCount: v.optional(v.number()),
})
  .index("by_name", ["name"])
  .index("by_email", ["email"])

export const categories = defineTable({
  name: v.string(),
  slug: v.string(),
  sortOrder: v.optional(v.number()),
}).index("by_name", ["name"])

/**
 * AUTH TABLES
 **/

export const session = defineTable({
  expiresAt: v.number(),
  token: v.string(),
  createdAt: v.number(),
  updatedAt: v.number(),
  ipAddress: v.optional(v.string()),
  userAgent: v.optional(v.string()),
  userId: v.id("user"),
  impersonatedBy: v.optional(v.string()),
})
  .index("by_token", ["token"])
  .index("by_userId", ["userId"])

export const account = defineTable({
  accountId: v.string(),
  providerId: v.string(),
  userId: v.id("user"),
  accessToken: v.optional(v.string()),
  refreshToken: v.optional(v.string()),
  idToken: v.optional(v.string()),
  accessTokenExpiresAt: v.optional(v.number()),
  refreshTokenExpiresAt: v.optional(v.number()),
  scope: v.optional(v.string()),
  password: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
}).index("by_userId", ["userId"])

export const verification = defineTable({
  identifier: v.string(),
  value: v.string(),
  expiresAt: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
}).index("by_identifier", ["identifier"])

export const apikey = defineTable({
  name: v.optional(v.string()),
  start: v.optional(v.string()),
  prefix: v.optional(v.string()),
  key: v.string(),
  userId: v.id("user"),
  refillInterval: v.optional(v.number()),
  refillAmount: v.optional(v.number()),
  lastRefillAt: v.optional(v.number()),
  enabled: v.optional(v.boolean()),
  rateLimitEnabled: v.optional(v.boolean()),
  rateLimitTimeWindow: v.optional(v.number()),
  rateLimitMax: v.optional(v.number()),
  requestCount: v.optional(v.number()),
  remaining: v.optional(v.number()),
  lastRequest: v.optional(v.number()),
  expiresAt: v.optional(v.number()),
  createdAt: v.number(),
  updatedAt: v.number(),
  permissions: v.optional(v.string()),
  metadata: v.optional(v.string()),
})
  .index("by_key", ["key"])
  .index("by_userId", ["userId"])
