import type { BlockComponentProps } from "@vexcms/react"

import { cn } from "@vexcms/react"
import { icons } from "lucide-react"

import type { HowItWorksBlock } from "~/vex.types"

import { Container } from "~/components/Container"
import { SectionHeader } from "~/components/SectionHeader"

export { howItWorksBlock } from "./config"

/** Past this many steps a four-up rail squeezes descriptions below a readable
 *  measure, so the grid drops to three columns. */
const WIDE_RAIL_LIMIT = 8

/**
 * HowItWorks — a numbered rail, not a timeline graphic.
 *
 * Origin UI's timeline supplies the connector idea; its `radix-ui`
 * `Slot.Root` polymorphism is dropped for concrete elements and its
 * dot-and-line SVG is replaced by border utilities, which cost nothing and
 * follow the theme.
 */
export default function HowItWorksBlockRenderer({ block }: BlockComponentProps) {
  const { heading, steps, subheading } = block as HowItWorksBlock
  const items = steps ?? []

  if (items.length === 0) {return null}

  return (
    <section className="py-14 md:py-20 xl:py-28">
      <Container>
        <SectionHeader heading={heading} subheading={subheading} />

        <ol
          className={cn(
            "grid list-none gap-8 md:grid-cols-2 md:gap-x-8 md:gap-y-10 xl:border-t xl:border-border xl:pt-6",
            items.length > WIDE_RAIL_LIMIT ? "xl:grid-cols-3" : "xl:grid-cols-4"
          )}
        >
          {items.map((step, index) => {
            const Glyph = step.icon ? icons[step.icon as keyof typeof icons] : undefined
            return (
              <li
                className="border-t border-border pt-4 xl:border-t-0 xl:pt-0"
                key={`${step.title}-${index}`}
              >
                <div className="flex items-baseline gap-3">
                  {/* Generated by the renderer, never a field — reordering the
                      array must not force an editor to renumber. */}
                  <span className="font-mono text-2xl leading-none font-semibold tracking-[-0.03em] text-primary tabular-nums">
                    {String(index + 1).padStart(2, "0")}
                  </span>
                  {/* The connector is what makes separate cells read as a
                      sequence, and is why the icon sits right, not left. The
                      last one is kept: it points at the CTA below. */}
                  <span aria-hidden className="h-px flex-1 bg-border" />
                  {Glyph ? (
                    <Glyph className="size-3.5 shrink-0 self-center text-muted-foreground/70" />
                  ) : null}
                </div>

                <h3 className="mt-4 text-[17px] leading-[1.35] font-semibold text-foreground">
                  {step.title}
                </h3>
                {step.description ? (
                  <p className="mt-2 text-sm leading-[1.6] text-pretty text-muted-foreground">
                    {step.description}
                  </p>
                ) : null}
              </li>
            )
          })}
        </ol>
      </Container>
    </section>
  )
}
